### ISSUE TITLE
RSS feed not properly working with Recent Datasets

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1000]
see; NCS-76

## Description
The RSS feed for Recent Datasets is not working. When I create a new Dataset the RSS feed is not updating to reflect this. The Events and News RSS feeds both work properly to update when new content is created.
## Steps to Reproduce
1. Create a new dataset on the website.
2. Go to https://xyz client/dataset/rss and you will see that the rss feed has not updated to include the newest dataset.

## Acceptance Criteria
When creating a new dataset the dataset rss feed should update to reflect it's creation.

**Comment by sheldonrampton** [comment]
I don't think DKAN as a product has an RSS feed at the path /dataset/rss. If that's the case, this is not a product bug and should be closed.
