### ISSUE TITLE
Problem with display of popup in Panelizer

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1002]
see CIVIC-768
## Description

When adding content a Data Dashboard node, I noticed a problem with the way the Panels popup displays buttons. Several of the buttons have text that wraps outside the button and is then obscured because the part of the text that wraps falls behind the button. 

see Jira ticket for screenshot and details

**Comment by sheldonrampton** [comment]
It appears that this issue is fixed in the master branch of DKAN, so this issue can probably be closed once DKAN 7.x-1.12 is released and we confirm that it is fixed there.
