### ISSUE TITLE
 Illegal choice error message is displayed when clicking the Next button within a Group

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1005]
See: NCS-27

## Description:
Illegal choice error message is displayed when clicking the Next button within a Group

Severity: Medium

## Instructions to reproduce: 

Go to https://xyzclient/groups and click on the Game and Fish logo. Scroll down and click on the Next button.

**Comment by acouch** [comment]
This is a duplicate of: https://github.com/NuCivic/dkan/issues/912
