### ISSUE TITLE
CSV Previews Don't work for Linked Files from non-CORS enabled Sources

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1013]
See NCS 54

## Description: 
Linked CSV files cannot be previewed if CORS is not enabled. For more information about CORS or enabling CORS see: http://enable-cors.org/

CSVs from non-CORS enabled sources can be previewed if they are imported into the datastore.

This is a restriction that we are not aware of a work around for.

**Comment by federicca** [comment]
Closing. Duplicate.
