### ISSUE TITLE
 RSS sender name is not consistent and issues receiving in Outlook

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1014]
See NCS - 65

## Description: 
Sender name shown in RSS feeds are not consistent which may also be preventing consistent reception of the RSS feeds

## Instructions to reproduce: 
The RSS feeds all work if these URLs are clicked on and viewed within a browser. However, when setting these up to be read by Outlook (my version is 2013) not all of the items come in for Recent Datasets. Then as new items are added to DKAN, it appears that only the News and Upcoming Events items are automatically updated. The Recent Datasets do not appear to update in Outlook – newly entered datasets don’t appear. I’m wondering if this is related to the inconsistent sender shown for each RSS type, for example, see the attached image ‘RSS inconsistent sender’. So two things to fix/assist me with: 1) Change the sender names to be the same as the RSS name (see attached image, the News is perfect, it is an example of what I’m looking to have for the other two RSS types), 2) identify and fix the issue with the Datasets feed not apparently working.
And finally, on a related note though I’m not sure if it impacts this issue, please see the ‘Current provider limit’ shown on images Esri and DKAN. The Esri RSS feed has a set value, the DKAN RSS feed does not. Perhaps this needs to be fixed as well; if it’s something that I can fix just let me know where, thanks.

**Comment by sheldonrampton** [comment]
This is not a product bug. DKAN doesn't have these RSS feeds. They were added as a custom feature to the North Dakota website. This ticket can be closed.
