### ISSUE TITLE
Fix s3 site db and files assets backups disappearing.

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1016]
See NCS - 80

## Description: 
The database and files backups are getting removed.
Yesterday I noticed this was happening for some client assets so I manually triggered a job to recreate them. Afterwards, I was able to successfully build some QA sites using these assets.
However, this morning again I noticed that assets are missing. This time it's the db backup

**Comment by dkinzer** [comment]
@jpasila this is not a dkan related issue.
