### ISSUE TITLE
Theme settings: Managed file: the file used in the field may not be referenced

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#1031]
## Description
 User is not able to change the site logo if a background image file has already been uploaded.

**issue 1:** Managed file: the file used in the field may not be referenced
https://www.drupal.org/node/979158

**issue 2:** Notice: Undefined index: #field_name
https://www.drupal.org/node/1903010#comment-10118508

## Steps to Reproduce
1. Navigate to the theme settings form for nuboot_radix
2. Upload a new image in the Hero Unit field and save, you may see this error
![screenshot_3_25_16__10_40_am](https://cloud.githubusercontent.com/assets/314172/14047599/d682147e-f276-11e5-9049-ec2163aef940.png)

3. Now upload a new file in the logo field. You will see this error:
![screenshot_3_25_16__10_47_am](https://cloud.githubusercontent.com/assets/314172/14047626/f9d52c18-f276-11e5-8440-da97ffd64961.png)

## Acceptance Criteria
- [ ]  I should be able to upload a custom hero image and a custom logo into the theme settings without errors
- [ ] If I upload a file with spaces in the name, the site should re-name the file with dashes
- [ ] If I enable the site name it should be a link to the front page

## Test Updates
- [ ]  Add test for uploading a hero image and custom logo
 
## PR
https://github.com/NuCivic/nuboot_radix/pull/73

**Comment by janette** [comment]
Hero image field needs file_usage_add() function:
https://www.drupal.org/node/979158.

**Comment by smielza** [comment]
Experiencing two errors. Thought it may be related to conflicts with unix and AFS permissions, but access to /files where our media is pointed to for upload is 755 (full access). Please help!

![Screen Shot 2019-11-07 at 2 11 15 PM](https://user-images.githubusercontent.com/57536238/68489018-4648d080-0214-11ea-8a1a-44a040d55479.png)
![image](https://user-images.githubusercontent.com/57536238/68489059-58c30a00-0214-11ea-8eff-2507ed004592.png)
