### ISSUE TITLE
Access to modify look and feel 

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1045]
## Description

As a user with the site manager role I should have permissions to configure theme settings and site settings.
## Steps to Reproduce
1. Create a user with the site manager role and log in as that user.
2. Try to add a custom logo, or a site slogan
## Tasks

Add permissions to site manager role
- [ ] Administer themes
  Allows user to manage custom logo, custom hero image, and custom fonts
- [ ] Administer site configuration
  Allows user to manage colorizer, site name and slogan
## Acceptance Criteria

As a site manager I should see links in the admin menu to access theme settings, colorizer, and site settings.
As a site manager I should be able to click those links and make adjustments to these configuration forms.
## Test Updates

Update permissions tests on test/features/theme.feature
• site manager can upload a custom logo
• site manager can upload a custom hero image
• site manager can change colorizer settings
• site manager can edit site name
• site manager can edit site slogan

**Comment by janette** [comment]
## On Hold
until it is confirmed that site managers should get these permissions

**Comment by janette** [comment]
1.13 command center menu adds this functionality
