### ISSUE TITLE
Project Open Data Validation Breaks after 1.11

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#1062]
Currently 7.x-1.x doesn't pass data.json validation because there a change in behavior for the token ``:url`` for the file upload field.

In DKAN 7.x-1.11 the output of the ``downloadURL`` for the resource of an uploaded file was:

<img width="781" alt="screen shot 2016-04-11 at 11 35 26 am" src="https://cloud.githubusercontent.com/assets/512243/14434957/206ed448-ffdb-11e5-8cd0-ff13d5872fd1.png">

In 7.x-1.x the output is:

<img width="525" alt="screen shot 2016-04-11 at 11 45 39 am" src="https://cloud.githubusercontent.com/assets/512243/14434963/2fed09c6-ffdb-11e5-8e06-b1945b767683.png">

I checked and the token dictating this has not changed ``[node:field-resources:Nth:field_link_remote_file] || [node:field-resources:Nth:field-upload:url]``. 

I could not find from cursory look what changed either in Drupal core or elsewhere to change the behavior of the token.

A quick fix would be to change the token to ``[node:field-resources:Nth:field_link_remote_file] || [site:url][node:field-resources:Nth:field-upload:url]`` which produces an added "/" in the url (``http://example.com//sites/default/files/file.csv``), change the token to ``[node:field-resources:Nth:field_link_remote_file] || [node:field-resources:Nth:field-upload:download-url]`` which produces a link like (``http://example.com/node/N/download``), or fix it in code by checking for "http" in code in the odsm module.

In code that could be done here: https://github.com/NuCivic/open_data_schema_map/blob/master/modules/open_data_schema_pod/open_data_schema_pod.module#L175

```php
global $base_url;
if (isset($dataset['downlowdURL']) && !filter_var($dataset['license'], downlowdURL) && filter_var($base_url . $dataset['downlowdURL'])) {
  $dataset['downlowdURL'] = $base_url . $dataset['downlowdURL'];
}
```

## Steps to Reproduce

* Check http://demo.getdkan.com/data.json. See any downloadURL field.

## Acceptance Criteria

* Uploaded files provide full absolute URL with domain in data.json.
* Uploaded files provide full absolute URL with domain in other endpoints

## Test Updates

* Add automated testing to validate data.json output.

**Comment by msolv** [comment]
Update: This issue is related with this: https://github.com/NuCivic/dkan/blob/7.x-1.x/modules/dkan/dkan_featured_topics/dkan_featured_topics.module#L113

**Comment by msolv** [comment]
PR: https://github.com/NuCivic/dkan/pull/1064 (It includes adding a Behat test for POD validation).
