### ISSUE TITLE
Chart Visualization not displaying % numbers that have decimals

### ISSUE THREAD

**Issue by fbrooks1056** [NuCivic/dkan#1063]
## Description
When viewing a Chart visualization that uses the 100,000% filter, points with decimals will not display at all.  
![image](https://cloud.githubusercontent.com/assets/10466565/14437315/49394ba0-ffe6-11e5-8824-7c5546dda713.png)

## Steps to Reproduce
1. Create a Chart Visualization using data with decimal points. Set the filter to 100,000%.
2. You'll see that anything with a decimal point will not appear but whole numbers will. 

## Ticket Reference
NCS-275

**Comment by topicus** [comment]
If you want to use decimals you need to use the formatter with decimals (100,000.00%). I've tried and seems like this is working fine.

<img width="1269" alt="screen shot 2016-05-20 at 4 23 05 pm" src="https://cloud.githubusercontent.com/assets/381224/15478514/2463d0da-20f1-11e6-8c4c-5e0a14fc1383.png">

Reopen if that's not the case.
