### ISSUE TITLE
Cannot link to Google Spreadsheet

### ISSUE THREAD

**Issue by Krista-Nuams** [NuCivic/dkan#1068]
## Description

As a Site Manager, I am trying to link to a public google spreadsheet https://docs.google.com/spreadsheets/d/1poOlLzFFqKIho6r83EADAXbEATiIkeDFTbOeXpSoHW8/edit#gid=0 as a resource so that I can create charts and dashboards with the resource.

When I add the link and click "Select," nothing happens. When I click "save" I get this error: 
The selected file edit?usp=sharing could not be referenced. Only files with the following extensions are allowed: csv html xls json xlsx doc docx rdf txt jpg png gif tiff pdf odf ods odt tsv geojson xml zip.
![screen shot 2016-04-13 at 4 15 16 pm](https://cloud.githubusercontent.com/assets/4095552/14507917/fa963716-0192-11e6-9a99-14da8d39b2a1.png)
## Steps to Reproduce
- Add a Resource to a dataset
- Insert the URL of the Google Spreadsheet
- Click Select
- Add a title
- Click Save
## Acceptance Criteria
- When I add a google sheet link to a Resource, it saves.
- I can create previews and dashboards with charts by using the Resource.

**Comment by federicca** [comment]
"Add a Resource to a dataset
Insert the URL of the Google Spreadsheet" is not expected behavior.

We'll revise the Google Spreadsheet backend from charts, where this functionality is supported.

**Comment by dafeder** [comment]
May be resolved by #739

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/dkan_dataset/pull/276

<img width="787" alt="dkan___the_site_slogan_thing_here" src="https://user-images.githubusercontent.com/314172/28216425-5057b3fe-6877-11e7-997f-ff2bf8d59393.png">
