### ISSUE TITLE
Charts in the visualization entity are not refreshed when the DKAN datastore is updated

### ISSUE THREAD

**Issue by lcshiung** [NuCivic/dkan#1076]
After updating the datastore, charts in the visualization entity continue to retain the old values (unless I explicitly go back to Step 1 to load data again). Is it possible to automatically refresh the charts after the datastore is updated?

**Comment by dafeder** [comment]
Hi @lcshiung we're testing this. It might be a caching issue. What is your server configuration like? Are you using Pantheon or another host with Varnish enabled?

**Comment by dafeder** [comment]
Actually, I responded before thinking this through sufficiently. The visualization entity chart is based on a resource's file whether the file has been imported to the datastore or not; it doesn't currently pull from the datastore. So if you replace the file on your resource, you will need to re-save the entity to make it point to the new file.

**Comment by dafeder** [comment]
Also, a clarification. The Visualization Entity Chart is built off of a resource's _file_, it can't build from the _datastore_ (for now). So you're saying you replaced the file, correct?

**Comment by lcshiung** [comment]
Yes, I was trying to build the chart based on the datastore. No worries, I will look for some other ways of doing this then.
