### ISSUE TITLE
Organic Groups security vulnerability DRUPAL-SA-CONTRIB-2016-023

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1079]
## Description

https://www.drupal.org/node/2710115

"Under the certain field configurations a user is able to subscribe without approval to group that requires approving the membership."

This security vulnerability in the [Organic Groups](http://drupal.org/project/og) module was reported on April 20, 2016. We have so far not been able to reproduce on a DKAN site. It also only makes the site vulnerable to malicious _registered users_. 

As this fix seems important but not urgent, we plan to put out a patch release in the next two weeks. If you have open user registration (not on by default) you may want to disable it until the fix is released.

**Comment by janette** [comment]
OG was upgraded here: https://github.com/NuCivic/dkan_dataset/pull/223
