### ISSUE TITLE
DKAN module version numbers are not correctly set on releases

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1083]
If we're not releasing on Drupal.org, we need an equivilant to the Drupal packaging script that will set the version number on release tags.

https://github.com/NuCivic/dkan/blob/7.x-1.12/modules/dkan/dkan_topics/dkan_topics.info
https://github.com/NuCivic/dkan_dataset/blob/7.x-1.12/dkan_dataset.info

**Comment by janette** [comment]
Done. Thanks Jenkins
