### ISSUE TITLE
Trying to get property of non-object in dkan_sitewide_update_status_alter() 

### ISSUE THREAD

**Issue by SmallhillCZ** [NuCivic/dkan#1102]
When site is not connected to internet, following error is shown in the administration:

`Notice: Trying to get property of non-object in function dkan_sitewide_update_status_alter() (line: 187 in file E:\Apache24\htdocs\profiles\dkan\modules\dkan\dkan_sitewide\dkan_sitewide.module).`

I fixed it by adding `if(!$tags) return;` after line 181, because I didn't have time to examine what is the purpose of the code.

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/dkan/pull/1804
