### ISSUE TITLE
Adding dataset is possible to a group user is not member of

### ISSUE THREAD

**Issue by SmallhillCZ** [NuCivic/dkan#1105]
It is possible to add a dataset to a group that current user is not member of.

In my configuration my user **does not have** a user role to add dataset, the organic group type **has** role to add a dataset. On the add dataset page all of the groups are available for selecting and when I proceed the dataset is created in the selected group (where I am not member of), but then I can't edit that dataset anymore.

**Comment by janette** [comment]
@SmallhillCZ the create/edit permissions for group content were fixed on the 1.13.3 release

Documentation on the roles and how they work is here http://dkan.readthedocs.io/en/latest/components/dataset/groups.html#roles-and-permissions

In summary:

**Content creator:** 
 - can create datasets and resources in a group they are a member of
 - can only edit their own content within the group

**Editor:** 
 - can create datasets and resources in a group they are a member of
 - can edit any content in a group they are a member of

**Site manager:** 
- can create/edit any content without being a member of the group
