### ISSUE TITLE
Site Managers cannot add Datasets to a Group unless a part of one Group or more (UX fix)

### ISSUE THREAD

**Issue by mcdougs** [NuCivic/dkan#1132]
## Description

Site Managers cannot add Datasets to a Group unless they themselves are a part of one or more Groups; Site Managers are not automatically assigned to any Groups when the user is created. Site Managers would not know that they need to add themselves to a Group in order to add a Dataset to a Group. 

The Site Manager user should be able to add Datasets to Groups without belonging to any Group. Lower-level users would still be required to belong to a Group to add Datasets to it. 
## Steps to Reproduce
1. Build or access existing demo site built with 7.x.1.x parameters
2. Create or login as site manager user not assigned to a Group. 
3. Go to _Add content_ and select Dataset. 
4. Scroll to sub-menu with options for url path, revisions, publish status and author info
   ![screen shot 2016-05-17 at 11 30 02 am](https://cloud.githubusercontent.com/assets/12161118/15332888/77963cea-1c35-11e6-998d-b8658da145b6.png)
5. The Groups options are not available. 
## Acceptance Criteria
- [ ] Site Manager users can add a Dataset to a Group without being a user within the Group.  
## Test Updates

Unknown
## Documentation Updates

Include instructional documentation for Site Managers and Group admins to add lower-level users to Groups in order to add Datasets to Groups.
## Ticket Reference

CIVIC-2546

**Comment by janette** [comment]
Related to: https://github.com/NuCivic/dkan/issues/1105

**Comment by dkinzer** [comment]
This is still an issue in 1.13.x and 1.12.x as of 1.13.1 and 1.12.13.  A further complication is that a belonging to the group is not enough, in order to have any kind of real access (update, reject, publish) the user will also need to be an administrator of the group as current default group permissions only allow for READ access.

**Comment by dkinzer** [comment]
REF CIVIC-5962

**Comment by janette** [comment]
## Clarification:
In **DKAN 1.13**, a user with the **site manager** role can add datasets to any group, and edit any group dataset, without belonging to the group.

A user with the **editor** role can not add datasets to a group unless a member of the group. And once they are a member of the group, they can not edit datasets created by other members unless they are given the group administrator role.
