### ISSUE TITLE
Visualization form error: spectrum is not a function

### ISSUE THREAD

**Issue by mcdougs** [NuCivic/dkan#1134]
## Description
The Query and Filter editors are broken when attempting to create a Chart on the bleeding edge install of DKAN. 
`recline.view.nvd3.controls.min.js?o7by1d:311 Uncaught TypeError: $(...).spectrum is not a function`
![screenshot_5_17_16__1_46_pm](https://cloud.githubusercontent.com/assets/314172/15334939/e480904e-1c35-11e6-8869-db5a79891cb2.png)

 
## Steps to Reproduce
 
1. Build or access existing demo site built with 7.x.1.x parameters. 
2. Add a new Chart (from anywhere on the site). 
3. Create a title for the Chart and scroll past the other fields to the _Preview and Adjust_ screen. 
4. Expand both the _Query editor_ and the _Filter editor_. The corner icon should appear as a minus sign and the fields are empty. 

![screen shot 2016-05-17 at 2 40 18 pm](https://cloud.githubusercontent.com/assets/12161118/15334710/5a3738b8-1c3d-11e6-96cd-3c6c7e984959.png)

## Acceptance Criteria

- [ ] The Query editor should have the appropriate field for performing a query on the Resource consumed by the Chart. 
- [ ] The Filter Editor should have fields to add new terms to filter the data in the Resource consumed by the Chart. 

 
## Test Updates

Unknown 

## Documentation Updates

Unknown

##NCS

CIVIC-2551

**Comment by janette** [comment]
This issue was a js error on the spectrum library which has been fixed
https://github.com/NuCivic/visualization_entity_charts/commit/ac8f67766a080c24bbdb9633e935a24441e36fc2
