### ISSUE TITLE
Consolidate categories on IPE

### ISSUE THREAD

**Issue by mcdougs** [NuCivic/dkan#1141]
## Description
When logged in as an admin on DKAN 1.11, the user sees multiple buttons that all say "visualzations" 

![screen shot 2016-05-20 at 3 39 53 pm](https://cloud.githubusercontent.com/assets/12161118/15441469/0ceba792-1ea9-11e6-939d-8aebd902a46e.png)

Each button has a different set of options to choose from:

![screen shot 2016-05-20 at 4 41 03 pm](https://cloud.githubusercontent.com/assets/12161118/15441592/c1ef957c-1ea9-11e6-99e1-9ef318362a28.png)

![screen shot 2016-05-20 at 4 40 54 pm](https://cloud.githubusercontent.com/assets/12161118/15441606/ccbb0fb8-1ea9-11e6-84cf-d2521195098c.png)

![screen shot 2016-05-20 at 4 40 46 pm](https://cloud.githubusercontent.com/assets/12161118/15441832/26d0bdd0-1eab-11e6-92ca-de10bcb98e3c.png)

 
## Steps to Reproduce

1. Create or login to 1.11 install of DKAN as admin user. 
2. Choose a page to customize and add content to any of the panels. 
3. Find Visualizations buttons in IPE
 
## Acceptance Criteria

There should only be one button for visualizations in the IPE selection menu. 
Use '_Visualizations_' as the category for all so that everything works with the new IPE changes in 1.12
 
## Test Updates
 
Unknown 

## Documentation Updates

Unknown
 
## Ticket Reference
CIVIC-2609

**Comment by dafeder** [comment]
This UI has been revamped in DKAN 7.x-1.12
