### ISSUE TITLE
Unable to extract a range of data from a certain field in the API

### ISSUE THREAD

**Issue by tqx94** [NuCivic/dkan#1144]
Hi, 

I have tried many codes in attempt to filter out a range of data in the api. For instance, I would like to extract data only from the dates from 2016-03-31 to2016-04-12 in the link: http://172.24.242.50/api/action/datastore/search.json?resource_id=6bd1a0d7-93c3-4e47-b77e-8dabdb13fcad . 
In general programming language, colon : is commonly used to extract data within a certain intervals. However, in dkan, I have made several attempts to extract the data, but to no avail. 
Below are some attempts that I had tried. 

http://172.24.242.50/api/action/datastore/search.json?resource_id=6bd1a0d7-93c3-4e47-b77e-8dabdb13fcad&filters[Date]=2016-03-31:2016-04-12 

http://172.24.242.50/api/action/datastore/search.json?resource_id=6bd1a0d7-93c3-4e47-b77e-8dabdb13fcad&q={Date=2016/04/12:2016/04/10}

Is there anyway for me to resolve this problem?

Thanks,

**Comment by dafeder** [comment]
Hi @tqx94 - at the moment the datastore API is very simple and only allows matching single values. We are planning to roll out more powerful querying abilities in the datastore API. What we have done as a workaround in the meantime when we've needed to consume more complex query results has been to write queries directly on the database using Drupal functions and use Services to expose them as custom endpoints.

You can see an example here, with a disclaimer that we haven't quite settled on a preferred strategy for this and the documentation is minimal.

https://github.com/NuCivic/react_dashboard
https://github.com/NuCivic/react_dashboard/blob/master/react_dashboard.module#L50

**Comment by dafeder** [comment]
Closing this, please re-open if you have more questions @tqx94

**Comment by tqx94** [comment]
thank you! :)
