### ISSUE TITLE
Remove Menu Options for Disabled Visualization Features

### ISSUE THREAD

**Issue by jasoneverettmiller** [NuCivic/dkan#1165]
## Description
When logged in as a Site Manager, the admin menu for Visualizations (in the main nav and under Add Content > Visualizations) includes links for Choropleth and GeoJSON, yet clicking those items simply takes the user to the Visualizations landing page with Charts as the only available option.

## Steps to Reproduce
1. Log-in as a Site Manager.
2. Rollover Visualizations in the admin menu, in the main nav and under Add Content > Visualizations.
3. Click on either Choropleth or GeoJSON.
4. Note that user is taken to Visualization landing page with Charts as the only option.

## Acceptance Criteria
When logged in as a Site Manager, there should be no menu options for visualization entities that are not enabled.

## Test Updates
To be completed by developer.
 
## Documentation Updates
To be completed by developer.

## Ticket Reference
CIVIC-2717

**Comment by dafeder** [comment]
This was fixed by NuCivic/dkan#1094 and will be included in a future release.
