### ISSUE TITLE
Site Manager not allowed to edit pages with HTML body

### ISSUE THREAD

**Issue by dkinzer** [NuCivic/dkan#1176]
## Description
The site manager is not able to edit the body field of a page if it was saved with the HTML filter because they do not have access to the HTML filter.

## Steps to Reproduce
* As the administrator create a page and save the body of the page using an HTML filter.
* As a site manager try to edit the page, you will be able to go to edit page but body field will have access protection enabled.

## Acceptance Criteria
- [ ] A site manager will be able to create and edit any page regardless of whether there is an HTML filter added to it.

## Test Updates
- [ ] A test should be added that includes access to the filter to avoid a regression

## Documenation Updates
N/A

**Comment by janette** [comment]
fix has been merged https://github.com/NuCivic/dkan/pull/1085
