### ISSUE TITLE
Site Manager Can't Assign Roles to New Users

### ISSUE THREAD

**Issue by jasoneverettmiller** [NuCivic/dkan#1180]
## Description
As a Site Manager creating a new user, I am not allowed to set the user's role in DKAN 7.x-1.12. 

## Steps to Reproduce
1. Create new user
2. Note there is no way to assign role.
 
## Acceptance Criteria
1. Site Manager should be allowed to assign Site Manager, Content Editor or Content Creator role to any new user.
 
## Test Updates
To be completed by developer.
 
## Documentation Updates
To be completed by developer.
 
## Issue Link
CIVIC-2811

**Comment by mcdougs** [comment]
Known issue; should fix with Admin Role Module https://www.drupal.org/project/adminrole

**Comment by dafeder** [comment]
This work was merged and will be included in the next patch release, 7.x-1.12.6
