### ISSUE TITLE
Broken link in readme for ticket template

### ISSUE THREAD

**Issue by jvitello** [NuCivic/dkan#1185]
## Description

The link in the readme for the ticket template is broken.
## Steps to Reproduce

Visit the readme page and try to click the ticket template link. It will take you to...
https://github.com/NuCivic/dkan/blob/7.x-1.x/CONTRIBUTING.md#new-feature-template
... which is returning a 404 for me.

This seems to be the correct link:
https://github.com/NuCivic/dkan/blob/7.x-1.x/.github/CONTRIBUTING.md#new-feature-template

![screen shot 2016-06-13 at 2 06 58 pm](https://cloud.githubusercontent.com/assets/5174815/16017973/65175a0e-3170-11e6-8260-2021116c1fac.png)

**Comment by janette** [comment]
Fixed
