### ISSUE TITLE
error on resource pages when visualizations are disabled

### ISSUE THREAD

**Issue by jvitello** [NuCivic/dkan#1187]
## Description

During an upgrade to 1.12, we encountered this error whenever we visited a resource page:
`EntityFieldQueryException: Unknown field: field_uuid_resource in EntityFieldQuery->addFieldCondition() (line 817 of /var/www/docroot/includes/entity.inc).`

We investigated and found that this error occurs when the visualization module is disabled (it is enabled by default). We wanted to have this disabled so that the visualization features would be hidden until we were prepared to train users on the new functionality.

This is a quasi bug/feature request:
As a site administrator
I need the option for new major functionality to be optionally disabled
So that I can upgrade the rest of the site without fielding questions from users on new functionality that will take a lot of time to prepare training
## Steps to Reproduce

Install DKAN 1.12 with the visualization module disabled.
## Acceptance Criteria

Given I have installed a version of DKAN 1.12
And I have disabled the visualization module

When I visit a resource page
I should not see any errors
## Test Updates

TBD
## Documenation Updates

TBD

**Comment by acouch** [comment]
I've created a solution at https://github.com/NuCivic/dkan_dataset/issues/272

**Comment by janette** [comment]
Merged via the dev-integration branch #281
