### ISSUE TITLE
Changing @font-your-face Settings for Standard Text Breaks Topic Icon Selector

### ISSUE THREAD

**Issue by jasoneverettmiller** [NuCivic/dkan#1202]
## Description

When the CSS Selector for Standard Text is modified by an Admin or Site Manager in the @font-your-face section, icons disappear when adding or editing topics.
## Steps to Reproduce
1. Log-in as Site Manager or Admin.
2. Go to /admin/appearance/fontyourface > Browse All Fonts and enable a new font.
3. Click on Enabled Fonts and change the font setting for CSS Selector to Standard Text for the font just enabled.
4. Click "Save applied fonts" to save new settings.
5. Navigate to /structure/taxonomy/dkan_topics and click Add Term.
6. Notice that icons are not visible.
## Acceptance Criteria
1. As an Admin or Site Manager, modifying the font settings for Standard Text in @font-your-face shouldn't make the icons disappear when adding a new Topic.
## Test Updates

Developer to update this section.
## Documentation Updates

Developer to update this section.

**Comment by janette** [comment]
Fixed here https://github.com/NuCivic/dkan/pull/1406
