### ISSUE TITLE
Undefined index "data" in open_data_schema_pod.module

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#1214]
Generic mimetypes like "data" or "rest" are not defined so cause an undefined index error in line 169 of open_data_schema_pod.module.

Mimetype is always required if there is a download: https://project-open-data.cio.gov/v1.1/schema/#distribution-downloadURL or url.

This can be fixed by updating https://github.com/NuCivic/open_data_schema_map/blob/master/modules/open_data_schema_pod/open_data_schema_pod.module#L169 to 

```
              $map = file_mimetype_mapping();
              // Use the format if the mimetype is not known. This is necessary
             // when the mimetype is not provided.
              $dataset['distribution'][$num]['mediaType'] =
                isset($map['extensions'][$dist['format']]) ?
                $map['mimetypes'][$map['extensions'][$dist['format']]] : t('unknown');
            }
```

This can be recreated by creating a dataset with a resource with a "data" type, viewing data.json, and then viewing the logs.

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/open_data_schema_map/commit/29cfa4375c8de25529280188e458d6d051cb267f
