### ISSUE TITLE
Features revert does not work in Open Data Schema Map

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#1216]
Currently features revert doesn't work on ODSM. To verify this change a field in and ODSM endpoint that is in features, run features revert, and notice that it doesn't revert.

There is a PR to fix this: https://github.com/NuCivic/open_data_schema_map/pull/42 

This fix is to make sure that the primary key is included. See https://api.drupal.org/api/drupal/includes!common.inc/function/drupal_write_record/7.x

> $primary_keys: To indicate that this is a new record to be inserted, omit this argument. If this is an update, this argument specifies the primary keys' field names.

**Comment by rhabbachi** [comment]
PR reviewed and merged.

**Comment by janette** [comment]
Fixed!
