### ISSUE TITLE
DKAN links not using relative paths in several places

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1225]
From the dev list:

> Hi Everyone,
I'm just getting started with DKAN and I'm running into trouble with maps and some other icons.  I've searched through everything I could find and our team has spent a few hours trying to > debug without any success.  
> 
I believe almost all of our issues are based on the base path for the system.  It looks like DKAN is configured to look for mysite.com.  Our process builds out to teamsites.com/mine/> dkan/.  The mine/dkan part of the URL is throwing a major wrench in the entire process
> 
> A few of the things we are experiencing:
> 
1) leaflet marker-icons do not appear.  It looks like it is looking for /profiles/.../marker-icon.png.  When we remove the leading '/' the images load fine.  I've tried greping the entire > directory to find that line but I've come up empty handed.  Where is this located?
> 2) Links to datasets topics are broken.  This is the view on the homepage for the featured topics (Featured Topics Grid).  The link wants to end up here:
> https://{base}/dan/dkan/search/field_topic/flood-modeling-24
> but I think it should be here:
> https://{base}/dan/dkan/?q=search/field_topic/flood-modeling-24
> 
> I see similar issues on the dataset landing pages where the link goes to:
> https://{base}/dataset/flood-scenario-a1234
> when it should be:
> https://{base}/dan/dkan/?q=dataset/flood-scenario-a1234
> 
> Thanks for any help / pointers you can provide.

The Features Topics Grid view at least does have "/" links defined in the fields rewrite section.

**Comment by skorski** [comment]
I'm happy to help resolve this issue but I need some direction from someone with more experience on how DKAN is put together.

**Comment by dafeder** [comment]
@skorski this will be fixed in the next DKAN patch release!

**Comment by skorski** [comment]
Thanks @dafeder.  We really appreciate your help.
