### ISSUE TITLE
DKAN links not using relative paths in searching datasets

### ISSUE THREAD

**Issue by bndri** [NuCivic/dkan#1260]
Hi
I do not understand what is wrong with DKAN sitewide Search module. The Datasets link in the menu show th search page : http://localhost/<my site>/search/type/dataset.
But whatever datasets links that I click, it shows me this error page : /dataset/<dataset title> was not found on this server.
I have found that the link doesn't include the site root name; Itis using **localhost/dataset/<dataset title>** instead of **http://localhost/<my site>/dataset/<dataset title>**
Please can someone tell me what is going wrong ? and tell what to do.
Thanks a lot.

**Comment by dafeder** [comment]
@bndri I believe this is a dupliocate of #1225, which is fixed in PR #1297
