### ISSUE TITLE
RDFa Lite/DCAT markup: prefixes and missing properties

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#130]
I can do the work for this, but assigning to Aaron to get some clarity.

A couple questions about RDFa Lite implementation:

1. A number of properties have the *dc* prefix, (*title*, *format*, etc) when the DCAT specification gives them the *dct* prefix. Is this an issue?
2. A number of the properties listed on the dataset page are not marked up at all. These include *publisher*, *license*, *contact email*, and possibly others. Should we add RDFa Lite markup to these as well?
3. As far as I can tell, there is no *description* property on either dataset listing pages or individual dataset pages.
4. The *distributions* on a dataset page do not have a *format* property, or anything besides an *accessURL*.

**Comment by dafeder** [comment]
We are moving away from RDFa in next release; closing

**Comment by akuckartz** [comment]
What will replace RDFa ?

**Comment by dafeder** [comment]
@akuckartz we are focusing on supporting DCAT RDF endpoints (as opposed to inline RDF markup on pages) through the [Open Data Schema Map](https://github.com/NuCivic/open_data_schema_map) module. ODSM provides an extensible endpoint creation and configuration interface  for mapping open data API schemas (like CKAN, Project Open Data, and now DCAT) to Drupal tokens. See work in progress at https://github.com/NuCivic/open_data_schema_map/pull/57
