### ISSUE TITLE
[CKAN Write API compatibility layer]: Package and Resources creation

### ISSUE THREAD

**Issue by paolomainardi** [NuCivic/dkan#132]
Endpoints:
URL: "api/action/package_create"
URL: "api/action/package_create"

Documentation: http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.package_create
http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.resource_create

Implementation:
Services module
dkan_dataset
dkan_datastore

I'm going to using this special tag in the subject in order to group this type of implementation (CKAN Write compatibility), i can't tag this issue using github labels, so feel free to adapt/modify the subject as you prefer.

**Comment by dafeder** [comment]
Closing this - we have not added a CKAN-compatible write API and don't have that on the roadmap presently; we're focused on the functionality of the Services-based Dataset REST API. See documentation.
