### ISSUE TITLE
DKAN on PHP 5.3

### ISSUE THREAD

**Issue by amuirha** [NuCivic/dkan#1326]
Hi, just downloaded the current distribution and installing on lamp which meets or exceeds the specs.  It creates the database tables etc just fine and half way through the install comes up with:-

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /home/high/public_html/dkan3/profiles/dkan/themes/contrib/nuboot_radix/template.php on line 306

Any suggestions greatly welcomed!

**Comment by dafeder** [comment]
@amuirha what release did you download and how?

**Comment by amuirha** [comment]
Hi Dan

From this page http://docs.getdkan.com/dkan-documentation/dkan-developers-guide/installing-dkan 

I used the link the latest version of the "DKAN DROPS” codebase <https://github.com/NuCivic/dkan-drops-7/archive/master.zip>

Andrew



On 18 Aug 2016, at 17:07, Dan Feder <notifications@github.com> wrote:

@amuirha <https://github.com/amuirha> what release did you download and how?

**Comment by dafeder** [comment]
ok @amuirha I will see if I can reproduce. Did you install on the command line with Drush or in the browser with install.php?

**Comment by amuirha** [comment]
In the browser with install.php

**Comment by amuirha** [comment]
PHP 5.3.29
MySQL 5.5

**Comment by dafeder** [comment]
@amuirha we generally use PHP >= 5.5.x so there is some newer code not tested on 5.3. Although that particular line is just an anonymous function/closure syntax that should be fine on 5.3.x. Do you have any way to test on 5.4 or 5.5?

**Comment by acouch** [comment]
The anonymous array walk shouldn't throw an error in 5.3 http://stackoverflow.com/questions/3197853/php-anonymous-function-with-array-walk

**Comment by amuirha** [comment]
Not easily, no. I'd have to upgrade the whole server and that may have implications on other sites and software running on it. 

The installation notes say 5.3.x

On 18 Aug 2016, at 18:01, Dan Feder <notifications@github.com> wrote:

@amuirha we generally use PHP >= 5.5.x so there is some newer code not tested on 5.3. Although that particular line is just an anonymous function/closure syntax that should be fine on 5.3.x. Do you have any way to test on 5.4 or 5.5?

―

**Comment by acouch** [comment]
What does ``php -v`` say?

**Comment by dafeder** [comment]
@amuirha as a stop gap you could try commenting out those lines in the theme to get it installed; it's fairly minor functionality. We can report this as a bug and try to tweak for better backwards compatibility in a future release.

**Comment by amuirha** [comment]
Thanks Dan

Will try commenting out.  Here is the php -v result:-

Here is the result,
----------
root@hgserver [~]# php -v
PHP 5.3.29 (cli) (built: Oct 6 2014 12:06:09) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014Zend Technologies
with the ionCube PHP Loader v4.6.1, Copyright (c) 2002-2014, by ionCube Ltd., and
with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies

On 18 Aug 2016, at 18:24, Dan Feder <notifications@github.com> wrote:

@amuirha as a stop gap you could try commenting out those lines in the theme to get it installed; it's fairly minor functionality. We can report this as a bug and try to tweak for better backwards compatibility in a future release.

―

**Comment by amuirha** [comment]
Here is the result,
----------
root@hgserver [~]# php -v
PHP 5.3.29 (cli) (built: Oct 6 2014 12:06:09) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014Zend Technologies
with the ionCube PHP Loader v4.6.1, Copyright (c) 2002-2014, by ionCube Ltd., and
with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies

On 18 Aug 2016, at 18:05, Aaron Couch <notifications@github.com> wrote:

What does php -v say?

―

**Comment by amuirha** [comment]
OK, commented that out and it continued on for a while and then got:-

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://www.highgateassociates.com/dkan3/install.php?profile=dkan&locale=en&id=1&op=do StatusText: OK ResponseText: Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/high/public_html/dkan3/profiles/dkan/modules/contrib/markdown/markdown.module on line 117 Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/high/public_html/dkan3/profiles/dkan/modules/contrib/markdown/markdown.module on line 117 Parse error: syntax error, unexpected T_STRING in /home/high/public_html/dkan3/profiles/dkan/modules/contrib/markdown/markdown.module on line 117

**Comment by dafeder** [comment]
@amuirha this is another error I would expect you to get if you're running below PHP 5.3. See the line in question (this is not even our code but a common contrib module that we're including):

http://cgit.drupalcode.org/markdown/tree/markdown.module?h=7.x-1.4#n117

Support for those kinds of namespaces was added in PHP 5.3, so if you're still getting a syntax error for that backslash I have to think maybe your webserver is running a different PHP version than your CLI?

**Comment by amuirha** [comment]
Hi Dan

Please see http://highgateassociates.com/dkan3/phpinfo.php <http://highgateassociates.com/dkan3/phpinfo.php>

Its php 5.3

Best regards

Andrew



On 19 Aug 2016, at 12:18, Dan Feder <notifications@github.com> wrote:

@amuirha <https://github.com/amuirha> this is another error I would expect you to get if you're running below PHP 5.3. See the line in question (this is not even our code but a common contrib module that we're including):

http://cgit.drupalcode.org/markdown/tree/markdown.module?h=7.x-1.4#n117 <http://cgit.drupalcode.org/markdown/tree/markdown.module?h=7.x-1.4#n117>
Support for those kinds of namespaces was added in PHP 5.3, so if you're still getting a syntax error for that backslash I have to think maybe your webserver is running a different PHP version than your CLI?

**Comment by amuirha** [comment]
Dan - what do I need to do to make this work on php 5.3?

**Comment by dafeder** [comment]
@amuirha I've been trying to set up a build environment with 5.3 to see if I can reproduce, but have been having some trouble getting it working. I'll update here when I figure something out. I would suggest considering an upgrade path or a new server, as PHP 5.3 is no longer receiving security updates.

**Comment by amuirha** [comment]
Thanks Dan, OK, Im looking in to upgrading the server to 5.6



On 23 Aug 2016, at 00:10, Dan Feder <notifications@github.com> wrote:

@amuirha <https://github.com/amuirha> I've been trying to set up a build environment with 5.3 to see if I can reproduce, but have been having some trouble getting it working. I'll update here when I figure something out. I would suggest considering an upgrade path or a new server, as PHP 5.3 is no longer receiving security updates.

**Comment by dafeder** [comment]
@amuirha I was able to set up a test environment on CircleCI using PHP 5.3.25. The release branch (what drops builds off of) installed with no syntax errors. See:

https://circleci.com/gh/dafeder/dkan-test/7

What is the result of `drush php-eval "phpinfo();"` ?

**Comment by amuirha** [comment]
Hi Dan

I've installed drush and ran the command, however it didn't result any output,
--------
root@hgserver [~]# drush php-eval "phpinfo();"
root@hgserver [~]#

Andrew 

On 23 Aug 2016, at 13:46, Dan Feder <notifications@github.com> wrote:

@amuirha I was able to set up a test environment on CircleCI using PHP 5.3.25. The release branch (what drops builds off of) installed with no syntax errors. See:

https://circleci.com/gh/dafeder/dkan-test/7

What is the result of drush php-eval "phpinfo();" ?

―

**Comment by dafeder** [comment]
Oh, I thought you were using Drush already. I really can't explain what you're experiencing, again, according to all documentation the syntax that's failing for you should work on 5.3.29 and I can build and install with no errors on 5.3.25. Again, PHP 5.3 reached its end-of-life 2 years ago and should really not be used in production anymore anyway. 

Good luck!
