### ISSUE TITLE
Discovery on API Umbrella

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#133]
https://github.com/NREL/api-umbrella provides some high level capabilities for API management including rate limiting, keys, etc.

If we were to use this with DKAN what would be the level of effort?

Would it be easier to make a PHP version of the web manager or Drupal extensions for that?

How does it route to DKAN/CKAN APIs?

**Comment by dafeder** [comment]
There hasn't been movement on this and most ideas for the future of the datastore involve handling this kind of thing locally within whatever we build. Might revisit in the future but closing for now.
