### ISSUE TITLE
Datastore picks wrong size if an int and bigint are present

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#1347]
Currently the datastore chooses ``int`` if both ``int`` and ``big int`` are present. This is because ``bigint`` is declared after ``int`` in the ``type_counter`` array.

This produces an error after the datastore table has been created because the column uses the ``int`` type that is too small for the data:

```
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'COLUMN_NAME' at row 1
```

A CSV will the following data can reproduce the issue:

```
year,number
2013,1354900000000000
2013,50
```

**Comment by acouch** [comment]
The following fixes the bug: https://github.com/NuCivic/feeds_flatstore_processor/blob/datatype_guess_int_bigint/feeds_flatstore_processor.module

**Comment by acouch** [comment]
The attached PR fixes the issue.

**Comment by dafeder** [comment]
This was merged and will be included in the next release.
