### ISSUE TITLE
ViziCities Choropleth map demo not working

### ISSUE THREAD

**Issue by jayenashar** [NuCivic/dkan#1361]
http://data.nucivic.com/dataset/vizicities/resource/d04178ec-8cdf-43ad-9a13-6aee0a0eb7b2 contains an iframe with a 404 as well as this message:

`File type application/json not supported for preview.`

**Comment by acouch** [comment]
Thanks for noting that. It has been updated http://data.nucivic.com/dataset/vizicities/resource/d04178ec-8cdf-43ad-9a13-6aee0a0eb7b2
