### ISSUE TITLE
Issue with previews of linked zip files

### ISSUE THREAD

**Issue by rumpledelf** [NuCivic/dkan#1385]
Undefined variable: request in theme_recline_default_formatter() (line 98 of /var/www/html/profiles/dkan/modules/contrib/recline/recline.theme.inc).

Looks like a logic error - request is only generated if type is not set (line 56), but then request is referenced in a switch further down (line 98) by type, and only for zip files.

**Comment by rumpledelf** [comment]
Additionally content-length is not set by drupal_http_request for HEAD so even if you do set the request you still get an error here.

**Comment by dafeder** [comment]
@rumpledelf can you give me the version of DKAN you're using, a URL to the ZIP file you're seeing this with and let me know which field (API/Remote File/Upload) on the resource form you're adding the file to?

**Comment by rumpledelf** [comment]
Its an outright logic error in the code for remote zip files, glaringly obvious. Its referencing a variable that is only set in one branch of an if in the other branch, but only for zip files - and then references an index into that that is never returned by the api in the first place. We've had to patch it and some other equally obvious logic errors that I'm amazed haven't been hit yet by other people. Do you want me to add the patch to the ticket?

**Comment by dafeder** [comment]
@rumpledelf can you tell me what version of the recline module you're using? It may be that it's one few people are using in production yet. These features have changed a lot recently and we're preparing a new stable release.

**Comment by dafeder** [comment]
And yes of course always appreciate patches or pull requests

**Comment by janette** [comment]
Fixed https://github.com/NuCivic/recline/pull/56

![dkan___the_site_slogan_thing_here](https://user-images.githubusercontent.com/314172/28217271-328a24a8-687a-11e7-9c00-5d36f7689461.png)
