### ISSUE TITLE
DKAN Dataset should require DKAN Dataset Content Types

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#140]
Currently "drush en dkan_dataset" misses the dataset and resource content types because dkan_dataset_content_types is not listed in dkan_dataset.info

**Comment by dafeder** [comment]
Closing. The main issue here has been completed for some time: https://github.com/NuCivic/dkan/blob/7.x-1.13.4/modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.info#L9
