### ISSUE TITLE
dkan_dataset: duplicate function names in 2033147-508-compliance branch

### ISSUE THREAD

**Issue by upieper** [NuCivic/dkan#141]
When both dkan_dataset_api and dkan_open_data modules are enabled, the json link from a dataset page creates a white screen in the 2033147-508-compliance branch, because there are duplicate function names between these two files:

dkan_dataset/modules/dkan_dataset_api/dkan_dataset_api.inc
dkan_dataset/modules/dkan_open_data/dkan_open_data.module

(resulting in the error message: 

```
PHP Fatal error:  Cannot redeclare dkan_open_data_build_rows() (previously declared in docroot/profiles/dkan/modules/dkan/dkan_dataset/modules/dkan_open_data/dkan_open_data.module:65) in docroot/profiles/dkan/modules/dkan/dkan_dataset/modules/dkan_dataset_api/dkan_dataset_api.inc on line 83
```

Changing the overlapping function calls in dkan_dataset_api.inc to start with the module name fixes the problem.

**Comment by janette** [comment]
dkan_open_data no longer exists - closing
