### ISSUE TITLE
PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in phar:///usr/bin/drush/vendor/webmozart/path-util/src/Path.php:257 

### ISSUE THREAD

**Issue by MradulaPai** [NuCivic/dkan#1429]
I am trying automate the Dkan installation on Elastic Beanstack. 
After every required installation,
If i run drush si dkan --verbose --account-pass='admin' --site-name='EIC' install_configure_form.update_status_module="'array(FALSE,FALSE)'" --yes 
is working throwing below error. 
PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in phar:///usr/bin/drush/vendor/webmozart/path-util/src/Path.php:257

But manually above command working fine. Need some help here.

**Comment by acouch** [comment]
Looks like your ``env`` folder isn't setup right for the path-utils library: https://github.com/webmozart/path-util/blob/master/src/Path.php#L245

Can you share the recipe you are using?
