### ISSUE TITLE
Recline grid view search data not working 

### ISSUE THREAD

**Issue by viewpnt** [NuCivic/dkan#144]
When trying to "search data..." in the recline grid view, the "Loading" message never disappears.

I traced the issue to the function dkan_datastore_api_add_index_query() in file 
```
profiles/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
```
Replacing the line:
```
    //Not working
    $ft_result = db_query("SHOW INDEX IN \{$table\} WHERE Index_type = 'FULLTEXT'");

``` 
With this line solves the problem,
```
    //Working
    $ft_result = db_query("SHOW INDEX IN {" . $table . "} WHERE Index_type = 'FULLTEXT'");

```

![dkan-recline-view-search-data](https://cloud.githubusercontent.com/assets/5809755/3194699/a5efae6e-ed02-11e3-8119-e78c87a7be2c.png)

**Comment by acouch** [comment]
This has been done.
