### ISSUE TITLE
Cannot associate resource to dataset

### ISSUE THREAD

**Issue by rzw** [NuCivic/dkan#1449]
I can only create a resource if I attach to dataset - None -

Also on the edit resource page there is a notice which I guess points [knowledgable people] to the problem. 
Notice:
Undefined index: og_group_ref in dkan_dataset_form_alter()
(line 308 of .../profiles/dkan/modules/dkan/dkan_dataset/dkan_dataset.forms.inc).

I am using the fully made version at http://github.com/nucivic/dkan-drops-7

Can I try to edit a table directly for testing? Which table?

**Comment by dafeder** [comment]
@rzw the prefered way to create a resource is to start from a dataset and use the "add resource" link - did you try that?

**Comment by dafeder** [comment]
Also, it sounds like that has to do with the dataset not having a group. Can you see if it works if the dataset is assigned to a group?

**Comment by dafeder** [comment]
More than a month with no response - closing
