### ISSUE TITLE
dkan in subdirectory redirects to base after saving a resource

### ISSUE THREAD

**Issue by sturkarslan** [NuCivic/dkan#146]
I am not sure if this is the proper place to submit this issue. I have a drupal installation running at http://mydomain.com. My dkan is installed in http://mydomain.com/dkan. Everything works fine but when i add a resource at http://mydomain.com/dkan/node/add/resource and click save it goes back to http://mydomain.com/node/add/resource.
 I played around with .htaccess Rewrite rules with no luck. my RewriteBase /dkan and my baseurl in settings.php is http://mydomain.com/dkan

Here is my Rewrite rule
RewriteCond %{REQUEST_URI} ^/dkan/(._)$
RewriteRule ^(._)$ /dkan/index.php?q=$1 [L,QSA]

Any idea why this might be happening?

**Comment by janette** [comment]
@sturkarslan I apologize for such a late reply, if you upgrade your build to the latest release you should have better luck. http://dkan.readthedocs.io/en/latest/introduction/maintaining.html#basic-upgrades
