### ISSUE TITLE
Add support for a theme or category constrained taxonomy

### ISSUE THREAD

**Issue by pmackay** [NuCivic/dkan#148]
As opposed to the current user-defined tags taxonomy. This would map well to DCAT themes (http://www.w3.org/TR/vocab-dcat/#Property:dataset_theme). It is also modelled in data.gov.uk (http://data.gov.uk/data/search).

**Comment by janette** [comment]
fixed https://github.com/NuCivic/open_data_schema_map/blob/7.x-1.x/modules/open_data_schema_dcat/data/dataset-1.1.json#L41
