### ISSUE TITLE
Document current limitations of datastore search

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#149]
The datastore search as exposed through the recline interface is limited by the mysiam fulltext implementation. We want to use mysaim since the innodb version is not available until 5.6 which is less supported. It only searches on text tables and on up to 16 of them. This limitation should be exposed to the user and in docs. InnoDB and Sphynx both have fullltext search for later or updated versions of MySQL. These should be explored in a separate ticket.

**Comment by dafeder** [comment]
Closing in favor of #2042
