### ISSUE TITLE
Admin role defaults to "Editor" on fresh install.

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#151]
Forgive me if this has already been fixed, but I noticed that the "admin role" was set to "Editor", not administrator in a fresh install.  

I was using nuams/dkan-drops-7 to install.

**Comment by jonpugh** [comment]
A quick test on a new install of dkan (using dkan-drops-7, master branch) shows "Editor" is still set as the default admin role.

This would be a great thing to add to the behat tests...

**Comment by jonpugh** [comment]
Calling "drush fr --force" still seems to leave "editor" as the admin role.  :cry:

**Comment by dafeder** [comment]
## User Story

As a site builder, when I install a new DKAN instance, the "administrator role" should be set to "administrator"

## Context

This seems to set to "editor" by default.

**Comment by jacintocapote** [comment]
Fixed https://github.com/NuCivic/dkan/pull/576
