### ISSUE TITLE
Sitewide blocks on left doesn't show 'other' license 

### ISSUE THREAD

**Issue by rumpledelf** [NuCivic/dkan#1520]
The striped table block at the bottom of a dataset shows the 'other' license correctly
The panels block at the left of a dataset falls through to 'License not specified' when you set the 'other' license.

Additionally it is not easy to add new licenses as they are a text list not a taxonomy and I haven't dug around enough to find where the URLs for licenses are pulled from. Our client generally isn't using any of the licenses provided and is using the 'other' option a lot.

I patched our copy with this (doesn't check for language)

@@ -184,6 +184,9 @@ function dkan_sitewide_license_block() {
		         return $output;
		       }
		     }
		+    if (isset($node->field_license[LANGUAGE_NONE][0])) {
		+      return $node->field_license[LANGUAGE_NONE][0]['safe_value'];
		+    }
		     return t('License not specified');
		   }
		 }

**Comment by janette** [comment]
You can use hook_license_subscribe() to create a custom list of license values
https://github.com/NuCivic/dkan/blob/7.x-1.x/modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc

**Comment by janette** [comment]
Here is some documentation: http://dkan.readthedocs.io/en/latest/development/license.html
