### ISSUE TITLE
Notice: Undefined index: base theme in drupal_find_base_themes()

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1522]
I'm installing dkan-drops-7 from scratch in a PHP 7 server and I have seen this notices during the installation:

Notice: Undefined index: base theme in drupal_find_base_themes() (line 844 of /var/local/html/dadesobertes/includes/theme.inc).
Notice: Undefined index: base theme in drupal_find_base_themes() (line 844 of /var/local/html/dadesobertes/includes/theme.inc).

However, the installation was successful.

**Comment by janette** [comment]
Thanks oriole9g, a fix for this error will be in the next release. 
https://github.com/NuCivic/recline/pull/77/files
