### ISSUE TITLE
Document conventions for contributed modules

### ISSUE THREAD

**Issue by pmackay** [NuCivic/dkan#153]
It would be really helpful to know what conventions to follow for any modules that are intended to be work on top of DKAN but not actually be added to it (which is probably "most things" at this point if DKAN is preferred to be small). 

Should contrib modules reuse fields in DKAN where possible? If so, there wont be any namespacing. Should content types have any prefixes? Etc. 

Any quick thoughts on this here or on a wiki page would be super helpful.

**Comment by janette** [comment]
Documentation started, more to follow http://dkan.readthedocs.io/en/latest/development/index.html

**Comment by kimwdavidson** [comment]
We're documenting this work in #2167. You can follow progress and add comments in that ticket. We'll close this ticket. Thanks!
