### ISSUE TITLE
Old Ctools and PHP 7 Warning

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1543]
CKan is using ctools 7.x-1.9 but with PHP 7 appears a warning.

Deprecated function: Methods with the same name as their class will not be constructors in a future version of PHP; ctools_context has a deprecated constructor a require_once() (línia 127 de /var/local/html/dadesobertes/profiles/dkan/modules/contrib/ctools/ctools.module).

This issue is fixed: https://www.drupal.org/node/2528736

Maybe we can update the oficial version to the last stable ctools 7.x-1.11 to go away the warning.

**Comment by rhabbachi** [comment]
> CKan is using ctools 7.x-1.9 but with PHP 7 appears a warning.

You sure it's CKan? 

@oriole9g Are you able to reproduce the same issue Using this PR?

**Comment by rhabbachi** [comment]
Missed the PR link in the previous comment. Sorry!
Here's the link https://github.com/NuCivic/dkan/pull/1465

**Comment by dafeder** [comment]
Ctools is up to 1.10 on the 7.x-1.x branch but the 1.12 releases are still on 1.9. I've created a PR to upgrade to 1.11 in dkan dataset 1.12.x. NuCivic/dkan_dataset#290

**Comment by oriole9g** [comment]
@rhabbachi Obviously it's DKAN :)

**Comment by rhabbachi** [comment]
@oriole9g The fix was merged and should be available in the next 1.12.x release (coming soon).
