### ISSUE TITLE
Group page dataset button shows page not found.

### ISSUE THREAD

**Issue by arealperson** [NuCivic/dkan#1560]
Problem Statement:
I have a page of DKAN Groups that contain datasets, Under each Group there is a small blue button
that should take me to that groups dataset list. Everything else works.
But when I click it, I get the following error.

Page not found

The requested page "/?q=%3Fq%3Dgroup/data" could not be found.

Question:
Is there a setting I can check ?
What module controls this feature ? Why is this not working ? What documents should I review ?
What else can I check ? If you don't specifically what I should check, please help me anyway, is this PHP ?

Notes:
I've posted to all the DKAN forums (1 very small google) and I also cannot get any response from
the NuCivic Chat room after 2 weeks. Drupal forum sent me here.

**Comment by janette** [comment]
Thanks for posting, looks like this is a bug, if you edit line 36 of `themes/nuboot_radix/templates/node/node--group.tpl.php` from
```<a href="<?php print url($node_url) ?>" class="btn btn-primary"><?php print count($datasets) ?> datasets</a>```
to 
```<a href="<?php print urldecode($node_url) ?>" class="btn btn-primary"><?php print count($datasets) ?> datasets</a>```
