### ISSUE TITLE
If I change the public folder location the font icon select doesn't reflect the change

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1583]
If I change the  public folder and clean all caches the font icon select are still using the old public folder.

I have seen the file_managed table and all seems correct because the font files uri is public://dkan-topics.eot, but when I change the public folder, clean all caches and visit admin/config/content/font_icon_select_options/1/edit is still using the old public folder instead of the new public folder.

Plus, I have openend a issue to the sandbox folder: https://www.drupal.org/node/2831992

**Comment by dafeder** [comment]
@oriole9g did you fix this? I would suggest just re-uploading the font, something is stuck somewhere but doing that would be easier than debugging.
