### ISSUE TITLE
ahoy build config mktemp bug

### ISSUE THREAD

**Issue by asghaier** [NuCivic/dkan#1615]
Running `ahoy build config` on Linux machines (tested on both ArchLinux and Ubuntu) always breaks with the following error: `mktemp: too few X's in template 'bash'`

As a developer I want the `ahoy build config` command to work properly on both OSX and Linux.

**Comment by asghaier** [comment]
replacing Line 141 here: https://github.com/NuCivic/dkan/blob/7.x-1.x/.ahoy/site/build.ahoy.yml#L141

with the following:
`       tempdir=$(mktemp -d "/tmp/$0.XXXXXXXX")`

should fix the issue and work properly with both OSX and Linux without causing any conflicts.

**Comment by asghaier** [comment]
Fix in PR #1616 

`mktemp -d "/tmp/$0.XXXXXXXX"` tested on OSX, ArchLinux and Ubuntu and behaves exactly the same.

`ahoy build config` tested on ArchLinux and works fine. Please test the ahoy command on OSX to confirm this change doesn't break it.

**Comment by dkinzer** [comment]
@asghaier please redo PR from dkan_starter.

**Comment by dafeder** [comment]
Fixed in NuCivic/dkan_starter#39
