### ISSUE TITLE
Can't install DKAN

### ISSUE THREAD

**Issue by D0natel0** [NuCivic/dkan#1659]
Hello,

First of all, i'm french and my english is not quite so good, so forgive me if i'm little misunderstood.

I try to install since yesterday DKAN distribution on wamp + windows 10 environment.
My steps to do that : 

- creating dkan database in phpmyadmin (default engine is myISAM, but when tables are create they are all in innoDB.....kind of weird, but i don't like the idea of change each table's engine....).

- putting  dkan directory in my www.
- access to this file with chrome + localhost and launch the install.
- at the first time i had messages with timeout issues (it take very much time....) so i modified my php.ini to increase this parameter it seems to solve this issue.
- the next step of "configuring" dkan crash every time i try.... and i don t understand why neither the message ....(forgot to take a screenshot, but i have an install in progress now, i will show you as soon as possible).

I don t know how to solve, what to looking for, i don t understand why....

My wamp install, during my different tests i had to install a second version of php, so i have php 5.6.19 and 7.0.4 and even switching between those to versions, it doesn't do nothing better.

Need your help or/and advice :)
Thanks

**Comment by dafeder** [comment]
Hi @D0natel0 - please show us the exact error. Make sure you have at least 512mb ram allocated to PHP. To be honest we don't have any experience with WAMP and can't provide much support for it. When I've done Drupal development on Windows (it's been a while!) I've created a virtual linux machine with VirtualBox or VMWare so that I can have a more standard environment to work on.

**Comment by D0natel0** [comment]
Hello, i gave up the idea to try DKAN with wamp...

I try now to learn using Debian and at least try Dkan finally...

**Comment by dafeder** [comment]
Great, let us know how it goes! Also please check out our developer email list at https://groups.google.com/forum/#!forum/dkan-dev
