### ISSUE TITLE
Can't Create a Data Dashboard

### ISSUE THREAD

**Issue by CMAP-SLG** [NuCivic/dkan#1675]
I'm trying to create a Data Dashboard.
As admin from the menu I...

1) Select DKAN
2) Data Dashboards

I get a page and...
I click "Create Dashboard"

But...
I get 404 - Website cannot be found. 
Is this a bug ? 

The url the 404 is on is this...
http://mysite/node/add/data-dashboard

Thanks,

**Comment by janette** [comment]
@CMAP-SLG we will need more information about how you created your site, which version, build process, ...
