### ISSUE TITLE
feeds_get_importer_ids

### ISSUE THREAD

**Issue by gar37bic** [NuCivic/dkan#169]
I am just trying an install of DKAN on bluehost, which is running PHP 5.4.  Initial install went OK.  After running the update of all modules, I created a new dataset, and then clicked on the link-header /Datasets/[my dataset name], which went to this page:
  http://my-web.site/dataset/space-manufacturing-companies-public-data

That page had nothing but the following:
  Fatal error: Call to undefined function feeds_get_importer_ids() in /my/public/directory/dkan-drops-7-7.x-1.0/profiles/dkan/modules/dkan/dkan_datastore/dkan_datastore.module on line 115

I'm guessing that this is due to some version conflict between the feeds module and the datastore module?  My online Google search for feeds_get_importer_ids turned up a drush diff that added the missing function, but I was unable to determine if that was a new diff or an old one, or whether I could just hack that function into the feeds module - that seemed like a bad idea.

**Comment by suhasgr** [comment]
Hey I am facing the same issue. Can you Help me in figuring out the solution?

**Comment by drkloc** [comment]
@gar37bic

The error you are getting probably has to do with the fact that you update the **feeds** module, that function does not exists in the new version and dkan_datastore still uses it.

We keep track of the versions of modules that we need in order for dkan to provide that:

+ it can be rebuild properly
+ it can be installed properly
+ & it runs properly

We only update modules based on:

+ security updates
+ functionality needed

Each version of dkan freezes the versions that guarantees the conditions above. For instance:

v1.0 -> https://github.com/NuCivic/dkan/blob/7.x-1.0/drupal-org.make
v1.1 -> https://github.com/NuCivic/dkan/blob/7.x-1.1/drupal-org.make
v1.2 -> https://github.com/NuCivic/dkan/blob/7.x-1.2/drupal-org.make
v1.3 -> https://github.com/NuCivic/dkan/blob/7.x-1.3/drupal-org.make
v1.4 -> https://github.com/NuCivic/dkan/blob/7.x-1.4/drupal-org.make
v1.5 -> https://github.com/NuCivic/dkan/blob/7.x-1.5/drupal-org.make
v1.6 -> https://github.com/NuCivic/dkan/blob/7.x-1.6/drupal-org.make
dev version or 7.x-1.x -> https://github.com/NuCivic/dkan/blob/7.x-1.x/drupal-org.make

As you can see, the update strategy is to avoid updating modules and update the whole distro instead (which eventually gets some modules updated and in some cases patch to dkan needs). We recommend running the latest version or even better 7.x-1.x, which in our opinion is the most stable code there is.

There's documentation on how to update dkan in the docs site, precisely here -> http://docs.getdkan.com/dkan-documentation/dkan-developers/updating-dkan

I see that you are running 1.0 off the dkan-drops-7 repo which is a pretty old build, i recomend that you update to 1.6 or 7.x-1.x.

I hope this information is helpful to you.

**Comment by suhasgr** [comment]
I Understood the problem you are expressing.

But I really didn't understand the solution. Can elaborate in steps what
should I do?

Regards
Suhas

On 2 February 2015 at 22:12, Teofilo Sibileau <notifications@github.com>
wrote:

> @gar37bic <https://github.com/gar37bic>
>
> The error you are getting probably has to do with the fact that you update
> the *feeds* module, that function does not exists in the new version and
> dkan_datastore still uses it.
>
> We keep track of the versions of modules that we need in order for dkan to
> provide that:
>
>    - it can be rebuild properly
>    - it can be installed properly
>    - & it runs properly
>
> We only update modules based on:
>
>    - security updates
>    - functionality needed
>
> Each version of dkan freezes the versions that guarantees the conditions
> above. For instance:
>
> v1.0 -> https://github.com/NuCivic/dkan/blob/7.x-1.0/drupal-org.make
> v1.1 -> https://github.com/NuCivic/dkan/blob/7.x-1.1/drupal-org.make
> v1.2 -> https://github.com/NuCivic/dkan/blob/7.x-1.2/drupal-org.make
> v1.3 -> https://github.com/NuCivic/dkan/blob/7.x-1.3/drupal-org.make
> v1.4 -> https://github.com/NuCivic/dkan/blob/7.x-1.4/drupal-org.make
> v1.5 -> https://github.com/NuCivic/dkan/blob/7.x-1.5/drupal-org.make
> v1.6 -> https://github.com/NuCivic/dkan/blob/7.x-1.6/drupal-org.make
> dev version or 7.x-1.x ->
> https://github.com/NuCivic/dkan/blob/7.x-1.x/drupal-org.make
>
> As you can see, the update strategy is to avoid updating modules and
> update the whole distro instead (which eventually gets some modules updated
> and in some cases patch to dkan needs). We recommend running the latest
> version or even better 7.x-1.x, which in our opinion is the most stable
> code there is.
>
> There's documentation on how to update dkan in the docs site, precisely
> here ->
> http://docs.getdkan.com/dkan-documentation/dkan-developers/updating-dkan
>
> I see that you are running 1.0 off the dkan-drops-7 repo which is a pretty
> old build, i recomend that you update to 1.6 or 7.x-1.x.
>
> I hope this information is helpful to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NuCivic/dkan/issues/169#issuecomment-72585092>.
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by drkloc** [comment]
@suhasgr Rebuilding dkan will solve your issue. Please read http://docs.getdkan.com/dkan-documentation/dkan-developers/updating-dkan#DKAN_Tag_Updates

**Comment by suhasgr** [comment]
The server is in remote site and I don't have server's system access to
work on Drush to rebuild. Is there a way to rebuild through Drupal
application itself?

On 2 February 2015 at 22:22, Teofilo Sibileau <notifications@github.com>
wrote:

> @suhasgr <https://github.com/suhasgr> Rebuilding dkan will solve your
> issue. Please read
> http://docs.getdkan.com/dkan-documentation/dkan-developers/updating-dkan#DKAN_Tag_Updates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NuCivic/dkan/issues/169#issuecomment-72586000>.
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by drkloc** [comment]
Do you control the codebase at least? If you do, you could rebuild locally or in a server that you have access and upload the changes.

**Comment by suhasgr** [comment]
Please elaborate.

On 2 February 2015 at 22:50, Teofilo Sibileau <notifications@github.com>
wrote:

> Do you control the codebase at least? If you do, you could rebuild locally
> or in a server that you have access and upload the changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NuCivic/dkan/issues/169#issuecomment-72588138>.
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by drkloc** [comment]
@suhasgr you are not going to be able to solve this from the browser.

What i mean is:

+ Is this a website you are mantaining?
+ Do you have the means to push code updates to that site even though you can't ssh into that server?
+ If you do you should be able to grab the code that is running now, run the rebuild in your computer and push the changes.
+ Then run database

**Comment by dafeder** [comment]
@suhasgr where do you have the feeds module installed?

**Comment by jonpugh** [comment]
This is still an issue.  

If you update to the latest Feeds module (currently beta1) it will break data stories, maybe some other things.

There is a security fix for feeds in alpha9 and beta1...

**Comment by jonpugh** [comment]
Ok, maybe not a problem in main DKAN, but data_starter still has feeds alpha: https://github.com/NuCivic/data_starter/blob/master/docroot/profiles/dkan/modules/contrib/feeds/feeds.info

**Comment by aborruso** [comment]
@jonpugh a stupid question: do you know if the last DKAN version works with 7.x-2.0-beta1?

**Comment by odvietnam** [comment]
I get this annoying error and cannot find any sollution :( 

Whenever I want to edit a page or a dataset/resource, the site turns the error "The website encountered an unexpected error. Please try again later."

The error log says "Error: Call to undefined function feeds_get_importer_ids() in dkan_datastore_feeds_access() (line 162 of ..../profiles/dkan/modules/dkan/dkan_datastore/dkan_datastore.module)." 

Can anyone suggests a fix for this? Thank you!

**Comment by janette** [comment]
To avoid errors do not upgrade the feeds module, the current version of DKAN is using a patched revision:
```
  feeds:
    download:
      type: git
      url: http://git.drupal.org/project/feeds.git
      branch: 7.x-2.x
      revision: d312f4f66e98cc12b8462cd13874184589017f72
    patch:
      1127696: https://www.drupal.org/files/issues/1127696-137.patch
```
Information on the patch can be found here: https://www.drupal.org/node/1127696

If you have not otherwise customized the distribution, you could restore the files by running
```
ahoy dkan remake
```
