### ISSUE TITLE
Minor form action problem - /node/add/resource

### ISSUE THREAD

**Issue by gar37bic** [NuCivic/dkan#170]
Folks,
I am running DKAN in a subdirectory, and found that the add resource form was giving a 404 when hitting either 'Save' or 'Next: Additional Info'.  Using Inspect Element I found that the form's Action did not include the subdirectory.  So I edited the Action and it worked.

**Comment by acouch** [comment]
Closing after lack of input. Please reopen if you are having the same issue.

**Comment by robinmarvel** [comment]
http://www.delhilocal.in/packers-movers-saket.html
http://www.delhilocal.in/packers-movers-mahipalpur.html
