### ISSUE TITLE
Bad documentation in dkan_dataset_content_types.api.php

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1721]
In this file you can read:

> /**
>  ** Removes a set of license options for the dkan dataset license field.
>  **
>  */
>  function hook_license_subscribe() {

The hook example should be **unsubscribe** not **subscribe** 

Plus, the documentation generated here: https://media.readthedocs.org/pdf/dkan/latest/dkan.pdf it's not correct. In page 22 says:

> // Let's asume we want to do this as part of the fictitious license_options_extra module
> function license_options_extra_unsubscribe() {
>   return array(
>     'notspecified',
>   )
>}

This doesn't work, if you create a module named **license_options_extra** the hook should be **license_options_extra_license_unsubscribe**

**Comment by dafeder** [comment]
Thanks @oriole9g - PRs appreciated if you are inspired, otherwise we'll fix for a future release.

**Comment by oriole9g** [comment]
#1774

**Comment by janette** [comment]
#1841 re-roll of #1774

**Comment by janette** [comment]
fixed
