### ISSUE TITLE
Download whole dataset (multiple resources) as a .zip file

### ISSUE THREAD

**Issue by federicca** [NuCivic/dkan#173]
Add a "download dataset .zip" button on the dataset page so users can download full datasets with multiple resources easily.

This will be especially useful for datasets with annual data or similar that have long lists of resources and might need to be used together

![image](https://cloud.githubusercontent.com/assets/1379537/3412039/bdc6dc52-fdfa-11e3-858f-8049b5701d01.png)

**Comment by drkloc** [comment]
there are updated requirements for this in NuCivic/dkan_dataset#173
