### ISSUE TITLE
Indefined index error messages on fresh in stall

### ISSUE THREAD

**Issue by OnnoRoosenschoon** [NuCivic/dkan#1768]
Hi all,

I did a fresh install of DKAN 1.13.1.

I got the following error message immediately after the install:

Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 201 of /DATA/apache/html/dkan.wenr.wur.nl/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /DATA/apache/html/dkan.wenr.wur.nl/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /DATA/apache/html/dkan.wenr.wur.nl/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 241 of /DATA/apache/html/dkan.wenr.wur.nl/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).

When I execute the "Run updates" command form the UI, this error message disappears.
After running cron or checking updates, the errors message is there again.

What is the cause of this message? What does it mean and does it influence correct functioning of DKAN?

On 1st glance, everything seems to work fine. But what if I dig deeper?

**Comment by janette** [comment]
Hi OnnoRoosenschoon, 
We use the dkan_sitewide_update_status_alter() function to display a message on the available updates page when we are using a patched version of a module. In 1.13 we have removed several RDF modules but have not yet updated the function so you will see the errors you mentioned. If you want to fix this before the 1.13.2 patch comes out you can remove the following lines:
<img width="818" alt="remove_rdf_config_from_dkan_features_civic-5856_by_janette_ _pull_request__1755_ _nucivic_dkan" src="https://cloud.githubusercontent.com/assets/314172/23613280/6ecf87a6-0244-11e7-853d-5406b5131e28.png">

The functionality of DKAN is not effected.

**Comment by janette** [comment]
@OnnoRoosenschoon This will be fixed in the 1.13.3 release
