### ISSUE TITLE
undefined variables in panels.inc

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#1770]
Folks are reporting notices about undefined variables from the theme:

```bash
Notice: Undefined variable: front_nid in nuboot_radix_preprocess() (line 48 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 44 of C:\xampp\htdocs\dkan\profiles\dkan\themes\nuboot_radix\includes\panel.inc).
```

See: https://github.com/NuCivic/dkan/issues/1732#issuecomment-282073204

**Comment by janette** [comment]
Thanks Aaron, we got it :)
https://github.com/NuCivic/dkan/pull/1730

**Comment by dafeder** [comment]
Hmm - I'm not sure that #1730 addresses the second error message, `Notice: Undefined offset: 1 in nuboot_radix_preprocess()`. Going to reopen for now.

**Comment by dafeder** [comment]
Haven't been seeing this, closing
