### ISSUE TITLE
Is it possible to not use Windows reserved characters in dkan_default_content and dkan_migrate_base_example filenames?

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1790]
Windows have this reserved characters in filenames:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247
```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

With the new dkan_fixtures module we are using filenames with question mark (?) character
https://github.com/NuCivic/dkan/tree/7.x-1.x/modules/dkan/dkan_fixtures/modules/dkan_default_content/data

Is it possible to replace this Windows reserved character for something else?

This was causing errors like this when trying to clone the repo:
`error: unable to create file modules/dkan/dkan_fixtures/modules/dkan_default_content/data/data_dashboard_show?id=59c96dfb-d64e-4025-b766-d9f1c7faaa47.json: Invalid argument`

**Comment by janette** [comment]
oriole9g could you try building from the `default-content-windows-chars` branch and see if that works?

**Comment by oriole9g** [comment]
@janette Yes, this errors have reduced but there are more files with a mark in dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/

`$ git clone -b default-content-windows-chars https://github.com/NuCivic/dkan.git
Cloning into 'dkan'...
remote: Counting objects: 20881, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 20881 (delta 31), reused 7 (delta 7), pack-reused 20805
Receiving objects: 100% (20881/20881), 56.88 MiB | 548.00 KiB/s, done.
Resolving deltas: 100% (13092/13092), done.

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/package_show?id=afghanistan-election-districts-test: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/package_show?id=gold-prices-london-1950-2008-monthly-test: In valid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/package_show?id=us-national-foreclosure-statistics-january-2012-test: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/package_show?id=wisconsin-polling-places-test: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/resource_show?id=06f553fe-e063-44ea-afac-be0de6a9e0ca: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/resource_show?id=5df6eb37-fa44-4d29-bd67-8158aa57547e: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/resource_show?id=5fea3bdb-3138-4867-a7e8-fa1bcc182a7f: Invalid argument

error: unable to create file modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/data/resource_show?id=b9b0d609-b332-476b-8884-94fbc56f689a: Invalid argument

fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
`

**Comment by janette** [comment]
thanks @oriole9g could you try it again with the `default-content-windows-chars` branch?

**Comment by oriole9g** [comment]
All fine now!

```
$ git clone -b default-content-windows-chars https://github.com/NuCivic/dkan.git
Cloning into 'dkan'...
remote: Counting objects: 21367, done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 21367 (delta 122), reused 2 (delta 2), pack-reused 21134
Receiving objects: 100% (21367/21367), 57.07 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (13422/13422), done.
```
