### ISSUE TITLE
Dkan dataset groups have a hidden dependency with path Breadcrumbs module

### ISSUE THREAD

**Issue by oriole9g** [NuCivic/dkan#1791]
If you dissable Path Breadcrumbs module, when you edit/save a dataset gets FATAL error:

`Error: Call to undefined function path_breadcrumbs_object_cache_clear() a dkan_dataset_groups_node_update() (línia 214 de /var/local/html/dadesobertes/sites/all/modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.module).`

We need to add the dependency in info file or protect the call with a module_exists()

**Comment by janette** [comment]
There is a dependency on path_breadcrumbs in dkan_sitewide_panels,
https://github.com/NuCivic/dkan/blob/7.x-1.12.13/modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info#L11

but adding module_exists() to the function wouldn't hurt, thanks for flagging it

**Comment by oriole9g** [comment]
I'm using some dkan modules instead of using the full project profile, so in this scenario it is possible to enable dkan_dataset_groups without enable dkan_sitewide_panels.

**Comment by oriole9g** [comment]
I think it is better to simply add the dependency to force enable path_breadcrumbs if dkan_dataset_groups is enabled, but module_exists() it is also a good solution.

**Comment by dafeder** [comment]
@oriole9g your PR works, going to merge - best practice to make dependencies explicit. FYI though we don't really support any modules from inside the DKAN repo as standalone modules.
