### ISSUE TITLE
Create Harvesting Examples from CKAN and Socrata

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#18]
Create a migration to do this.

**Comment by Forester1** [comment]
Thanks.  Having a look.

**Comment by dafeder** [comment]
Closing as we have a new Harvester framework focused on Project Open Data, which Socrata and CKAN both generally support. Open new tickets if there is interest in a new Harvester plugin that would support CKAN endpoints specifically - we haven't seen much demand for this recently.
