### ISSUE TITLE
package_show result should be a dictionary, not an array

### ISSUE THREAD

**Issue by adufilie** [NuCivic/dkan#182]
DKAN returns an Array result ("result": [{...)
    http://demo.getdkan.com/api/3/action/package_show?id=766fb66c-56b7-49fb-bf4d-062dbb6d017e

CKAN returns an Object result ("result": {...):
    http://demo.ckan.org/api/3/action/package_show?id=adur_district_spending

The API documentation says the return type should be a dictionary:
    http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.package_show

**Comment by drkloc** [comment]
this is have been merge to NuCivic/open_data_schema_map master. Closing
