### ISSUE TITLE
DKan Datastore Import

### ISSUE THREAD

**Issue by gouli** [NuCivic/dkan#1849]
Datastore Import fails to import the csv file wherein the column name ends with ",".

Steps to Reproduce:
1) Create a Resource using the csv.
2) The delimited in the csv file is ","
3) First row ends with ","
4) Upload the file.
5) Go to Manage Datastore.
6) Import the attached resources.

We get the below error message 
SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name ''

**Comment by dafeder** [comment]
@gouli if your delimiter is se to "," I think getting this error on a file with lines that end in "," would be expected. If you post the file with the issue it would be easier to troubleshoot.

-dan

**Comment by dafeder** [comment]
@gouli - this is an invalid CSV file, so the fact that you're getting an error is correct behavior from DKAN.
