### ISSUE TITLE
How to desable demo content?

### ISSUE THREAD

**Issue by mayarahmo** [NuCivic/dkan#185]
Well, I've not found that demo homepage section where is written: "Try out standard DKAN functionality in a sandbox environment. Search for datasets directly from the homepage or by navigating to the Datasets search page where you can facet by tags, groups and format." and "You can add a Dataset to get a sense of publisher workflow. This form can be customised to require many additional fields. In this demo only the most basic fields are required.".

I want to desable this section but maintain the group block "Front Page Group Grid" in homepage. 

I tried to disable the "DKAN Sitewide Demo Front" but this disabled the groups block too. But there is no a separated view for this section. Any thoughts? Do I have to try remove that  section by code?

**Comment by acouch** [comment]
Disabling the "DKAN Default Content" module will delete the default content.
