### ISSUE TITLE
Unable to get grid, graph view when uploading xlsx. but when saving same file in csv format with utf-8 encoding. It works.

### ISSUE THREAD

**Issue by kundanrock** [NuCivic/dkan#1851]
HI,

i have uploaded xls file but grid and graph is not visualise.

**Comment by dafeder** [comment]
@kundanrock not clear to me how this is different from #1830

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:54518 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1cy1do-000LR6-UQ
	for greg@biomassiv.es; Tue, 11 Apr 2017 14:39:53 -0500
Date: Tue, 11 Apr 2017 12:39:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1491939553;
	bh=FXGN7H0X/Bs1l23dK+Afl+WJhw/80aTeb+TLUJzw5uE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LLpso7V2gsJduzFv32KCsUTzGY6jdDmeGYd9if4cTQqJ5TY2ovgzg5ZM0AfB4lrm0
	 FOcUO/Z67ZxjahNACt+5I4+HQ10C55hLwxU49NbTowEyC0PzRqc27VlG5e1jPGOE8w
	 eH4tfHn4TOg5peqd6KJqhTs2BCjelWlUshZ7AEx4=

**Comment by kundanrock** [comment]
Both are same it was my bad.

**Comment by dafeder** [comment]
No problem!
