### ISSUE TITLE
Unable to harvest data "source is missing"

### ISSUE THREAD

**Issue by yudasakura** [NuCivic/dkan#1918]
I've been trying to use the DKAN Harvest by enabling the dkan_harvest_datajson module. And using the demo node.json output at "http://demo.getdkan.com/api/dataset/node.json" with no results. I'm using Dkan v13 and I always get this same message with no logs on drupal after running:
"drush --user=1 dkan-h test_from_demo"
![image](https://cloud.githubusercontent.com/assets/8119332/26332591/452c3a1e-3f1d-11e7-824f-482db37b7be7.png)

 Is there anything I'm not doing or missing?

**Comment by rhabbachi** [comment]
@yudasakura The `dkan_harvest_datajson` module extend the harvest to add support for [POD type endpoint](https://project-open-data.cio.gov/v1.1/schema/). From the demo site that would be This endpoint: http://demo.getdkan.com/data.json

That endpoint you used is the datasets Dkan endpoint which very useful but not POD formatted.

**Comment by janette** [comment]
Thanks @rhabbachi ! @yudasakura this sounds resolved so I will close it. You can find more information in the docs: http://dkan.readthedocs.io/en/latest/components/harvest.html
