### ISSUE TITLE
Reset button should reset facets

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1953]
CIVIC-5912

## Description

If you have search facets applied on the search page, the reset button should remove them. At the moment, the reset button only affects the search page form.

## Acceptance Critiera

Given I have facets applied on the search page
When I press the Reset button
Then all of the facets should be reset as well as any field selections

**Comment by dafeder** [comment]
![screen shot 2017-03-07 at 12 10 38 pm](https://user-images.githubusercontent.com/309671/27297371-937b39e6-54f2-11e7-9e10-3837f403b0ff.png)

**Comment by msolv** [comment]
This was fixed here: https://github.com/NuCivic/dkan/pull/1968
