### ISSUE TITLE
Count and delete resources on Harvest source deletion

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1969]
The confirmation dialog when you delete a harvest source only references datasets. When a harvest source is created, resources and groups are also created. It would be clearer if 

a) all content associated with the harvest source that will/won't be affected is listed in the dialog.
b) when deleting all _datasets_ belonging to a source, all _resources_ are deleted as well

![screen shot 2017-01-05 at 6 24 05 pm](https://user-images.githubusercontent.com/309671/27485641-82982ba0-57fb-11e7-9afb-6253af9b6b19.png)

## Acceptance Criteria

1. Confirmation dialog says:
> The following sources were selected to be deleted:
> Harvest Source Name: 18 Datasets, 29 Resources
> No groups generated during harvest will be affected by this action. They must be manually managed.

2. Resources are deleted if datasets are deleted

**Comment by dangur** [comment]
https://github.com/NuCivic/dkan/pull/1988

**Comment by msolv** [comment]
The PR has been merged. Closing this.
