### ISSUE TITLE
unable to edit ODSM schema maps

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1974]
CIVIC-6513

Reported by @sheldonrampton: Open Data sites return a 500 error when trying to edit ODSM schema maps. This is happening on all of the APIs that I tried to edit. The error is tied to the *distribution Multivalue Field*. I am able to create and save new APIs, and I am able to edit them and resave them. However, if I save an API with a value of "Resource," the 500 error occurs, and I am therefore no longer able to edit it.

Error is reported as:

```
[15-Jun-2017 22:46:52 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16547661 bytes) in /mnt/www/html/████████/docroot/includes/cache.inc on line 465 request_id="v-8642f0d0-521c-11e7-93ea-0a4d6b13166d"
```

This does not happen on versions earlier than 1.13. Currently it also does not happen on the `7.x-1.x` branch, where the latest `1.13.4` changes have not been merged. Presumably, then, this bug was introduced between 1.13.3 and 1.13.4.

## Steps to reproduce

* Log in as a site manager or administrator to a site on the `1.13.4` branch
* Visit/admin/config/services/odsm
* Click on the edit link for the "data.json 1.1 API"
* You will get a 500 error message.
* You will get the same result if you click on the edit link for any of the other APIs on the ODSM page.
* Now go to the ODSM page and click on the "Add API" button at admin/config/services/odsm/add/api
* You will be able to create a new API. Fill it in as though you are creating a data.json API, with the following values before hitting submit:
  * Entity type: Node
  * Bundle: Dataset
  * Endpoint: test.json
  * Output format: json
  * Schema: Project Open Data v1.1
* Click the "Create API" button. This will create the API, and you will be able to continue editing. Fill in values for some of the fields in the schema. You will be able to enter and save values and continue editing for any of the fields *except* the field named "distribution Multivalue Field."
* Now select "Resource" for the "distribution Multivalue Field" and click the "Update API" button. Once you do so, the 500 error message will appear, and you will no longer be able to edit the new API that you just created.
* If you examine the `test.json` feed that you created with the new API, you will see that it works and that the Resource option got saved when you saved it to the distribution Multivalue Field, showing that the form submission worked as it should. The problem is that once that value has been saved, Drupal starts throwing an error when it tries to render the API edit form.

## Acceptance criteria

* Administrators and site managers should be able to edit APIs without experiencing 500 errors.
* Adding a value to the "distribution Multivalue Field" should not cause HTTP 500 errors when rendering the API edit form.

**Comment by dafeder** [comment]
This only occurs when we have less than 256mb memory allocated to PHP. Solution is to increase the memory limit for the DKAN application, or at least for this specific page.

**Comment by frayber** [comment]
Same error for me, when I try to edit but not in all schemas, I get error 500 with nothing in error log.
I raised memory_limit to 4096 without success.
