### ISSUE TITLE
landingPage missing from data.json feed

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#1975]
CIVIC-6512

Reported by @sheldonrampton: The landingPage field is missing from data.json feeds for datasets that have been manually created. This is happening because the schema definition for data.json fields defines the Homepage URL (landingPage) field as follows:

```
[node:field_landing_page:url]
```

Previously the landingPage field was defined as:

```
[node:url]
```

The earlier field mapping displayed the URL of the dataset where it appears on the DKAN site. The new mapping will display the URL of harvested datasets where they appear on their source websites. However, it fails for datasets that have been manually added directly to the DKAN site. To correct this, the landingPage field should be defined as:

```
[node:field_landing_page:url] || [node:url]
```

## Steps to reproduce
* Log into a DKAN site as an admin or site manager and visit the Edit API form for the Data Json 1.1 API at path /admin/config/services/odsm/edit/data_json_1_1
* Inspect the Homepage URL (landingPage) field, and you will see that it has a value of `[node:field_landing_page:url]`
* Inspect the site's data.json feed. You will see that the landingPage field is missing from datasets.
* Edit the Homepage URL (landingPage) field in the Edit API form to give it a value of `[node:field_landing_page:url] || [node:url]`
* Now re-inspect the data.json feed, and you will see that the landingPage field appears.

## Acceptance criteria

* The default value for the Homepage URL (landingPage) field in all project open data schemas should be `[node:field_landing_page:url] || [node:url]`
* The landingPage field should appear in data.json dataset listings for both harvested datasets as well as for datasets that have been manually created.

**Comment by dangur** [comment]
https://docs.google.com/spreadsheets/d/1xs8B3frnnZGjkdwQmuTk3HdD-QECEDs2JoHbCkl1l1U/edit?usp=sharing
