### ISSUE TITLE
License block - field setting and search configuration 

### ISSUE THREAD

**Issue by upieper** [NuCivic/dkan#200]
The current license search block display is problematic:

1. The acronym for the license is displayed instead of the name of the license, which is not very meaningful for the casual user:

        admin/structure/types/manage/dataset/fields/field_license:
        gfdl|GNU Free Documentation License

        acronym: gfdl  
        full name: GNU Free Documentation License

This can quickly be changed by modifying the "Available options" in admin/structure/types/manage/dataset/fields/field_license:

    Creative Commons Attribution|Creative Commons Attribution
    Creative Commons Attribution Share-Alike|Creative Commons Attribution Share-Alike
    Creative Commons CCZero|Creative Commons CCZero
    Creative Commons Non-Commercial (Any)|Creative Commons Non-Commercial (Any)
    GNU Free Documentation License|GNU Free Documentation License
    License Not Specified|License Not Specified
    Open Data Commons Attribution License|Open Data Commons Attribution License
    Open Data Commons Open Database License (ODbL)|Open Data Commons Open Database License (ODbL)
    Open Data Commons Public Domain Dedication and Licence (PDDL)|Open Data Commons Public Domain Dedication and Licence (PDDL)
    Other (Attribution)|Other (Attribution)
    Other (Non-Commercial)|Other (Non-Commercial)
    Other (Not Open)|Other (Not Open)
    Other (Open)|Other (Open)
    Other (Public Domain)|Other (Public Domain)
    UK Open Government Licence (OGL)|UK Open Government Licence (OGL)

(and changing the demo datasets and the default value)

2. In the search/facet configuration, the field is by default defined as "fulltext" instead of string, resulting in license acronyms that are further broken into pieces (admin/config/search/search_api/index/datasets/fields): 

        cc-by-sa|Creative Commons Attribution Share-Alike
        displayed in separate lines: cc, by, sal

This can be fixed by changing the "Type" from "Fulltext" to "String". 

Screenshots of the combined issue:
Currently, the block looks like this:

![screen shot 2014-08-20 at 11 04 24 am](https://cloud.githubusercontent.com/assets/2594179/3982966/79157fc2-287b-11e4-8f70-7d7377041cca.png)

Preferable would be a block like this:

![screen shot 2014-08-20 at 11 04 10 am](https://cloud.githubusercontent.com/assets/2594179/3982970/84ee49a0-287b-11e4-828f-b7a4e131aaf7.png)

**Comment by dafeder** [comment]
Field license is now set to string in DKAN
