### ISSUE TITLE
Make json output human readable

### ISSUE THREAD

**Issue by upieper** [NuCivic/dkan#201]
It would be nice to change the json output (both in dkan_dataset and in open_data_schema_map), so that it is more human readable. An example site with the output we like http://www.usda.gov/data.json. 

I have forked the two repositories, made the necessary changes and issued pull requests. It would be great if you agreed to commit it like this or similar. 

https://github.com/NuCivic/dkan_dataset/pull/45
https://github.com/NuCivic/open_data_schema_map/pull/14

**Comment by janette** [comment]
An alternative would be the JSONview plugin for chrome https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc
