### ISSUE TITLE
Data harvesting with /data.json runs out of memory

### ISSUE THREAD

**Issue by haoliangyu** [NuCivic/dkan#2023]
When I try to download the `data.json` from a data portal, it returns the following message after a long run

``` html
<br />
<b>Fatal error</b>:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 24 bytes) in
<b>C:\path\to\dkan\profiles\dkan\modules\contrib\token\token.tokens.inc</b> on line
<b>379</b>
<br />
```

It seems the portal has too many datasets and the `/data.json` API cannot deal with them.

**Comment by dafeder** [comment]
Hi - @haoliangyu it sounds like this is an issue with the server providing the data.json feed, not DKAN itself, correct? I think we were discussing some kind of pagination solution for this, but that will require some kind of customization as the harvester currently doesn't support this automatically. Please let me know if I should keep this ticket open.

**Comment by haoliangyu** [comment]
@dafeder From my perspective it seems DKAN were trying to generate the complete data.json in memory before sending to me and the giant data.json just ate all memory. I am not sure whether it's DKAN's problem or the portal server's problem. I think I just want to let you know that this problem happened to me. However, after this issue happening months ago, I cannot remember which portal has the problem now.

**Comment by dafeder** [comment]
OK @haoliangyu - I agree there should be a better way to harvest from very large portals, and we'll keep that in mind for future harvest types we may ship with DKAN. I'm going to close this for now but please feel free to re-open if the issue comes up again and you'd like more help.
