### ISSUE TITLE
Investigate Datastore tests failing in CircleCi

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#2073]
## Description
error: **Couldn't find No imported items. within 30 seconds**

- resource.admin.feature (Scenario: Delete items on datastore of any resource)
- resource.editor.feature (@resource_editor_7)

These scenarios will usually pass if you run them locally but usually fail in CircleCi
Is there a better way to test this funcionality

![nucivic_healthdata__1409_-_circleci](https://user-images.githubusercontent.com/314172/29837890-2828e594-8cbf-11e7-9c18-6d05fc6e6f75.png)

![test-failure-screenshot-2017-08-29-12-33-13_i-wait-for--no-imported-items--](https://user-images.githubusercontent.com/314172/29838090-c3da6ad0-8cbf-11e7-905e-f08a8e7842b5.png)

**Comment by fmizzell** [comment]
After talking with @dafeder and @janette, we agreed that the current PR is a band-aid and what should be a deeper dive into the performance of this user workflow. The real solution might be to try to unit test the DKAN specific functionality if possible. Further work would be to dig into that possibility.

**Comment by dkinzer** [comment]
I converted all the datastore files in s3 to be only 3 records long.
