### ISSUE TITLE
UI for ODSM cache

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#2082]
CIVIC-6658

As a site administrator, I want to be able to understand and control the ODSM File Cache, so that my data.json and other endpoints behave as expected.

## Acceptance Criteria

* There is a column for filecache status in the main ODSM API list
* The column has either the cache age ("6 hours") or "none"
* Status links to a filecache management page for the specific API
* Each filecache can be deleted, generated or refreshed from the interface

**Comment by dafeder** [comment]
Assigning back to @dkinzer - tests are not passing. Also, needs QA steps in Pull Request.

**Comment by dkinzer** [comment]
All requested changes have been made.

**Comment by dafeder** [comment]
We sill need tests but that can be handled in a separate ticket.
