### ISSUE TITLE
dkan_dataset:  Form validation error if field_link_api is removed from Resource fields

### ISSUE THREAD

**Issue by infofinity** [NuCivic/dkan#209]
Related to NuCivic/dkan#208. Requirement to remove link to file and link to API fields from Resource. When doing this and trying to add a resource with an uploaded file and not giving it the required title, receive this notice:

Notice: Undefined index: field_link_api in dkan_dataset_resource_node_form_validate() (line 340 of /var/www/html/dkan/sites/all/modules/dkan_dataset/dkan_dataset.forms.inc).

**Comment by dangur** [comment]
Changed and added validation
