### ISSUE TITLE
Chart Legends Overlapping Graphs

### ISSUE THREAD

**Issue by jvitello** [NuCivic/dkan#2092]
## Description
The legends on visualizations are overlapping the graphics. This is true for all sites running DKAN 1.13.6 and using data visualizations. https://www.data.va.gov/story/economic-opportunities-veterans, https://data.ri.gov/story/2016-phase-1-pilot-municipalities 

## Acceptance Criteria
Chart labels shouldn't overlap graphics.

**Comment by jvitello** [comment]
PR in this repo:
https://github.com/NuCivic/recline.view.nvd3.js/pull/47

**Comment by janette** [comment]
If we force a 30 for single item legends and 0 for multi item legends it seems to adjust as needed:
https://github.com/robinfhu/nvd3/commit/33221877a773ba1611ec641a0f00eb06a4228809
