### ISSUE TITLE
Horizontal bar charts Are Failing to Auto-Adjust Labels

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#2097]
## Description

On multiple DKAN sites, Charts created with the Visualization entity are failing to resize themselves in order to accommodate chart elements.

In this example from a test site (9/5/17), the values being measured along the Y-axis have been "smushed" together. Instead, the labels should have auto-spaced themselves, and the Chart should have resized itself:

![screen shot 2017-09-06 at 11 32 39 am](https://user-images.githubusercontent.com/5174815/30120543-227254e4-92f7-11e7-977e-c6b7fb7d2323.png)

This may be related to an issue where charts were not resizing to accommodate legend elements #2092 

## Steps to Reproduce

- Create a resource using the attached data
- create a chart using a file with many rows (file attached below)
- add one or more series and select city for x-field
- select horizontal bar chart type
- finish and view

[many_rows.csv.zip](https://github.com/NuCivic/dkan/files/1281713/many_rows.csv.zip)

## Acceptance criteria

- labels on horizontal bar charts do not overlap when using data with many rows

**Comment by jvitello** [comment]
I edited this issue. The legend overlapping is handled by #2092 and I was only able to reproduce the label overlapping with horizontal charts that have many rows.

**Comment by janette** [comment]
To fix the crowding of labels on a horizontal chart would require the user to increase the height of the chart, that functionality was lost but restored here https://github.com/NuCivic/recline.view.nvd3.js/pull/45
And should be on the next patch release of dkan.

**Comment by kimwdavidson** [comment]
This will be in version 1.3 of vis_ent. In 1.13.8 or 1.14 of DKAN.
