### ISSUE TITLE
Dataset download permissions

### ISSUE THREAD

**Issue by prazor** [NuCivic/dkan#212]
Hi there,
I saw there is a posibility to set "Public Access Level" for a dataset. Now I'm not sure is this a bug or not:
It doesn't matter which level I set here (Restricted of Private), it seems that the recource is always downloadable. With restricted or private level I'm not allowed to view them (Explore data), but however I'm able to download them. Is this an error, or do I forgot some settings?
Regards

**Comment by takuya310** [comment]
We need to make sure the same point of Mr.Prazor wrote.
In CKAN, only users belongs to an organization which tethered to the dataset can browse the dataset when we make it private.

We tried the same settings in DKAN.
We tried to do so through og access control module.
http://drupal.stackexchange.com/questions/20116/how-to-make-a-og-private

1)Open the dataset field settings page.
(admin/config/group/fields）
2)Add the Group content visibility field.
3)Open the dataset configure page, set the value of Group content visibility to what we want.
That makes anonymous users not be able to browse the data.

Thank you.
