### ISSUE TITLE
Print: remove the search bar

### ISSUE THREAD

**Issue by alexiscott** [NuCivic/dkan#2141]
User story: As a user, when I print a page, I should not see the search bar, so that space on my page is used efficiently.

**Comment by alexiscott** [comment]
Description
===
Showing the search bar on printed pages is not useful, and amounts to a waste of space.

QA Steps
===
1. Go to file/print on any page in the site and.
2. The search bar should not show on printed pages.

**Comment by iris-i** [comment]
Hi @alexiscott, This removes the search bar on top as required. I came across a page that has an extra search bar at the bottom and it was displayed in the print page (/dynamic-transportation-visualizations). I'm wondering if we should remove that too? Or maybe open another ticket to hide all search input elements in the print stylesheets?

**Comment by alexiscott** [comment]
@iris-i yes, let's remove that too. Could you send me the URL, please? 
I do like the idea of finding a global solutions mind you for all search input fields, but not quite sure how easy that would be to achieve?

**Comment by iris-i** [comment]
Sure. url: http://demo.getdkan.com/dynamic-transportation-visualizations.
To hide the search boxes globally we could consider just not displaying any forms in print pages. i.e simply target all `form` elements.

**Comment by alexiscott** [comment]
Thanks, @iris-i 

 Do you think that there could be an issue, let's see if someone needed to print out a form that they had to fill in?

**Comment by iris-i** [comment]
oh right, that would be inconvenient :) . I thought about going more granular with 
`form form-item-search`
 but that leaves us with an adjacent sibling element for the submit button
``` <input type="submit" id="edit-submit--2" name="op" value="" class="form-submit btn btn-default btn-primary compact-form-input">```
maybe 
`form form-item-search` & 
`form form-item-search + input[type = "submit"]`?
