### ISSUE TITLE
Link to About DKAN Video is broken

### ISSUE THREAD

**Issue by iris-i** [NuCivic/dkan#2160]
The video in the About page the Get DKAN demo site is broken. Also broken in sandboxes.
http://demo.getdkan.com/about

**Comment by kimwdavidson** [comment]
Let's remove the video for now then make a new ticket about a possible new video

**Comment by janette** [comment]
The _front_ page and _about_ page are placeholder content and we didn't want them to be in features so they are built with fixtures, we'll need to update the configuration in the dkan_default_content module.
