### ISSUE TITLE
Resource is not saving

### ISSUE THREAD

**Issue by kevindavis338** [NuCivic/dkan#2163]
Hi there,

Every time I'm trying save a resource I'm getting an following error:
The URL is invalid.

It is based on the following url:
http://hostname/?q=node/624/edit

Why would I be getting that error?

**Comment by janette** [comment]
@kevindavis338 can you list the exact steps you are doing because we can not reproduce the error. http://demo.getdkan.com/dataset/florida-bike-lanes/resource/77a00c9d-5637-405e-9a26-6b5bf17cf466

**Comment by kevindavis338** [comment]
Hi there,

Here is what is going on..

1. I go to the resource
2. I click on New Draft (similar to the edit )
3. It turns into the following url: http://hostname/?q=node/624/edit
4. I click on save button

That is where I get the error.

**Comment by janette** [comment]
@kevindavis338 
So the resource you are trying to edit is node/624?
What value do you have in the remote link field?
Can you provide a screenshot?

**Comment by kevindavis338** [comment]
Here are the screenshots showing the sequence of events. It is not that particular resource but on all resource.  I can save the pages and datasets. 

![2017-10-17 1](https://user-images.githubusercontent.com/4030822/31687963-64fec878-b350-11e7-8e14-e5e1697ca625.png)
![2017-10-17 2](https://user-images.githubusercontent.com/4030822/31687964-6519f33c-b350-11e7-8d3a-e18f6570c172.png)
![2017-10-17 3](https://user-images.githubusercontent.com/4030822/31687965-65324734-b350-11e7-8d8c-00704a3346b4.png)
![2017-10-17 4](https://user-images.githubusercontent.com/4030822/31687966-654196b2-b350-11e7-81e0-b1a1d75e3557.png)

**Comment by kevindavis338** [comment]
Well, I made some changes to the settings to feeds import and now I'm getting the following error: 

**Error: Call to undefined function feeds_node_prepare() in dkan_datastore_node_update() (line 307 of /dkan/dkan/profiles/dkan/modules/dkan/dkan_datastore/dkan_datastore.module).**

**Comment by kevindavis338** [comment]
The url is invalid has been resolved, however, the current resource isn't saving.
