### ISSUE TITLE
DKAN not honouring OG private access members only setting

### ISSUE THREAD

**Issue by jmgurgeh** [NuCivic/dkan#218]
Hi, I am wanting to constrain access to Datasets and Resources to (by default) only be accessible to members of the publishing Group.

I followed the steps from this link: http://drupal.stackexchange.com/questions/85261/non-members-of-organic-group-can-still-view-node-links
answer by Loloy D to configure the DKAN content types Dataset and Resource to have the OG field "Group Content Visibility" added and configured it to be private access to members only by default.

However, it seems to have no effect. Non-members of the group still have full access to any of the Datasets or Resources with access set to private...

Has anyone else managed to make this work?

I am using drupal 7.31 and the "1.3" drop of DKAN.

**Comment by drkloc** [comment]
this has been sitting idle for a couple of months now. Closing. Re-open if needed.

**Comment by andrepearce** [comment]
Hi, I am having this exact issue. I cannot restrict access to any datasets or resources. The OG permissions are not being obeyed at all. I would really appreciate your help with this. 

Thanks.

**Comment by andrepearce** [comment]
I managed to solve my issue by disabling the `og_moderation` module. Having it enabled was causing all of the og visibility permissions set to be dishonouring.
