### ISSUE TITLE
How to make "Upload a file" the default tab?

### ISSUE THREAD

**Issue by eindgebruiker** [NuCivic/dkan#251]
On the Create Resource page "Link to a file" is the default tab. I would like to make "Upload a file" the default, but have no idea how to do that.
I tried rearranging the fields on the Resource content type, setting the htab "open", changing the weights with a form_alter, tried hook_field_group_build_pre_render_alter.

Where is this set, and how can I change it?

**Comment by acouch** [comment]
> everything is working fine.

Closing.
