### ISSUE TITLE
Can't install visualization extensions via Drush

### ISSUE THREAD

**Issue by cdoten** [NuCivic/dkan#264]
Following the instructions here line-by-line:
https://github.com/NuCivic/visualization_entity/wiki/Installation

And i'm not able to use Drush to install any of the visualization pieces

`cdoten@console:/var/www/html/datatest$ drush make --no-core sites/all/visualization_entity/visualization_entity.make`
`Make new site in the current directory? (y/n): y`
`Beginning to build                                         [ok]`
`sites/all/visualization_entity/visualization_entity.make.`
`No release history was found for the requested project     [warning] (geo_file_entity).`
`cdoten@console:/var/www/html/datatest$ drush -y en visualization_entity`
`visualization_entity was not found.                        [warning]`
`No release history was found for the requested project     [warning] (visualization_entity).`
`There were no extensions that could be enabled.            [ok]`

Unsurprisingly given this "Entity Types" does not appear in the Structure menu. Choropleth and GeoJSON extensions fail as well.

Thoughts? The files are here:
`sites/all/visualization_entity/modules/visualization_entity_`...

**Comment by janette** [comment]
@cdoten improvements have been made to visualizations charts since you've reported this issue, try updating your build. http://dkan.readthedocs.io/en/latest/introduction/maintaining.html#basic-upgrades
