### ISSUE TITLE
Explore dataset issue on IE < 11

### ISSUE THREAD

**Issue by tiger-damon** [NuCivic/dkan#282]
We seem to be getting the following issue when exploring some datasets (CSV) using IE versions less than 11.  

When viewing a dataset, we get the following error: 

Error returned from datastore: [object Object].

Anyone seen this or know the cause? (I think it the issue may lie in the recline library)

**Comment by janette** [comment]
@tiger-damon cross browser improvements have been made to recline and the grid previews should be functioning in all supported IE browsers now.
