### ISSUE TITLE
Undefined index: es en dkan_open_data_build_dataset_resources()

### ISSUE THREAD

**Issue by merolhack** [NuCivic/dkan#287]
Hi,
i receive the next error when i view the resource in the languague "Spanish (es)":

`Notice: Undefined index: es en dkan_open_data_build_dataset_resources() (línea 199 de /profiles/dkan/modules/dkan/dkan_dataset/modules/dkan_dataset_api/dkan_dataset_api.inc).`

I resolve adding this to the line 199 and stablish "en" languague by default:
`        if ( isset( $node->field_upload[$node->language][0] ) ) {`
`                $file = $node->field_upload[$node->language][0];`
`        } else {`
`                $file = $node->field_upload['en'][0];`
`        }`

Best regards,
Lenin Meza

**Comment by acouch** [comment]
We are using the ODSM module now. Please reopen if there is an issue using the ODSM module or if you have any questions.
