### ISSUE TITLE
Add dashboard capability using Panels and the Visualization Entity

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#290]
This is in the works.

**Comment by acouch** [comment]
We have added panels as the layout engine for DKAN. Working on adding visualization entity.

**Comment by janette** [comment]
Done

Create charts:
http://dkan.readthedocs.io/en/latest/components/visualizations/visualization_entity/chart.html

Create data stories: 
http://dkan.readthedocs.io/en/latest/components/storytelling.html
