### ISSUE TITLE
Theme hook not found in field_group_table

### ISSUE THREAD

**Issue by eindgebruiker** [NuCivic/dkan#297]
If I add fields to group_additional of content type dataset, and view a dataset node, a warning will show up in the watchdog for every field that is left empty: "Theme hook not found."

That's actually "Theme hook %hook not found."

In field_group_table.module:
      foreach (element_children($element) as $k) {
        // Grab rendered version first.
        $rendered = theme($element[$k]['#theme'], $element[$k]);

$element[$k]['#theme'] will be NULL.

**Comment by drkloc** [comment]
@eindgebruiker i think this was fixed recently. Can you try reproducing this with the most recent 7.x-1.x

**Comment by acouch** [comment]
This has been fixed: https://github.com/nuams/field_group_table/commit/b1ff5a4f191d9c05e168f6ebe769c37173615b67
