### ISSUE TITLE
PHP notices when installing DKAN

### ISSUE THREAD

**Issue by sheldonrampton** [NuCivic/dkan#300]
After running the DKAN installation script, I get some PHP warning notices, as pictured here:

![image](https://cloud.githubusercontent.com/assets/2838758/5252862/9b0daaae-7967-11e4-8bef-e43209747afb.png)

**Comment by populist** [comment]
I can confirm the errors still show up on the current dkan-drops repository. Perhaps it just needs an update from the current codebase?

**Comment by acouch** [comment]
We've pushed a new version, tagged here as 7.x-1.7 which fixed the issue:

![screen shot 2015-02-24 at 4 59 44 pm](https://cloud.githubusercontent.com/assets/512243/6361304/92d2adea-bc46-11e4-8f8f-a61e42a6d7dc.png)
