### ISSUE TITLE
Legend/Key Customization

### ISSUE THREAD

**Issue by nditechteam** [NuCivic/dkan#302]
As it currently stands, all titles in the legend/key to the side of the map in the choropleth visualizations are lowercase. Ideally, we would like these titles to match the name of the data column (so if the column title is Other, the map legend title next to the selection box should read 'Other', not 'other' as it currently does). Thanks.

**Comment by janette** [comment]
Choropleth functionality is experimental and not enabled at this point. Any community contributions are always welcome.
