### ISSUE TITLE
Hover over box customization

### ISSUE THREAD

**Issue by nditechteam** [NuCivic/dkan#303]
We would like to be able to change the "hover over" box on the choropleth visualizations to appropriately match the geographic area in question. As it stands, every map reads "hover over state" regardless of the level of geographic breakdown. If this could mesh with the geographic level of the map (i.e. State or Zone or District, etc.) that would be great. Thanks.

**Comment by janette** [comment]
Choropleth support is still experimental at this point, anyone interested in jumping in on this feature please feel free to contribute pull requests: http://dkan.readthedocs.io/en/latest/components/visualizations/visualization_entity/choropleth.html?highlight=choropleth
