### ISSUE TITLE
SearchApiException thrown when trying to search for dataset

### ISSUE THREAD

**Issue by Viktour19** [NuCivic/dkan#309]
![capture](https://cloud.githubusercontent.com/assets/3490854/5326383/f422963c-7d17-11e4-88f3-68eff5851ac1.PNG)

After installing the DKAN App  from Windows Azure Gallery, I keep getting this error:
SearchApiException: Trying to search on field field_resources:body:value which is no indexed fulltext field. in SearchApiQuery->fields() (line 530 of D:\home\site\wwwroot\profiles\dkan\modules\contrib\search_api\includes\query.inc)
anytime I search for a dataset

**Comment by janette** [comment]
@Viktour19 I don't think there is active development on that app, perhaps you can follow up here https://github.com/acouch/DKAN-Azure
