### ISSUE TITLE
Add Dataset REST API using services

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#310]

**Comment by acouch** [comment]
We have this working except for tests https://github.com/NuCivic/dkan_dataset/tree/310_dataset_rest_api/modules/dkan_dataset_rest_api

**Comment by Krista-Nuams** [comment]
Does DKAN now use a REST compliant API?

**Comment by Vanuan** [comment]
So, this won't be CKAN API compatible?

**Comment by dafeder** [comment]
@Vanuan for now, no. We will still publish CKAN endpoints for harvesting by other CKAN sites, but for now we haven't seen enough demand for CRUD operations via REST using the CKNN API and schema.

**Comment by dafeder** [comment]
...but obviously any contribution bridging that gap would be welcome!
