### ISSUE TITLE
Database issue when upgrading to latest version

### ISSUE THREAD

**Issue by jbaumgartner-ndi** [NuCivic/dkan#312]
After creating a new clean install, the site works fine.  After moving old data from sql dump to the new server, there was a php error:

PHP Fatal error:  require_once(): Failed opening required '/var/www/dkan/sites/all/modules/contrib/entity/includes/entity.wrapper.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/dkan/includes/bootstrap.inc on line 3198

The previous install had the entity.wrapper.inc file at this location:

/var/www/dkan/profiles/dkan/modules/contrib/entity/includes/entity.wrapper.inc

I'm not sure if that was due to a difference in installation.  It would be nice if there was a clean way to upgrade the code while retaining the DB contents.  Any suggestions on how to do this?  I'd be happy to remove code and insert new code but that may not be ideal moving forward.

Thanks!

**Comment by janette** [comment]
@jbaumgartner-ndi could you review the upgrade instructions here: http://dkan.readthedocs.io/en/latest/introduction/maintaining.html#basic-upgrades and get back to us if you continue to have issues.
