### ISSUE TITLE
QA POD 1.1 schema

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#314]
follow this -> https://github.com/NuCivic/dkan/pull/313

**Comment by dafeder** [comment]
See https://github.com/NuCivic/dkan/pull/313#issuecomment-74578750

**Comment by dafeder** [comment]
All remaining validation issues were due to underscores in the domain name, a fringe case that has been brought to the attention of the validator's maintainers. See GSA/project-open-data-dashboard#82
