### ISSUE TITLE
DKAN Graphing 'Group Column' Data Not Aggregating 

### ISSUE THREAD

**Issue by nditechteam** [NuCivic/dkan#315]
When trying to create a graph in DKAN with a given resource, the 'group column' that is selected does not appear to be functioning as intended. We thought that when graphed, the data would aggregate by group column, as opposed to re-titling every x-axis bar (in this bar chart example) by the group column. For example, the image below (we thought) should should 1 column per state, as opposed to multiple columns per state
![untitled](https://cloud.githubusercontent.com/assets/6877174/5462982/c1ccba28-8546-11e4-88fd-369abcbcac8e.png)
. Please let us know if further clarification is needed.

**Comment by nditechteam** [comment]
Hi @acouch any word on how this ticket is progressing? We'd love to help test any additions/upgrades to the graphing feature within resources in DKAN. Thanks!

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:14564)
	by server23.websitehostserver.net with esmtps (UNKNOWN:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.82)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1Y8c94-000EJw-8V
	for greg@biomassiv.es; Tue, 06 Jan 2015 15:58:35 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=smtpapi; bh=+61WXCFUg/ytQCjy77hn8dPWSEs=; b=iBSJU5QfUJCA0TYlKS
	G0dg/xzOfZCYZKu/mKRg8owu8U5eDPVF2ankR5KkvLxvYSXfNi08JtUamsUvY0MV
	sB9zHxEvihnfoJlYcH5TASAqRmBD2bUHl28v/MJqKhdy4GXhHkb52pNzJezGq+VA
	vZgr4Lq7ZdokJGuojxBtzevjY=
Received: by filter0030p1mdw1.sendgrid.net with SMTP id filter0030p1mdw1.26092.54AC5A88C
        2015-01-06 21:58:33.099829809 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-024 (SG) with ESMTP id 14ac141a757.6cc3.5751a
	for <greg@biomassiv.es>; Tue, 06 Jan 2015 21:58:33 +0000 (UTC)
Date: Tue, 06 Jan 2015 13:58:32 -0800

**Comment by federicca** [comment]
this isn't possible in recline. won't do.
