### ISSUE TITLE
Technical evaluation of DKAN

### ISSUE THREAD

**Issue by ALeicht** [NuCivic/dkan#329]
Hello! My team is conducting tool evaluations prior to building a Data Set Catalog, and I was wondering if anyone knows of or would be willing to share a (somewhat formal) technical evaluation of DKAN. I have found formal evaluations for CKAN open source software (the most comparable tool to DKAN), but it seems like the newness of DKAN means that there haven't been as many detailed evaluations produced at this point. I appreciate your help!

**Comment by acouch** [comment]
Thanks for asking. Can you share the technical evaluation of CKAN? We may have some resources internally or be able to help fill in missing information.

**Comment by ALeicht** [comment]
Hi Aaron,

Thanks for your prompt response. I'm attaching an evaluation of CKAN from
the University of Lincoln, UK. At this point, we are trying to get a sense
of how DKAN compares to CKAN in terms of extensibility. It seems like DKAN
is similarly flexible to CKAN and also benefits from the thousands of
Drupal modules. However, because DKAN is newer, there aren't as many case
studies/evaluations/exemplars for us to look at. One concern is that,
although DKAN is modeled after CKAN, there might be certain features
missing. Can you speak to that at all? Also, I would appreciate any DKAN
resources (outside of the documentation) that you can share.

Thanks,
Anna

**Comment by acouch** [comment]
I didn't receive your email or attachment. Can you email me at ``aaron`` ``@`` ``nucivic.com``?

**Comment by acouch** [comment]
I've received your email. Will have a reply this week. Thanks!

**Comment by andrewhoppin** [comment]
Anna, there is a comprehensive evaluation published by the World Bank of DKAN and a range of other platforms here, specifically for their applicability for National Statistical Organizations; DKAN is on page 32: 

http://www-wds.worldbank.org/external/default/WDSContentServer/WDSP/IB/2014/12/01/000469252_20141201092022/Rendered/PDF/928100WP0Techn0Box385378B000PUBLIC0.pdf

If you do create a new evaluation, we'd love to see it!  And please do feel free to reach out with any other questions general or specific.
