### ISSUE TITLE
Error when deleting Resources through admin/content management

### ISSUE THREAD

**Issue by Kopec** [NuCivic/dkan#332]
Hello,

just ran into a problem when I deleted eight resources from admin console. The Dataset was no more accessible, entity wrapper something (at the time I forgot to take notes) error was on the Dataset page and prevented editing and deleting of Dataset. Finally I solved the problem by removing links to two of eight missing resources from table something_field_resource and clearing cache (then I was able to view and delete dataset). sorry I haven't got more info.

martin 

P.S. I am using newest version of DKAN distribution on apache on windows (fairly recent versions of php and mysql)

**Comment by acouch** [comment]
Thanks for you noting this. We will try and recreate ourselves. Will post a reply soon.

**Comment by drkloc** [comment]
@Kopec this could be related to **ref_field** bug we solved in NuCivic/dkan_dataset#78. Could you try rebuilding or just applying these two patches -> https://github.com/NuCivic/dkan_dataset/pull/78/files#diff-64b1b569653d8299bb11f2110f2796e7R116

**Comment by drkloc** [comment]
I'm confident that rebuilding will solve this issue. Closing
