### ISSUE TITLE
fail to migrate from CKAN

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#335]
I'm harvesting data from CKAN(dataset) using DKAN migrate.
When I'm trying, error is displayed. Like this.

Invalid argument supplied for foreach() File /var/www/dkan/profiles/dkan/modules/contrib/ref_field/ref_field_sync.module, line 206

So, change ref_field_sync.module(l205) like this, I could import.
if (isset($fields_name))
→ if ($fields_name)

Check description method is mixed in this source.
Please confirm.
Thank you.

**Comment by acouch** [comment]
Thank you for noting that. This should be fixed here: https://github.com/NuCivic/dkan_dataset/pull/78

**Comment by drkloc** [comment]
@takuya310 if you rebuild you'll be fine. Please confirm and close the ticket if everything is working for you

**Comment by drkloc** [comment]
@takuya310 I'm confident that rebuilding will fix your issue (it just does what you did). Closing.

**Comment by takuya310** [comment]
Other work is busy, it was not able to test.
It was sorry for not immediately able to correspond.
@drkloc @acouch  Thank you so much.
