### ISSUE TITLE
Provide a plain url field formatter for recline field!

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#336]
The only two formatters available now are:
+ recline.js formatter
+ datastore status formatter

We need:

+ Plain url rendering
+ html Link to the resource file

so folks can use those resources in stuff like views.

**Comment by drkloc** [comment]
this is in. Closing.

**Comment by boabjohn** [comment]
Sorry guys, not seeing this working. I've given an outline of my process here:
https://groups.google.com/forum/#!topic/dkan-dev/n3tdy_4yzF8 (last comment in thread).
