### ISSUE TITLE
Provide update function in dkan.install to migrate 1.6 -> 1.7 (context -> panels)

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#339]
It should:

- [x] Disable/uninstall dkan_sitewide_context
- [x] Enable dkan_sitewide_panels
- [x] Enable nuboot_radix
- [x] Make sure panel page at /welcome is set as the frontpage
- [x] Set up nuboot_radix as default theme & admin_theme
- [x] Migrate nuboot and colorizer settings to nuboot_radix
- [x] Disable nuboot

- [x] Also provide panels -> context 
- [ ] Disable view page at `/dataset/`

**Comment by drkloc** [comment]
moving to drush commands

**Comment by acouch** [comment]
This was completed. Cleaning up old tickets.
