### ISSUE TITLE
Recline call to leaflet library broken

### ISSUE THREAD

**Issue by boabjohn** [NuCivic/dkan#340]
G'Day good DKAN people,
We have an install with latest Leaflet and libraries and 0.7.3 of the leaflet.js...however our Drupal status check refuses to locate the version of Leaflet....thus no maps.
I'm no coder, but a kind soul on d.o assisted with the cluetrail:
https://www.drupal.org/node/2152423#comment-9567995
Let me know if I can be of further assistance.
JB

**Comment by drkloc** [comment]
hey @boabjohn Did you update Leaflet yourself?

Either way, If you tell me what version are you running we can launch a qa site with exactly that version of dkan to walkthrough the issues..

Glad to see you participating here as well mate.

**Comment by boabjohn** [comment]
G'Day @drkloc,
So sorry about dropping the thread...had two other site launches to get through and am now back to this issue.
I've started a thread on the docs site asking how to update just dkan_dataset.
And I'll also chase up your comments on the dkan_developers list.
So I'll close this thread and chase the other two.
Thanks again for your support!
