### ISSUE TITLE
Add "honeypot" to prevent spam registrations, etc.

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#341]
We should add honeypot.module to DKAN core.  

Lots of user registrations happen on various public DKANs.

**Comment by acouch** [comment]
Lets do this.

**Comment by Krista-Nuams** [comment]
agreed

**Comment by pmackay** [comment]
Ha, I *just* added this to a new DKAN site I'm building :)

**Comment by dafeder** [comment]
- [ ] Add specific version to https://github.com/NuCivic/data_starter/blob/master/build.make
- [ ] Make sure it's turn on by this script -> https://github.com/NuCivic/data_starter/blob/master/scripts/rebuild-nucivic-data.sh

**Comment by drkloc** [comment]
- [ ] Add specific version to https://github.com/NuCivic/dkan/blob/7.x-1.x/drupal-org.make
- [ ] Add dependency to info file -> https://github.com/NuCivic/dkan/blob/7.x-1.x/dkan.info
- [ ] If needed, create code to set settings in the profile file -> https://github.com/NuCivic/dkan/blob/7.x-1.x/dkan.profile

**Comment by drkloc** [comment]
Will write the tests as part of #502
