### ISSUE TITLE
Error With DKAN Datastore and feedwws_flastore_processor

### ISSUE THREAD

**Issue by suhasgr** [NuCivic/dkan#342]
Hi

I am getting the following error. Please help
Fatal error: Call to undefined function feeds_get_importer_ids() in /ip/workshop/www/drupal7/sites/all/modules/dkan_datastore/dkan_datastore.module on line 115

**Comment by drkloc** [comment]
please see #169

**Comment by drkloc** [comment]
closing, this is a duplicate of #169
