### ISSUE TITLE
Update version in .info file

### ISSUE THREAD

**Issue by pmackay** [NuCivic/dkan#343]
Noticed that although DKAN is on v1.6, the .info file contains `version = 7.x-1.x`. Should this be being updated?

**Comment by acouch** [comment]
Thanks for asking. 

The idea is that the 7.x-1.x branch is on 7.x-1.x and the tag should have the tag number.

The 1.6 tag should say 1.6 not 1.x https://github.com/NuCivic/dkan/blob/7.x-1.6/dkan.info

I am not sure it is worth updating that tag but we will make sure to correct that for the 7.x-1.7 release.

**Comment by drkloc** [comment]
I need to update the script to do that. Doing it right now.

**Comment by drkloc** [comment]
Ok, everything ready for next version will include the proper version in ```dkan.info```. Thanks for the feedback @pmackay.

Closing this.
