### ISSUE TITLE
Ho to customize standard dkan homepage

### ISSUE THREAD

**Issue by aborruso** [NuCivic/dkan#345]
Hi,
I know I can change the hero background, but how is it possible to modify the default four blocks of homepage?

Thank you

**Comment by drkloc** [comment]
@aborruso with the new panels based frontpage you can do that easily (among other things). I need to write documentation for that, i'll report back as soon as i have it.

**Comment by aborruso** [comment]
@drkloc could you give the URL to open this panels based front page?

Thank you

**Comment by drkloc** [comment]
@aborruso i have this piece of documentation ready. I'll update the docs site today.

**Comment by drkloc** [comment]
@aborruso -> http://docs.getdkan.com/dkan-documentation/dkan-users-guide/customize-dkan-pages-layouts-and-components-using-panels

**Comment by aborruso** [comment]
Hi @drkloc , thank you very much, really great work!

My problem is that I do not have 1.7. Then I must make an upgrade.

Thank you so much

**Comment by drkloc** [comment]
@aborruso it'll definitly be much easier to customise dkan if you update to 1.7 or even better try to have an updated 7.x-1.x

Good luck!
