### ISSUE TITLE
Resource URL in API is the url of the HTML page for the resource, not the actual resource data file

### ISSUE THREAD

**Issue by Bjwebb** [NuCivic/dkan#348]
e.g. http://demo.getdkan.com/api/3/action/resource_show?id=107dac9c-2896-4142-9c09-e7257a87037c
Behaviour: `url` is http://demo.getdkan.com/dataset/wisconsin-polling-places/resource/107dac9c-2896-4142-9c09-e7257a87037c 
Expected Behaviour: `url` is http://demo.getdkan.com/sites/default/files/Polling_Places_Madison_0.csv

As far as I can tell there is no way to get the URL of the actual data file through the API.

For, comparison, in CKAN, `url` is the URL of the data file. e.g.
http://demo.ckan.org/api/3/action/resource_show?id=f472af82-aa6c-46f0-8475-2f154ac1b01a
`url` is http://demo.ckan.org/dataset/4dff1a58-df52-46c8-b611-bcdd01cddea3/resource/f472af82-aa6c-46f0-8475-2f154ac1b01a/download/agenda2.csv

At a glance, I would think the relevant piece of DKAN code is https://github.com/NuCivic/dkan_dataset/blob/7.x-1.x/modules/dkan_dataset_api/dkan_dataset_api.inc#L191

This issue is with dkan_dataset, but as an unprivileged user, I can't add the appropriate label.

**Comment by acouch** [comment]
Thanks for noting this. This is actually controlled at ``/admin/config/services/odsm/edit/ckan_package_show``

Change the URL field to ``[node:field-resources:Nth:field-link-api:url] || [node:field-resources:Nth:field_link_remote_file] || [node:field-resources:Nth:field-upload:url]``

and ``/admin/config/services/odsm/edit/ckan_resource_show``

change the URL field to:

``[node:field-link-api:url] || [node:field_link_remote_file] || [node:field-upload:url]``
![screen shot 2015-02-12 at 5 36 04 pm](https://cloud.githubusercontent.com/assets/512243/6179321/d1bc107c-b2dd-11e4-9081-86aae635bc6f.png)

I made these updates in a branch in the open_data_schema_map_dkan module here: #349 We will QA and add to DKAN if the tests pass.

**Comment by acouch** [comment]
This has been updated on the dev branch: http://demo.getdkan.com/api/3/action/package_show?id=dfa5a0fb-5ac4-4509-8be5-12f94c61593b

Please reopen if you have any questions.

**Comment by Bjwebb** [comment]
Looks good, thanks.
