### ISSUE TITLE
About behavior of harvesting

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#350]
I have to need to harvesting from CKAN.
So, we tried two cases using migrate module and compare with CKAN.
1. Harvesting CKAN to CKAN.
2. Harvesting CKAN to DKAN.

Case 1 can harvest actual resource data file.
Case 2 can harvest links to resource data file but can't harvest actual resource data file.

Which behavior is correct in DKAN?
I think we are happy if we can choice above two patterns.

**Comment by dafeder** [comment]
The migration classes will attempt to harvest the file itself if the API identifies the url_type as "upload". Otherwise it will simply provide a link to the file's URL.

**Comment by takuya310** [comment]
Thanks.
Do I need to write this setting to the source code in dkan_migrate_base_resource.inc variable $row->url_type?

Do you define the description method of not the "upload"?

**Comment by janette** [comment]
@takuya310 you could harvest your CKAN data into DKAN if you create a data.json file of your CKAN data: http://extensions.ckan.org/extension/datajson/

Then create a harvest source from the above url. Documentation here: http://dkan.readthedocs.io/en/latest/components/harvest.html#dkan-harvest
