### ISSUE TITLE
Dependency on Gravatar not documented.

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#352]
I hit a fatal error on my /user page:

> PHP Fatal error: Call to undefined function _gravatar_load_account() in sites/all/themes/nuboot_radix/template.php on line 225

Should this theme really require gravatar? Would be nice if this was not a hard dependency...

Thanks!

**Comment by acouch** [comment]
Thanks for pointing out. I wrapped it in a module_exists: https://github.com/NuCivic/nuboot_radix/commit/afe6a6ba21ddb5c02aeba18eb8c778a83a6e220d

We will try and get that in before releasing next.

**Comment by acouch** [comment]
This code has been included in 7.x-1.x . If Gravatar is not present nuboot_radix should be fine.
