### ISSUE TITLE
Move panels doc to docs site

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#356]
Move https://github.com/NuCivic/slo/wiki/DKAN-Panels to docs.getdkan.com

**Comment by drkloc** [comment]
Done -> http://docs.getdkan.com/dkan-documentation/dkan-features/customize-dkan-pages-layouts-and-components-using-dkanpanels

**Comment by drkloc** [comment]
@dafeder Whenever you have 5' could you:

- [ ] Check if the writing is clear enough
- [ ] Check if location of documentation item within the book makes sense


http://docs.getdkan.com/dkan-documentation/dkan-features/customize-dkan-pages-layouts-and-components-using-dkanpanels

**Comment by dafeder** [comment]
1. Made some revisions: http://docs.getdkan.com/node/91/revisions/view/480/481. The screenshots should be updated to say "pane" instead of block

2. I would put this under DKAN User's Guide. Maybe add a line or two to the main DKAN Features page referencing it.

**Comment by drkloc** [comment]
on it

**Comment by acouch** [comment]
awesome work!!

**Comment by drkloc** [comment]
corrections are in place -> http://docs.getdkan.com/dkan-documentation/dkan-users-guide/customize-dkan-pages-layouts-and-components-using-panels

please review and close
