### ISSUE TITLE
Remove notices for "Gravatar integration"  "OG Extras"  "Link iframe formatter"

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#365]
These notices for the above modules are deceiving. We should block them. We could use: https://github.com/NuCivic/dkan/blob/7.x-1.x/modules/dkan/dkan_sitewide/dkan_sitewide.module#L106

![screen shot 2015-02-18 at 4 16 28 pm](https://cloud.githubusercontent.com/assets/512243/6256942/33f9c36e-b78a-11e4-850e-146aa0c74915.png)

**Comment by acouch** [comment]
Lets block them and set a drupal_set_message for the page saying, "X Module is up to date. We are using X revision (git hash)."

**Comment by acouch** [comment]
You can try this: https://api.drupal.org/api/drupal/includes!bootstrap.inc/function/drupal_installation_attempted/7

**Comment by acouch** [comment]
Ah, see you already have :)

**Comment by msolv** [comment]
Yes, thank you! :)

Closed.
