### ISSUE TITLE
Can't map UTM coordinates (not to be confused with lat/long)

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#369]
See below screenshots of the CSV and resulting map. If I put the X and Y columns in as latitude and longitude fields, the map zooms outward to the global view. No points can be seen.

X/Y coordinates are an alternative to latitude and longitude, typically plotted using GPS devices. There are ways to convert them to latitude and longitude, and it would be a good feature to have.

![screen shot 2015-02-20 at 2 40 31 pm](https://cloud.githubusercontent.com/assets/9059428/6308089/412261d2-b90f-11e4-97df-fc397b6cc7d2.png)

![screen shot 2015-02-20 at 2 47 36 pm](https://cloud.githubusercontent.com/assets/9059428/6308128/76e700c0-b90f-11e4-8682-cca764d328fc.png)

**Comment by dafeder** [comment]
Can you find some documentation for this format? There must be a more specific name for it than "X/Y". I've been googling a bit and it seems like even within the GIS world "X/Y coordinates" can mean different things in different contexts.

**Comment by stefaniefgray** [comment]
@dafeder Did some research on this format! It was frustrating, because most hits for X/Y coordinates + GIS led to ArcMap tutorials, not relevant info about the coordinates used in this sort of file.

Turns out that this format is the Universal Transverse Mercator coordinate system: http://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

Says Wikipedia: "The Universal Transverse Mercator (UTM) conformal projection uses a 2-dimensional Cartesian coordinate system to give locations on the surface of the Earth. It is a horizontal position representation, i.e. it is used to identify locations on the Earth independently of vertical position, but differs from the traditional method of latitude and longitude in several respects."

There's a solution for converting this format to latitude and longitude, but it's a bit complicated/horrifying: http://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#From_UTM_coordinates_.28E.2C_N.2C_Zone.2C_Hemi.29_to_latitude.2C_longitude_.28.CF.86.2C_.CE.BB.29

**Comment by stefaniefgray** [comment]
Changed name of ticket accordingly

**Comment by topicus** [comment]
I think we have to provide a kind of coordinate converter. There is a library to transform coordinates according to projections. http://stackoverflow.com/a/18621253/1043580

Some cities use their own coordinates systems to prevent measurement deviations and with this we would allow them upload data without make a coordinate conversion previously.

**Comment by stefaniefgray** [comment]
@topicus Is it possible to provide a coordinate converter or should I close this for now?

**Comment by stefaniefgray** [comment]
Closing this for now after speaking with @topicus yesterday about how the extra JavaScript may or may not be worth it at this point in time.
