### ISSUE TITLE
Support for XLSX files

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#372]
I can't view XLSX files as maps, graphs or grids unless I go back and save them as a CSV. 

Additionally - though I haven't been able to replicate this - I uploaded an XLSX file, put the filetype as XLS, and got an error message that the formats weren't the same.

**Comment by dafeder** [comment]
Recline relies on a data proxy for XLS files, which is a, remote service. The reason it was failing this weekend was because the service itself went down. We should come up with an alternative that. Maybe using https://github.com/SheetJS/js-xls or something like that?

**Comment by dafeder** [comment]
What do you think @topicus?

**Comment by akuckartz** [comment]
XLSX is not really an open format due to its unnecessary complexity compared to ODS.

**Comment by topicus** [comment]
@dafeder We could create a module to activate this feature using that library and this other as well https://github.com/SheetJS/js-xlsx

I don't know what's the browser support for those libraries.

**Comment by drkloc** [comment]
+1 on js-xlsx.

**Comment by drkloc** [comment]
https://github.com/SheetJS/js-xlsx#tested-environments

**Comment by acouch** [comment]
If we want to move forward with this we should try and do it upstream with Recline if possible. It might be preferable to try and do this on the server side http://phpexcel.codeplex.com/ or support XLS in the datastore

**Comment by drkloc** [comment]
that one is available as a composer library. Maybe a recline submodule so we don't force the composer dependency? recline_xls ?

**Comment by topicus** [comment]
@acouch Maybe providing some dataproxy like okfn does?

**Comment by topicus** [comment]
We build this backend. We just need to plug this into our recline views. https://github.com/NuCivic/recline.backend.xlsx

**Comment by dafeder** [comment]
## Story

I want to be able to preview XLS files the same way I can with CSV files.

## Context

We need to add the new XLS backend to our recline implementation.

**Comment by dafeder** [comment]
Looks like this is not ready to go for the release. Punting.

**Comment by janette** [comment]
CIVIC-1268
CIVIC-1270
