### ISSUE TITLE
Add ability to add change description when updating a dataset

### ISSUE THREAD

**Issue by hdinh** [NuCivic/dkan#373]
When a user updates a dataset, currently there is no way to document the reason why the dataset was changed. You would have to diff multiple datasets and manually take the time to understand what changed.

This request is for an optional comment dialog that would allow the modifier to specify the reason that the dataset gets changed.

The change reason would be shown in the revisions window

![screen shot 2015-02-21 at 3 45 00 pm](https://cloud.githubusercontent.com/assets/1069646/6315951/bbbc96b6-b9e0-11e4-8651-e46f50c03aad.png)

**Comment by dafeder** [comment]
There is a field at the bottom of the dataset form, Revision Log Message, in the revision information tab. That's what you're looking for. 

![screen shot 2015-02-24 at 12 06 51 pm](https://cloud.githubusercontent.com/assets/309671/6354691/1304aacc-bc1f-11e4-980b-c3b1a37a1a62.png)

**Comment by hdinh** [comment]
Ah, I didn't even see that! Perhaps, this should be more streamlined?

I guess my user story is that I'm used to working with git and being forced to write the change description. I looked for the description field for about 15 minutes before I thought it didn't exist. But now I know where it is :)

**Comment by acouch** [comment]
> Ah, I didn't even see that! Perhaps, this should be more streamlined?

I believe you are correct. We'll try and think about how to best do that. If you have any suggestions please let us know.
