### ISSUE TITLE
Uploading a dataset does not modify the API service

### ISSUE THREAD

**Issue by hdinh** [NuCivic/dkan#374]
When you upload a new dataset, the API access service does not change

1) Open an existing dataset (CSV is OK, must have API access)
2) Check the API result
3) Re-upload a new CSV
4) Check the API result. It does not update to respect the new changes - at least not immediately

**Comment by dafeder** [comment]
@hdinh - Did you re-import the resource into the datastore? The API draws from the datastore, and the CSV must be manually imported each time.

**Comment by drkloc** [comment]
If it does not show **inmediately** then is a caching issue. Does clearing the cache make the API result to display properly?

**Comment by hdinh** [comment]
I definitely didn't re-import the resource into the datastore. That's probably it.

Maybe a newb question:
Why does someone have to do reimport the data into the datastore each time? Intuitively, as a user all I know is that the API is now not up to date with the datasource.

**Comment by drkloc** [comment]
@hdinh are we talking about the dataset API-> http://demo.getdkan.com/api/3/action/package_show?id=30eefb20-908d-48cc-aee3-99196ea70ec9 ?

or the datastore API -> http://demo.getdkan.com/api/action/datastore/search.json?resource_id=66b870f9-972c-4c26-83a3-2fc770c4992f&limit=5

**Comment by hdinh** [comment]
The issue refers to the dataset API

**Comment by drkloc** [comment]
It's a cache issue then, the datastore is not involved.

**Comment by drkloc** [comment]
@hdinh feel free to reopen this ticket (or open a new one) if you want us to clear the cache for the dataset api on node_save. Closing this

**Comment by Katsivelisp** [comment]
Hi @drkloc, do you maybe have any tips on how to clear the feed import cache immediately after node_save? That would be really of huge help when we want to make periodic changes to the uploaded Resources. Thank you in advance!
