### ISSUE TITLE
current_package_list_with_resources has duplicate resources

### ISSUE THREAD

**Issue by Bjwebb** [NuCivic/dkan#376]
Specifically, the first dataset is okay, but the second dataset has the first dataset's resources in addition to its own. The third dataset has the first and second dataset's resources in addition to its own.... etc.

e.g. see http://demo.getdkan.com/api/3/action/current_package_list_with_resources

**Comment by Bjwebb** [comment]
Looking more closely at the output, it seems that all child elements are duplicated. groups and tags build up in exactly the same way.

I think this might be an issue with https://github.com/NuCivic/open_data_schema_map but haven't confirmed that, so haven't reported an issue there yet.

**Comment by acouch** [comment]
I'm taking a look right now. It is definitely an issue with ODSM. Will report back as soon as I can.

**Comment by msolv** [comment]
Hi @Bjwebb! We've uploaded a fix and it's working now: http://demo.getdkan.com/api/3/action/current_package_list_with_resources

Thanks for reporting this!

**Comment by Bjwebb** [comment]
Looks good, thanks!

**Comment by pmackay** [comment]
@msolv the demo link appears to be down. Also could I ask when this might be available in a release, and do you prepare a Pantheon drop soon after making a release?

thanks!

**Comment by acouch** [comment]
@pmackay we just pushed a release right before this. we won't push for another couple of weeks.

**Comment by acouch** [comment]
@pmackay I think if you just patch this manually it won't get missed on the next release since it is already in the 7.x-1.x branch
