### ISSUE TITLE
Changing Colorizer settings requires clearing caches

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#385]
When changes are made to colorizer as an admin, the settings change the file that holds the colorizer settings.

This is reflected immediately to the logged in user. However for the anon user the change in colorizer file means that the current colorizer settings are broken.

We should clear the caches after saving colorizer settings. Check first in the colorizer module and maybe submit a patch there: https://www.drupal.org/project/colorizer

![screen shot 2015-02-26 at 9 40 19 am](https://cloud.githubusercontent.com/assets/512243/6395085/b260b264-bd9b-11e4-9826-39b5d29d0e9c.png)

**Comment by janette** [comment]
We are using a patched version of colorizer that made for rgb values, I should probably finish a more generalized version so it would get merged into the standard module.

**Comment by msolv** [comment]
I uploaded a patch for the latest colorizer version here: https://www.drupal.org/node/2444249

Are we going to continue using 1.0 version? The latest is 1.4. If so I'll upload a patch specifically for that version.

**Comment by janette** [comment]
- [ ] upgrade colorizer to 1.4
- [ ] add patch to make file https://www.drupal.org/files/issues/colorizer-2444249.patch
- [ ] add patch to make file https://www.drupal.org/files/issues/colorizer-add-rgb-vars-2227651-4b.patch
