### ISSUE TITLE
Demo overhaul (New datasets and visualizations needed)

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#389]
## Add new datasets to:

- [ ] EbolaData.org
- [ ] demo.getdkan.com
- [ ] data.nucivic.com

### All three demos need to:

- [ ] Have an eye-catching design
- [ ] Use the latest release of DKAN
- [ ] Demonstrate scalability for large datasets, particularly ones that Socrata can't handle.
- [ ] Have a compelling mix of data, stories and tools including:
  - [ ] A Choropleth map
  - [ ] A CartoDB map
  - [ ] An ESRI ArcGIS map
  - [ ] An example of a Tableau visualization

## Modules that should be added to each demo's DKAN distribution:
- [ ] Choropleth bundle
- [ ] Data visualization bundle
- [ ] NVD3

## Demos would also be improved by (according to Federica):
- [ ] Adding more datastore features
- [ ] Better API capabilities
- [ ] Better previews. 
- [ ] Showing off our schema mappers and make it part of our core functionality.
- [ ] Showing that DKAN is more complete than CKAN or Socrata.

**Comment by Krista-Nuams** [comment]
Since Rent Control will be in the news again this year and there is 2015 data here http://www.nycrgb.org/html/resources/zip.html It would be cool to do some map work on the demo for that.
We'll also need a Federal example and a non US example to show off.

**Comment by jayenashar** [comment]
not sure where you are with this issue @stefaniefgray, but [demo.getdkan.com](http://demo.getdkan.com) (linked from the readme, very high google rank) throws a lot of php errors and [EbolaData.org](http://EbolaData.org) doesn't load for me

**Comment by dafeder** [comment]
demo.getdkan.com was just down temporarily this morning. This ticket was about adding content over a year ago - closing!
