### ISSUE TITLE
About description of data API Documentation

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#400]
"Documentation" part in data API page, it's description is like this.
See DKAN API documentation for more details: <a href="http://docs.getdkan.com/docs/dkan-documentation/dkan-api/datastore-api">DKAN Datastore API</a>

Is this description which "<a>" is appeared deliberate?
I consider whether or not trying to fix.

**Comment by dangur** [comment]
Updated documentation can be found at http://dkan.readthedocs.io/en/latest/apis/index.html
