### ISSUE TITLE
Support Description field for file object in Recline

### ISSUE THREAD

**Issue by boabjohn** [NuCivic/dkan#406]
On a Resource bundle, the recline file field concept looks similar to Drupal's filefield formatter, but lacks the capacity to specify a Description label.
The [Show Description] option can be enabled in the content type>Upload field definition, and the Description form element is provided on the node form, but when the node is saved recline simply omits the [Description] element altogether.
What this means, in the case of a PDF file attachment (for example) is that there is no option to display Description text as the download label: we are only able to display the filename itself. The filename can be highly awkward to format and quite human-unreadable. Normally, we would expect to hide the filename and display the Description element as a download link label.

**Comment by kimwdavidson** [comment]
We think seeing the file name is helpful and clearer, but you can definitely do what you've described here on your own site, and we'll certainly keep in mind ways to make that part of the page more helpful. 

(Sorry for the long wait on a response here! CivicActions has just become the DKAN maintainer, so we're looking through all the issues in this backlog now. Thanks for submitting!)
