### ISSUE TITLE
output of package_show api is different from CKAN

### ISSUE THREAD

**Issue by hissan1983** [NuCivic/dkan#410]
Hi. I'm Hiroyuki Terada. I use DKAN in Japan.

I tried to dkan migrate from DKAN to DKAN.
But I can't migrate dataset.

I investigation probrem, so I found that output of package_show api is different from CKAN.

In CKAN, top 4 line of return value is :
{
  help: "Return the metadata of a dataset (package) and its resources. :param id: the id or name of the  
    dataset :type id: string :rtype: dictionary ",
  success: true,
  result: {

but in DKAN, return value is:
{
  help: "Return the metadata of a dataset (package) and its resources. :param id: the id or name of the   
  dataset :type id: string :rtype: dictionary",
  success: true,
  result: [
    {

result is numeric array variable, but associative array may be right.

I think this resolved by edit that line 573 of dkan_dataset_api.module like that:
$output['result'] = $row → $output['result'] = $row[0]
Is it right ?

Thanks.

**Comment by hissan1983** [comment]
I solved parts of problem by install open_data_schema_map_dkan.
I read https://github.com/NuCivic/dkan/issues/195
But I can't get value of 'id' on but value of 'name' got on http:/HOSTNAME/api/3/action/package_list
I want get value of 'id' to make argument to http:/HOSTNAME/api/3/action/package_show?id=

How can I get id of dataset ?

**Comment by acouch** [comment]
The ``id`` for ``package_show`` can be the name found at ``package_list`` or the uuid of the dataset: http://demo.getdkan.com/api/3/action/package_show?id=gold-prices-london-1950-2008-monthly

So you can get the id from the ``package_list`` endpoint: http://demo.getdkan.com/api/3/action/package_list

**Comment by hissan1983** [comment]
Thank you for answer my question.

I found package show by use name found at package_list.
I misunderstand that argument of package_show is only uuid.
