### ISSUE TITLE
About authority of viewing data set

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#411]
In the field of data set, there is a setting of public access level.
In order not to browse to the anonymous user, I set a public access level of anonymous user to private.
And, I've set inaccessible to private data in the Data Workflow module.

However, when I set Publishing options of dataset is "Publish", anonymous users will be able to browse the data set. Do I need other settings?

**Comment by janette** [comment]
@takuya310 the public access level is a metadata value for the dataset not a visibility setting.
See: https://project-open-data.cio.gov/v1.1/schema/#accessLevel

If you want to restrict access to the datasets see my notes here: https://github.com/NuCivic/dkan/issues/498#issuecomment-314907401
