### ISSUE TITLE
Recline.visualization Views formatters broken

### ISSUE THREAD

**Issue by boabjohn** [NuCivic/dkan#413]
Hi guys,
Sorry for the re-post here...I did not see how to re-open a ticket. See references here:
https://github.com/NuCivic/dkan/issues/336

Quick re-cap:
Test-fail with latest DKAN profile on clean install and using DKAN sample data.
When adding the Upload field to a display, then accessing the Format drop-down, the system begins to freeze. All selections past this point result in a "missing slice" error.

**Comment by janette** [comment]
Ref: https://github.com/NuCivic/recline/pull/17
