### ISSUE TITLE
Behavior of Tika and Facet API 

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#414]
Install the solr and attachment, was to enable the Facet API.
When you access the page by clearing the cache, adapter.inc is invoked. 
You will see an error such as the following.

Warning: reset () expects parameter 1 to be array, null given FacetapiAdapter-> getFacetSettingsGlobal () (/var/www/dkan/webroot/profiles/dkan/modules/contrib/facetapi/plugins/facetapi/adapter.inc l 839).

Maybe I need setting in the "Facet API Pretty Paths", but I do not know the cause. 
Please let me know if you know about this.
Thanks.

**Comment by acouch** [comment]
Thanks for reporting this. I haven't had an issue with Tika and Facet API like this on our projects. You might want to post an issue to the Tika https://www.drupal.org/project/issues/search_api_attachments?categories=All or Facet API project https://www.drupal.org/project/issues/facetapi

**Comment by takuya310** [comment]
Thanks.
I'll post Tika or Facet API project.
If the cause is found, I will share.
