### ISSUE TITLE
Sorting group names in alphabetical order

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#415]
Is there any way to sort Groups by alphabetical order instead of having them ordered by when they were uploaded? Helps a lot with providing a neater appearance.

Janette sorted the Groups this way for the HHS demo, but I would like to know if there's any way for site admins to do it without having to hassle any developers. :)

**Comment by dafeder** [comment]
You should be able to sort any view by editing it and adding/removing criteria from the sort section.
