### ISSUE TITLE
admin/config page is broken because of floating dd's and dt's

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#418]
It looks like this:

![screen shot 2015-03-23 at 1 32 39 pm](https://cloud.githubusercontent.com/assets/428070/6784889/1d9207e4-d161-11e4-9229-e44586556772.png)

It could be fix by:

```sass
.admin-list {
  dt, dd{
    display:inline-block;
    float:none;
    vertical-align: top;
  }
}
```

So it looks like:

![screen shot 2015-03-23 at 1 35 36 pm](https://cloud.githubusercontent.com/assets/428070/6784958/8a317b28-d161-11e4-9ef7-4cba1116ace9.png)

I have no problem submitting the PR myself, just want to see if @janette agrees with me (meaning, i'm not broking anything else by doing this)

EDIT: throw in ```vertical-align: top;``` in the mix as well.

**Comment by janette** [comment]
looks good @drkloc , there are a few admin pages that use dt, dd so I would check the other admin pages first

node/add
admin/structure

might want to try:
.page-admin {
  .panel-default { border-color: none; }
  .panel-default > .panel-heading { clear: both; }
}

**Comment by drkloc** [comment]
cool

**Comment by acouch** [comment]
Did this get in? :)

**Comment by drkloc** [comment]
Will do this today so it gets in the release.

**Comment by drkloc** [comment]
NuCivic/nucivic-internal#553
