### ISSUE TITLE
Unable to harvest from DKAN to DKAN harvesting

### ISSUE THREAD

**Issue by hissan1983** [NuCivic/dkan#419]
Hi.

I tried to harvest groups, datasets, and resources from dkan server to dkan server.
I use DKAN Migrate Base.

I can harvest groups and resources but I can't get datasets with this error:
Invalid argument supplied for foreach() File /var/www/dkan-demo/webroot/profiles/dkan/modules/contrib/ref_field/ref_field_sync.module, line 207

Would you teach me what should I Confirm?

**Comment by acouch** [comment]
There is a patch for ref_field sync which was added to dkan_dataset: https://github.com/NuCivic/dkan_dataset/blob/7.x-1.x/dkan_dataset.make#L156. A remade version of dkan_dataset should include that update. You can also apply the patch yourself which is only a couple of lines https://www.drupal.org/files/issues/ref_field-delete-insert-warning-2360019-0.patch

That will fix that warning.

Thanks for asking and please let us know how it goes or if you have any other bugs or questions.

**Comment by hissan1983** [comment]
Thank you for answer my question.

It was solved by add your patch. Warning message isn't be shown.

But I have other probrem when I tried get resouce from other DKAN server.
I'll write it at new issue, and close this issue.
