### ISSUE TITLE
Unable to harvest Resources

### ISSUE THREAD

**Issue by ghost** [NuCivic/dkan#421]
I tried to get resources from other DKAN server by using dkan_migrate_base.
But I unable to get with that warning "Warning: file_get_contents(http://demo.getdkan.com/api/3/action/http://my_site_url/sites/default/files/ckan-migrate-resource_list_MigrateCkanResourceBase): failed to open stream: "DrupalRemoteStreamWrapper::stream_open" call failed CKANListJSON->computeCount() (/var/www/dkan-demo2/sites/all/modules/dkan_migrate_base/dkan_migrate_base.migrate.inc ファイル　59行)."　at /admin/content/migrate.

When I investigate this problem, I found that it's may be cause of it.

https://github.com/NuCivic/dkan_migrate_base/blob/master/dkan_migrate_base_resource.inc#L56
In this file, $list_url is joint $this->endpoint and $list_url. But should it be '$list_url = $list_url' ?
When I rewrite like it, I can get resource without warning message.

**Comment by hissan1983** [comment]
When I tried above rewrite, /sites/default/files/ckan-migrate-resource_list_MigrateCkanResourceBase isn't rewrote.
In this case, result of $this->getResourceId($resource->id) is null at
https://github.com/NuCivic/dkan_migrate_base/blob/master/dkan_migrate_base_dataset.inc#L118

**Comment by ziodave** [comment]
Same issue here.

**Comment by acouch** [comment]
Thanks for raising this. We just updated that part of migrate base. We will have time to verify that it fixes what you've described next week.

**Comment by hissan1983** [comment]
Thank you for reply.

I tried now, but I can't migrate with following message:

Undefined property: stdClass::$data File /var/www/dkan-demo4/sites/all/modules/dkan_migrate_base/dkan_migrate_base.migrate.inc, line 86(file: /var/www/dkan-demo4/sites/all/modules/dkan_migrate_base/dkan_migrate_base.migrate.inc, line 86)
Loading of http://testsite.jp/sites/default/files/ckan-migrate-resource_list_MigrateCkanResourceBase failed:
Migration failed with source plugin exception: Passed variable is not an array or object, using empty array instead, in /var/www/dkan-demo/sites/all/modules/migrate/plugins/sources/list.inc:167

I use master branch of  https://github.com/NuCivic/dkan_migrate_base.git and https://github.com/nuams/dkan-drops-7.git

**Comment by poliveiraIPB** [comment]
Hi, i´m still having the same problem. Import datasets, works well, but import resources don´t work.
I´m using "$arguments['endpoint'] = 'my_site_address/api/3/action/" in both class MigrateCkanDatasetExample and class MigrateCkanResourcesExample. 
Please help.

**Comment by dafeder** [comment]
@poliveiraIPB sorry we never got back to you on this. The migration classes have been through a lot in the last 3 years and we now have a separate Harvester module, so assuming this is no longer an issue. Please feel free to re-open if necessary.
