### ISSUE TITLE
Recline can't handle percentages in charts

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#426]
See https://github.com/NuCivic/sldata/issues/3

This issue was fixed on the [Sierra Leone site](http://live.data.sierraleone.nucivic.build/) but to the best of my knowledge has not been fixed elsewhere.

![screen shot 2015-03-20 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/9059428/6921956/faf53bbc-d795-11e4-81e9-79109f46a5fd.png)

![screen shot 2015-03-20 at 1 24 06 pm](https://cloud.githubusercontent.com/assets/9059428/6921961/ff292658-d795-11e4-9150-f26abc01fa65.png)

![screen shot 2015-03-20 at 1 24 31 pm](https://cloud.githubusercontent.com/assets/9059428/6921965/03aabade-d796-11e4-9144-53816b2defa8.png)

**Comment by drkloc** [comment]
http://demo.getdkan.com/dataset/resource/51659140-3c8e-4ec8-8969-f93765db6d6b#{view-graph:{group:!Letter,series:[!P],graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},currentView:!graph,graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}

**Comment by drkloc** [comment]
this has been done for months. Closing.
