### ISSUE TITLE
Add CONTRIBUTING.md pages for dkan and components

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#432]
### Example

https://github.com/okfn/recline/blob/master/CONTRIBUTING.md

### Why we need this?

If we add this, a special warning pop ups every time a contrib developer is trying to create a PR. We can add information about:

+ Make sure there's an issue to relate the PR to
+ How to label the issue and the PR
+ Style of commits messages (issue numbers, etc)
+ Criteria to squash commits (cosmetics vs functionality)

### Components

We need to add this to:

- [x] NuCivic/dkan
- [ ] NuCivic/dkan_dataset
- [ ] NuCivic/open_data_schema_map
- [ ] NuCivic/open_data_schema_map_dkan
- [ ] NuCivic/dkan_datastore
- [ ] NuCivic/recline
- [ ] NuCivic/feeds_flatstore_processor
- [ ] NuCivic/nuboot_radix
- [ ] NuCivic/geofile_entity
- [ ] NuCivic/visualization_entity

Please add more checkboxes to the list above ^^^

**Comment by acouch** [comment]
:+1:
