### ISSUE TITLE
Drush Make: Create Database fails

### ISSUE THREAD

**Issue by boabjohn** [NuCivic/dkan#434]
When attempting a new, clean install, following the process here [1], we get to the stage of running:

drush site-install dkan --db-url="mysql://DBUSER:DBPASS@localhost/DBNAME"

The database exists, the user exists, and the user has all privileges ont he db, and the db priveleges have been updated.
In the command line, we get a MySQL fail (>SQLSTATE[28000] [1045] Access denied for user ... )

Repeated attempts, trying different privileged users, etc...all fail at the command line drush site-install.

Going back and starting over with new database, new user, etc...we again get the fail at command line.

Now, WITH NO CHANGES AT ALL, we go to the new website address and get the expect "Install Drupal" UI. We proceed with installation, and use exactly the same database and user credentials, and the database is created no worries. The site is up and running successfully.

So: I reckon this means something it amiss with how the drush site-install is being run....but that's way past my technical grasp.

---

[1] https://github.com/nucivic/dkan#drush-make

**Comment by drkloc** [comment]
@boabjohn is this happening on 7.x-1.x?

**Comment by janette** [comment]
No response, outdated, closing.
