### ISSUE TITLE
Packaging of Soft Products for a Move

### ISSUE THREAD

**Issue by robinmarvel** [NuCivic/dkan#439]
Relocating and shifting is not all regarding picking large objects, there are numerous compact and soft items too feature in the move. And these small objects are the most difficult ones to handle in a move. They are climate and handling delicate items. They include towels, linens, drapes, quilt, tablecloth, curtains and many other similar to these. They are prone to fungus and insects. Therefore utter caution is to be shown to keep them off of wetness. These are not fragile yet are vulnerable of their kind. 

For packaging linens and blankets you have to keep in mind couple of things. You need to pack them tightly to ensure no air might go through them as air can transplant wetness inside them which can produce pest in that. Pack and fold over them in big plastic bags. And after that, pack them in a box which has been layered with neat newspapers. For packaging towels make sure they are dried up totally. Store them wrapped in a small plastic bag then packet. Carpets ought to be vacuumed and sanitized effectively before packaging. You may also dry it in sun shade to get rid of insects and fungus expansion in that. Storing naphthalene balls in such products can save them from pest attempts. For packing pillows, place them in between bed mattress and then collapse bed mattress suitably, with outside cover of old bed sheet in it. These are the most convenient steps in which you can pack and shift your soft goods for a shift.

<a href="http://www.delhilocal.in/packers-movers-saket.html">packers and movers Saket</a>
<a href="http://www.delhilocal.in/packers-movers-mahipalpur.html">packers and movers Mahipalpur</a>

**Comment by acouch** [comment]
This looks like spam.
