### ISSUE TITLE
Recline module - Leaflet library showing as "not found" on libraries-list

### ISSUE THREAD

**Issue by kdawg22** [NuCivic/dkan#444]
https://github.com/NuCivic/recline/blob/7.x-1.x/recline.module#L240

Due to capitalization on Leaflet, doing a `drush libraries-list` shows:
`leaflet                Not detected  -        -                 -            `

libraries_get_libraries() is showing:
[Leaflet] => profiles/dkan/libraries/Leaflet

Adding 
`"machine name" => "Leaflet",`

fixes missing library issue

**Comment by drkloc** [comment]
![screen shot 2015-04-28 at 4 17 53 pm](https://cloud.githubusercontent.com/assets/428070/7378212/305d735e-edc2-11e4-8694-b15a4f8face6.png)

This is not happening for me anymore. @kdawg22 Can you confirm that this is happening to you with a build with the latest 7.x-1.x?

**Comment by drkloc** [comment]
closing
