### ISSUE TITLE
Make the recline app ajax callback timeout configurable

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#446]
https://github.com/NuCivic/recline/blob/7.x-1.x/recline.app.js#L90

It would be nice that that should could be configurable through an admin page

**Comment by acouch** [comment]
:+1:

**Comment by drkloc** [comment]
https://github.com/NuCivic/recline/pull/25

**Comment by drkloc** [comment]
@dafeder @acouch Does this diserves a page in the docs?

**Comment by drkloc** [comment]
@dafeder assigning QA to you, use NuCivic/dkan#448 for the qa site and NuCivic/recline#25 for Acceptance Test.

Assign back to me with directions for documentation (where to put it).

**Comment by dafeder** [comment]
OK will take a look at this asap.
