### ISSUE TITLE
Hook implementation to provide other namespaces and links to the dataset field_license

### ISSUE THREAD

**Issue by boabjohn** [NuCivic/dkan#447]
At the moment it appears that links to cc licenses are automatically linked to the definitions available at OpenDefinition instead of CreativeCommons. CC have a safe, predictable namespace for the Deeds. There should be no reason to route CC links through OpenDefinition instead of CC.
At the moment OpenDefinition lists only a small subset of CC Deeds.

Although we can easily add a name|value pair to the license taxonomy, we have no UI control over how the license links get built.

This means that our required licensing is displayed with an un-fixable dead link...and that our license reference is also opaque to the user.
Both of these are serious, unacceptable conditions for a well-managed service.

I have provided a bit more info in discussion thread here:
https://groups.google.com/forum/#!topic/dkan-dev/dl-vqwYCPpE

A sample of a dead license link can be seen here:
http://maps.capeyorknrm.com.au/dataset/wcttaa-feral-control-effort

This data is being provided "openly" to the public, and the data owners wish to use a cc-by-nc-nd (4.0, International)

Is this a valid DKAN usecase?
What needs to happen so that my license link is properly linked (and iconised)?

**Comment by drkloc** [comment]
- [ ] Provide the same list of licenses but through a form_alter implementation
- [ ] Provide a way for developers to subscribe additional license values through a hook implementation and append those while altering the form select field options
- [ ] Create new 'link to license' render function through options provided by the hook above
- [ ] Be backwards compatible with the way we are rendering the licenses in the current version (existing values render properly)
- [ ] Be backwards compatible with existing search

**Comment by drkloc** [comment]
We have implement this in a client project. Since it involves changing more than one component, will be introducing and testing changes across all of them during this week.
It would go something like this:
- [ ] Update for dkan_dataset_content_types with the new hooks and formatter for the options for the license field
- [ ] Update for dkan distro's dkan_sitewide_search_db to alter the way the license field is rendered
- [ ] Update for dkan distros's dkan_sitewide_blocks to alter the way the license block for a given node is being rendered
- [ ] Update for open_data_schema_map to render the license using the helpers provided in dkan_dataset_content_types

Stay tuned @boabjohn

**Comment by boabjohn** [comment]
Brilliant! Thanks so much for the careful and thorough approach: glad to 
know you're moving forward.

On 5/05/2015 5:51 AM, Teofilo Sibileau wrote:
>
> We have implement this in a client project. Since it involves changing 
> more than one component, will be introducing and testing changes 
> across all of them during this week.
> It would go something like this:
>
>   * Update for dkan_dataset_content_types with the new hooks and
>     formatter for the options for the license field
>   * Update for dkan distro's dkan_sitewide_search_db to alter the way
>     the license field is rendered
>   * Update for dkan distros's dkan_sitewide_blocks to alter the way
>     the license block for a given node is being rendered
>   * Update for open_data_schema_map to render the license using the
>     helpers provided in dkan_dataset_content_types
>
> Stay tuned @boabjohn <https://github.com/boabjohn>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NuCivic/dkan/issues/447#issuecomment-98832028>.
>

-- 
John Brisbin
BoaB interactive Pty Ltd
POB 248, MT Molloy QLD 4871

E: john@boab.info
M: 0407 471 565 | P: 07 4094 2172
Skype: boabjohn | Twitter: @boabjohn

**Comment by drkloc** [comment]
All is in. Will be QA'ing this one quite heavily.

**Comment by dafeder** [comment]
Needs documentation.

**Comment by drkloc** [comment]
Draft for documentation provided here -> http://docs.getdkan.com/dkan-documentation/extending-dkan/addingremoving-license-options-tofrom-license-field

Please review and close
