### ISSUE TITLE
Colorizer needs separate header text option so that headers can stand out over hero images

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#457]
![hhsscreenshot](https://cloud.githubusercontent.com/assets/9059428/7477069/8f72717a-f31f-11e4-845d-f61e8ce51466.png)

Headers need their own colorizer option and should no longer be lumped in with "Text color."

In this example, the "Search Data" header is set to adopt the same #3B3B3B dark gray color as all other site text. This makes it difficult to read above the hero image.

If I set the text color to white, the header becomes easier to read, but the rest of the text on the site also becomes white.

![hhsscreenshot2](https://cloud.githubusercontent.com/assets/9059428/7477236/7b9bbbe2-f320-11e4-9429-9707db634f9d.png)

**Comment by drkloc** [comment]
@stefaniefgray this has been fix in NuCivic/nuboot_radix#31

Please
+ go to https://github.com/NuCivic/dkan/pull/503
+ Test the acceptance criteria using the qa site

**Comment by stefaniefgray** [comment]
Verified fixed
