### ISSUE TITLE
Datastore API sort and join parameter not working

### ISSUE THREAD

**Issue by eGovCologne** [NuCivic/dkan#465]
The request parameters sort and join are not working as shown in http://docs.getdkan.com/docs/dkan-documentation/dkan-api/datastore-api 

Sort: No effect
Join: Not joining, only shows result of resource 1

**Comment by acouch** [comment]
Thanks for noting this. Here is the docs http://docs.getdkan.com/docs/dkan-documentation/dkan-api/datastore-api#Joining

**Comment by janette** [comment]
Fixed! Documentation here: http://dkan.readthedocs.io/en/latest/apis/datastore-api.html
