### ISSUE TITLE
Update features module in distro

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#467]
Features is currently five point-releases behind.
- [x] Move to current stable release of Features
- [x] Re-export all features
- [x] To test, install on previous version, then check old db against new codebase to see if any features show as overridden
- [x] Add tests to check for overridden state upon DKAN install

**Comment by drkloc** [comment]
@frankcarey please take a look at https://github.com/NuCivic/dkan_datastore/pull/43

**Comment by janette** [comment]
Done
