### ISSUE TITLE
WSOD when adding a resource to a newly created dataset

### ISSUE THREAD

**Issue by ziodave** [NuCivic/dkan#468]
After creating a dataset, moving on to step 2, http://dkan/node/add/resource?dataset=<dataset-id>, I get a WSOD.

After some investigation I found that the page fails when trying to render the _field_dataset_ref_ field with a _selection list_ widget. Changing the widget to _autocomplete_ will make the page work, but the newly created dataset is not preselected.

I believe that the _selection list_ widget fails because it tries to load all of the datasets in memory (I have more than 11.000).

**Comment by janette** [comment]
@ziodave many improvements have been made, please upgrade to the latest release https://github.com/NuCivic/dkan/releases
