### ISSUE TITLE
Add DKAN Fixtures to DKAN to Replace Defuault Content

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#472]
- [x] Add DKAN Fixtures https://github.com/NuCivic/dkan_fixtures to DKAN and run migration for the content in dkan_fixtures_default_content. 
- [x] Turn off the dkan_default_content module. 
- [ ] Ensure migration is succesful
- [ ] Write a change notice that this has occured in CHANGELOG.txt.

**Comment by acouch** [comment]
I started this at #473 

Please make sure that the default content is loaded during installation.

You can see the correct default content here: http://demo.getdkan.com/dataset There should be 4 datasets of the same name.

**Comment by Krista-Nuams** [comment]
Igor, where did you end up with this? Should we expect a pull request?

**Comment by chilic** [comment]
@acouch @Krista-Nuams 
I created PR https://github.com/NuCivic/dkan/pull/489, https://github.com/NuCivic/dkan_migrate_base/pull/21, 
https://github.com/NuCivic/dkan_fixtures/pull/9

This should fix most of all errors and bugs, but I still have problem like:
`Loading of profiles/dkan/modules/dkan/dkan_fixtures/data/_list.json failed`
`Loading of profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_fixtures_default/data/package_list`
`Loading of package_list.json failed`

I am not sure understand in which place this file should be allocated and how they should be imported in right place.
I think if we will fix this errors migrations should be finished normally.

**Comment by acouch** [comment]
@chilic This was great work thanks.

**Comment by chilic** [comment]
@acouch Thank you.

**Comment by dafeder** [comment]
Done on #1259
