### ISSUE TITLE
Create Single Formatter for Resource Fields

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#474]
Currently there are three fields to identify a resource:

![screen shot 2015-05-27 at 7 13 54 am](https://cloud.githubusercontent.com/assets/512243/7835643/2b4226d2-0440-11e5-89c0-8dee4ec80f66.png)

with two different formatters:

![screen shot 2015-05-27 at 7 16 04 am](https://cloud.githubusercontent.com/assets/512243/7835666/496d6824-0440-11e5-8e15-662a6ab250cd.png)

We would like to have a single formatter that is given an input (url or file) and decides the correct output based on the input.

Inputs would include

| file type | output |
| --- | --- |
| csv | recline preview |
| Excel | TBD |
| image | preview image |
| PDF | https://github.com/mozilla/pdf.js/ |
| website (ie http://example.com) | Check headers, see if http, if so iframe, otherwise provide link OR use https://github.com/aboustayyef/previewer OR https://github.com/kasp3r/link-preview |
| rdf | use https://github.com/vakata/jstree ? |
| xml | use https://github.com/vakata/jstree ? |
| json | use https://github.com/vakata/jstree or https://github.com/yesmeck/jquery-jsonview |
| geojson | same as json or recline preview |
| zip | will link to way we are already handling |
| shapefile | treat as zip for now |

The code for this should live in two places:
1. A separate PHP PSR-0 compliant library that takes the file input and generates the preview
2. A drupal module that provides a formatter and handling from different file types

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/recline/pull/17https://github.com/NuCivic/recline/pull/17
