### ISSUE TITLE
Ensure Data.json Validates with Default Content

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#478]
The Data.json file validates but only when the correct content is included. This includes items like "Access Level" that are not included in the default content. We have not updated the default content because we are moving to a different way of importing the default content in: #472 . Once that is in it will be easy to update the default content to include the items missing for Data.json validation with the default content.

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/dkan/pull/1259
