### ISSUE TITLE
Entity warning message

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#483]
Getting the following on the dev branch:

```
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 175 of /var/www/dkan_demo/webroot/includes/entity.inc).
```

![screen shot 2015-05-28 at 5 51 51 am](https://cloud.githubusercontent.com/assets/512243/7859892/27f2177e-050a-11e5-9dd3-7cab7450ceac.png)

**Comment by drkloc** [comment]
this is done. closing.
