### ISSUE TITLE
Stop the make file inception

### ISSUE THREAD

**Issue by frankcarey** [NuCivic/dkan#520]
There are way too many make files that are bing used to create dkan. Worse is that the dkan make file include sub makefiles, which can in turn include sub make files.

```
DKAN core (drupal-org.make)
  └ dkan_dataset.make
    └ leaflet_widget.make
    └ recline.make
  └ dkan_datastore.make
  └ panopoly_widgets.make
  └ panopoly_images.make
```

Similar issue with data_starter

```
TODO
```
#### Related Issues / PR
- [ ] Move dkan_dataset.make into dkan.make https://github.com/NuCivic/dkan/pull/511

**Comment by acouch** [comment]
Would there be a better way to do handle this without losing the ability for dkan_dataset and recline to be standalone modules? Otherwise the items from the make file from recline for example would need to be updated in two places.

**Comment by acouch** [comment]
We talked and agreed on @frankcarey 's plan.

**Comment by janette** [comment]
Several modules were consolidated into core and the make file simplified https://github.com/NuCivic/dkan/pull/1387
