### ISSUE TITLE
Recline page won't stop showing "Loading..." dialog above chart preview even though chart preview works beneath it

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#525]
Page: http://dev-city-of-townsville-open-data-portal.pantheon.io/dataset/oklahoma-demographic-and-economic-data/resource/4463e8fb-c4b6-4bc3-8488-512751b2274e#{view-graph:{group:!Year,series:[!Employed++Civilian++Labor++Force,!Unemployed++Civilian++Labor++Force],graphType:!bars,graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},currentView:!graph,graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}

Site: http://dev-city-of-townsville-open-data-portal.pantheon.io/

This is on a Pantheon site that was spun up a week ago. The "Loading..." box will not go away and the wheel keeps spinning. I am able to create charts underneath it though.

![screen shot 2015-06-25 at 4 52 47 pm](https://cloud.githubusercontent.com/assets/9059428/8366177/b48f8a6a-1b60-11e5-9f0b-b18082d4f6a4.png)

**Comment by janette** [comment]
CIVIC-508
https://github.com/okfn/recline/pull/474

Fixed!
