### ISSUE TITLE
Old group title remains in breadcrumbs after changing it; button needs padding

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#526]
After changing "Biking" to "Economics," the old group name stuck around in the navigation breadcrumbs until I flushed the cache.

Additionally, the "Remove" button is clustered a bit too close to the file name and doesn't look quite right.

![screen shot 2015-06-18 at 10 49 55 pm](https://cloud.githubusercontent.com/assets/9059428/8366550/d16a2476-1b63-11e5-8509-c5f3f22bb02f.png)

![screen shot 2015-06-18 at 10 49 21 pm](https://cloud.githubusercontent.com/assets/9059428/8366545/c76f0324-1b63-11e5-91cc-1ab3bae69329.png)

**Comment by janette** [comment]
Fixed
