### ISSUE TITLE
No preview of dataset

### ISSUE THREAD

**Issue by inxaoc** [NuCivic/dkan#533]
Hello

I installed DKAN, after uploading file I can't see a preview of dataset (like this: http://opencitykg6n5fbpbzjz.devcloud.acquia-sites.com/dataset/%D0%B1%D1%8E%D0%B4%D0%B6%D0%B5%D1%82%D1%8B-%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D0%B5%D1%80%D1%81%D1%82%D0%B2-%D0%B8-%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D1%81%D1%82%D0%B2-%D0%BA%D1%8B%D1%80%D0%B3%D1%8B%D0%B7%D1%81%D1%82%D0%B0%D0%BD%D0%B0-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B9-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5-2015-%D0%B3%D0%BE%D0%B4/resource/36ed0913)

**Comment by acouch** [comment]
Looks like this works on our Demo site: http://demo.getdkan.com/dataset/resource/ccca2087-2a8e-470e-89b1-eb1f144a3323

(will be removed tonight)

So having trouble diagnosing the issue. For some reason the pageViews aren't getting added: 

![screen shot 2015-06-29 at 11 03 39 am](https://cloud.githubusercontent.com/assets/512243/8412295/8f2feef4-1e4e-11e5-95d7-35beeebc812d.png)

**Comment by inxaoc** [comment]
ok, how to fix it on my server?

**Comment by janette** [comment]
@inxaoc please upgrade to the latest release https://github.com/NuCivic/dkan/releases
