### ISSUE TITLE
Include "adminrole" module

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#534]
Without the module "adminrole" you cannot easily give other users full permissions.

The "administrator role" feature included in Drupal 7 does *not* actually set all permissions to the chosen role.

With "adminrole", the role set as the "administrator role" always has all permissions set, making it much easier to grant full privileges to others.

**Comment by jonpugh** [comment]
#151 would have have to be fixed first. Adding "adminrole" to dkan out of the box gives the "Editor" role full permissions!

**Comment by jonpugh** [comment]
The pull request at #198 was merged but does not seem to work.

**Comment by jacintocapote** [comment]
Done and waiting pass tests https://github.com/NuCivic/dkan/pull/577

**Comment by dafeder** [comment]
This doesn't seem to be enabled in new site instals

**Comment by dafeder** [comment]
The hook_strongarm_alter() method doesn't seem to be reliable. I'm removing the variable from strongarm and setting in the hook_install and in a hook_update_n() function.
