### ISSUE TITLE
Fatal error when try add +2 groups on dataset

### ISSUE THREAD

**Issue by jacintocapote** [NuCivic/dkan#539]
On the activities for training with DKAN I installed a fresh installation on pantheon and when I try to create a dataset and associate to +2 organic groups a I get a fatal error because the limit is to 2 groups

**Comment by janette** [comment]
The limit no longer exists and I can assign as many groups to a dataset as I wish. However, the dataset layout only displays one group, we should think about how we want to handle multiple groups on a dataset node.

![d1___dkan](https://user-images.githubusercontent.com/314172/28132501-99102340-6702-11e7-8dcd-2503118a9947.png)

**Comment by kimwdavidson** [comment]
Looks like this issue has been addressed. We can file a new ticket if anyone reports an issue with displaying a single group. Closing. Thanks!
