### ISSUE TITLE
Cannot connect to datastore

### ISSUE THREAD

**Issue by BobHarper1** [NuCivic/dkan#546]
The datastore and previewer have previously worked well with our portal, however I'm now starting to encounter some problems. 

For example, on http://data.nicva.org/dataset/individual-giving-survey-2010/resource/547c6dda-564c-4401-b232-afec8838277c in Chrome while logged in as admin the buttons for the grid view appear but the data doesn't render. In IE when logged out I get the message 'cannot connect to the datastore' (so am therefore guessing it's not a problem with recline - some other resources are working fine, but  few are similarly affected. 

However, importing to the datastore appears to work fine. Problem seems only to be happening with the larger files (number of rows).

**Comment by janette** [comment]
@BobHarper1 we've made improvements to the datastore since you've reported this, could you test out the latest release https://github.com/NuCivic/dkan/releases and if you still find issues, create a new ticket.
