### ISSUE TITLE
"Social" block should be last in sidebar, "Data Extent" block should take its place (when enabled)

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#557]
"Social" block should be last in sidebar, "Data Extent" block should take its place (when enabled)

"Data Extent" is more relevant for users who'd like to use the dataset for GIS; no one uses Google+ and it's pretty easy to paste the URL into Facebook and Twitter without the widget.

Cross-referenced in HHS (https://github.com/NuCivic/healthdata/issues/311) but relevant to DKAN as a whole.

![wisconsinpage](https://cloud.githubusercontent.com/assets/9059428/8629018/82389662-2725-11e5-9607-3754fcf7104c.png)

**Comment by cienvaras** [comment]
PR: https://github.com/NuCivic/dkan/pull/733

**Comment by janette** [comment]
done
