### ISSUE TITLE
Views exposed form labels are hidden

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#559]
Currently exposed admin views have the title hidden: https://github.com/NuCivic/nuboot_radix/blob/7.x-1.x/assets/sass/partials/_view.scss#L136

This can be viewed by enabling admin_views:

<img width="1073" alt="screen shot 2015-07-15 at 9 15 08 am" src="https://cloud.githubusercontent.com/assets/512243/8700566/239493d0-2ad2-11e5-80f1-9e20ecc8f908.png">

**Comment by janette** [comment]
@acouch is this a contrib view? where can I get a copy?

**Comment by janette** [comment]
https://github.com/NuCivic/nuboot_radix/pull/34

**Comment by dafeder** [comment]
@janette can you provide a URL on the QA site that demonstrates the fix working?

**Comment by janette** [comment]
that QA site is gone, I have a bad feeling that merging the 630 branch, which was older than many updates that got in faster, may have overwritten the theme fixes that were created after 630 but merged before 630

**Comment by dafeder** [comment]
Believe this is fixed, but test and confirm to close.
