### ISSUE TITLE
Overriding the Sitewide features

### ISSUE THREAD

**Issue by robhardwick** [NuCivic/dkan#584]
We've been building a DKAN site for a client who have some additional requirements for the datasets search. Specifically they want to be able to search and facet over some custom fields we've added. The changes we've made are causing the Search API index in the `dkan_sitewide_search_db` feature to be overridden.

The question we have is how such changes should be managed so that we can integrate updates going forward. The two approaches we've considered are:
- Features Override - We've had issues with the reliability of overrides in the past
- Forking - This should be more reliable but pulling in upstream changes is time consuming

I'd appreciate any thoughts/insights you have on this.

**Comment by acouch** [comment]
Thanks for reporting this. We are working on documenting and sharing best practices.

**Comment by janette** [comment]
@robhardwick if your changes are minor you could copy `dkan_sitewide_search_db` to the sites/all/modules directory and make your changes there. Here is the latest documentation: http://dkan.readthedocs.io/en/latest/development/index.html

There is also a new tool for managing customizations you can read about here: http://dkan-starter.readthedocs.io/en/latest/introduction/dkan-starter-overview.html
