### ISSUE TITLE
Labels hidden when using Admin Views

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#587]
![ea847fca-2c97-11e5-8101-493d85b9d8eb](https://cloud.githubusercontent.com/assets/512243/8855395/93a4e086-312a-11e5-8a2c-b37473951851.png)

I made a local fix with the following:

```
.admin-views-view .views-exposed-form label {
  display: inherit;
}
.admin-views-view .views-exposed-form .views-exposed-widget .form-submit {
  margin-top: 1.6em;
}
```

Not sure if there is a better approach for all labels. This overrides what is in Nuboot Radix:

```
.views-exposed-form label { display: none; }
```

**Comment by janette** [comment]
fixed
