### ISSUE TITLE
@font-your-face: Font names get cut off - sizing should be responsive

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#598]
Font names are too big for their given boxes, should be resized accordingly.

![screen shot 2015-07-23 at 6 26 57 pm](https://cloud.githubusercontent.com/assets/9059428/8946788/b5fbc3b2-3561-11e5-9f76-b0a00afa3f4d.png)

**Comment by kimwdavidson** [comment]
Looks fixed. Closing
