### ISSUE TITLE
@font-your-face: 'Browse all fonts' link beneath main selection box should be a button, not link

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#600]
Link is oddly placed beneath selection box

See screenshots:

![screen shot 2015-07-23 at 6 24 56 pm](https://cloud.githubusercontent.com/assets/9059428/8947718/4b8a403e-356c-11e5-9748-60cac8926577.png)

![screen shot 2015-07-23 at 7 17 05 pm](https://cloud.githubusercontent.com/assets/9059428/8947745/a8c50b8a-356c-11e5-9abd-8537f8cda261.png)

**Comment by janette** [comment]
@stefaniefgray I think that would make it more confusing to the user. We could remove the link entirely as it duplicates the 'Browse all fonts' tab.
