### ISSUE TITLE
Enhancement: Appearance options button for list of themes shouldn't say 'List,' it should say 'Themes'

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#606]
"List" doesn't make much sense (what kind of list is it referring to?), but "Themes" would.

![screen shot 2015-07-23 at 6 56 26 pm](https://cloud.githubusercontent.com/assets/9059428/8958628/fa868b62-35d3-11e5-808f-852c7aa97e3a.png)

**Comment by kimwdavidson** [comment]
This is default Drupal behavior and to stay sustainable, unlikely worth the effort of overriding
