### ISSUE TITLE
Enhancement: Appearance page should include shortcut to site name and slogan options

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#607]
It's a bit confusing that you have to navigate to admin/config/system/site-information to change the site name and slogan, especially because they are a crucial part of the site's appearance.

It took me 5 minutes to find these options the other day, and I'm pretty good with DKAN. :disappointed: 

Could the "Appearance" page include a shortcut link or text boxes to allow users to readily access the site name and slogan settings?

**Comment by janette** [comment]
Done! https://github.com/NuCivic/dkan/pull/1719
Thanks @jacintocapote
