### ISSUE TITLE
@font-your-face: Button colors on options page do not match the rest of the page

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#609]
Every other button on my site now matches my Colorizer settings except for these two buttons in the middle of this page.

The blue buttons should match the brown buttons above.

![screen shot 2015-07-23 at 7 17 05 pm](https://cloud.githubusercontent.com/assets/9059428/8959120/1003faa8-35d7-11e5-92d9-4b669fdbc23c.png)

**Comment by janette** [comment]
Fixed
