### ISSUE TITLE
UI/UX: Slogan alignment beneath site name is uneven. Users should have option to modify slogan alignment.

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#611]
Slogan alignment on my QA site looks messy, regardless of font. The slogan is loading to the left of the site name, and I have no option to move it.

Users should have the option to left, center or right-align the slogan beneath the site name. If this were an option, I could have the slogan begin where the site name begins.

Additionally, it would be helpful for design geeks to allow for both the slogan and name to be moved to the center or right side of the page itself.

See screencaps:

![screen shot 2015-07-23 at 7 32 42 pm](https://cloud.githubusercontent.com/assets/9059428/8959364/68dcbc0e-35d8-11e5-8681-383dfeaf44af.png)

![screen shot 2015-07-23 at 7 34 42 pm](https://cloud.githubusercontent.com/assets/9059428/8959367/6c032684-35d8-11e5-961c-f6bfd21c88ec.png)

**Comment by dafeder** [comment]
New functionality. Next release!

**Comment by janette** [comment]
Alignment fixed, no new functionality.
