### ISSUE TITLE
@font-your-face: Have to flush cache to load fonts

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#613]
Every time you load a new font, you must flush all caches in order for it to load.

Otherwise, the font will revert back to the DKAN default font or whatever prior font the user was attempting to modify.

**Comment by dafeder** [comment]
Can you add steps to reproduce?

**Comment by jacintocapote** [comment]
Fixed. I created a patch to regenerate css after add a new rule https://github.com/NuCivic/dkan/pull/637

**Comment by stefaniefgray** [comment]
Every time you enable a font - regardless of if you're using it or not - all of the font previews turn to Times New Roman. The fonts were previously displayed properly.

**To replicate:**

- Go to @font-your-face, make sure no fonts are enabled or currently in use.
- Go to the browse fonts page.
- Those fonts will all be previewed accurately.
- Enable a font, any font.
- Keep browsing through fonts by clicking on page 2 or 3 to view more fonts.
- Those fonts will all be previewed as Times New Roman.

![screen shot 2015-08-12 at 3 10 35 pm](https://cloud.githubusercontent.com/assets/9059428/9235684/4431847a-410e-11e5-8384-ab45b5f9310c.png)

If you're using a font in <body> and then disable it, it will disappear everywhere on the site except for on the font selection page. On the font selection page, it will continue to display the <body> font you disabled.

**To replicate:**
- Enable a font, any font.
- Go to the CSS selectors dropdown for the font and choose "Everything (Body)"
- Save.
- Disable the font and make sure it is not in use whatsoever.
- Save.
- Go elsewhere on the site to verify that it's not being used.
- Go to the "Browse Fonts" page. The font will still be in use there.
- Clear the cache.
- Go back to the "Browse Fonts" page once more. The font will still be in use there.

![screen shot 2015-08-12 at 3 42 28 pm](https://cloud.githubusercontent.com/assets/9059428/9235827/2c9ae666-410f-11e5-8bed-f34d80a5bbf7.png)

![screen shot 2015-08-12 at 3 44 11 pm](https://cloud.githubusercontent.com/assets/9059428/9235859/5daee4a0-410f-11e5-934b-70a1be23226f.png)

**Comment by dafeder** [comment]
Need to come back to this and finish QA/deploy

**Comment by dafeder** [comment]
Fixed with #874 d9c0d42efd50ce453d1f1f87bef9dbeb2827a02d
