### ISSUE TITLE
Decouple OG

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#617]
It would be nice if users who didn't want organic groups at all could disable it completely. It can cause serious performance issues on large sites, and just adds a ton of complexity that most users could do without if they don't need "groups".

Right now `dkan_sitewide_perms_roles` depends on og, og_ui, and og_moderation.

Could we explore separating this out into a separate module?

**Comment by dafeder** [comment]
This was accomplished here: https://github.com/NuCivic/dkan_dataset/commit/18b6d357ec35cb72e3fc3b7dc213a585ec8d479b
