### ISSUE TITLE
`drush buildmanager-build`, not `drush buildmanager build`

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#619]
I'd do this myself if I had access to the docs site...

The wrong command is listed on the page http://docs.getdkan.com/dkan-documentation/dkan-users-guide/starting-and-managing-data-starter-based-project

It says 
>Running drush buildmanager build will perform the following tasks to update your DKAN site:

The command is `drush buildmanager-build`.

**Comment by dkinzer** [comment]
Fixed
