### ISSUE TITLE
DKAN tests failing on faceted search

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#621]
Something to do with the group facet?

https://travis-ci.org/NuCivic/dkan/builds/73577830#L1082

**Comment by jacintocapote** [comment]
Fixed. See https://github.com/NuCivic/dkan/pull/628. I used index alter to add the field when is enable dataset groups.

**Comment by jacintocapote** [comment]
Fixed last problems related with default status.

**Comment by janette** [comment]
Fixed https://github.com/NuCivic/dkan_dataset/pull/142
