### ISSUE TITLE
User images are blurry

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#658]
Clear images uploaded to user accounts are uploading blurry/fuzzy, even when uploaded at 85 by 85.

Fix is already in the new release but for existing projects, the update needs to be applied to DKAN_sitewide by whichever dev manages each site's code build.

![screen shot 2015-05-18 at 6 42 46 pm](https://cloud.githubusercontent.com/assets/9059428/7692526/551b559a-fd93-11e4-8e03-2ac222927cc7.png)

![screen shot 2015-05-18 at 6 43 36 pm](https://cloud.githubusercontent.com/assets/9059428/7692541/69399730-fd93-11e4-8f2f-2a6f6fb2f3f1.png)

![screen shot 2015-05-29 at 5 56 01 pm](https://cloud.githubusercontent.com/assets/9059428/7893491/6a1eb206-062c-11e5-87ed-52fc91408032.png)

**Comment by janette** [comment]
Fixed
