### ISSUE TITLE
Warning on install w/ visualization_entity

### ISSUE THREAD

**Issue by ergonlogic** [NuCivic/dkan#668]
When installing DKAN, we always see the following warning in the Drush output:

```
[...]
WD system: visualization_entity module installed.
WD system: visualization_entity module enabled.
WD features: Rebuilding visualization_entity / eck_entity_type.
WD features: Rebuild completed for visualization_entity / eck_entity_type.
Invalid argument supplied for foreach() entity.info.inc:151
WD system: recline module installed.
WD system: recline module enabled.
[...]
```

**Comment by acouch** [comment]
Thanks for noting this. AFAIK it isn't affecting the build but we should identify the issue.

**Comment by sidburgess** [comment]
@acouch 

**************************
Hi Sid,

I emailing to follow up on the bugs my team needs fixed. Can you provide us a status update on them?

https://github.com/NuCivic/dkan/issues/668

and

DKAN's issue with calculating averages from datasets, which affects the map-shading functionality. DKAN needs to be consistent about how averages are calculated, and missing values should be ignored, not counted as zeros.

Thanks,
Jonathan

-- 
Jonathan Goodwin
Project Assistant
Information and Communications Technology Programs
National Democratic Institute for International Affairs
nditech.org
*****************

**Comment by sheldonrampton** [comment]
Aaron, we've been asked to address both of these issues as part of our Managed Services contract with NDI. Can you tell us how long it will take to fix them and what timeline the client should expect?

**Comment by sheldonrampton** [comment]
Federica, I'm assigning this to you since it appears to be a ticket that is best handled by the Product Design & Engineering team. Can you let me know when your team will be able to do the work?

FYI, I think Aaron may have done some work as part of the North Dakota project on the issue with calculating averages from datasets, but I don't know if that work has gotten added back to DKAN.

**Comment by federicca** [comment]
We can definitely estimate and add to our backlog. however if it's a time-sensitive ticket I'm not sure we should be handling these in the future @sheldonrampton

**Comment by nditechteam** [comment]
Any updates on this issue? We need it addressed asap.

**Comment by ergonlogic** [comment]
using the access_control branch of visualization_entity appears to resolve this.

**Comment by janette** [comment]
Fixed.
