### ISSUE TITLE
Issues with search_api_db - table not found for index

### ISSUE THREAD

**Issue by dharizza** [NuCivic/dkan#670]
The problem we are having is the described here https://www.drupal.org/node/2436341

**Comment by janette** [comment]
@dharizza does this patch fix the issue? I'm not seeing different results after adding it...

**Comment by acouch** [comment]
@janette these are the steps that it should resolve: https://github.com/NuCivic/dkan_dataset/pull/149#issuecomment-136746405

**Comment by dafeder** [comment]
This issue has been identified and documented for other Drupal distributions using Search API. See release notes for the [Panopoly](https://www.drupal.org/node/2425263) and [OpenAtrium](https://www.drupal.org/node/2443025) distros on Drupal.org.

To fix, follow these steps after updating your database:

1. Go to /admin/config/search/search_api/index/datasets/edit to edit the database node index
2. Set the Server to "< No Server >" and Save. Your index will now show as "disabled."
3. Edit it again (by clicking "Edit" next to "Database Node Index") and set the Server back to "Database Server" and Save.
4. Click the "enable" link while viewing the resulting page, or edit the index again and check the "Enabled" box.
5. Once the index is enabled, you should see "0/[total] Indexed" on the index page. Click "Index Now" at the bottom of the page to re-index all your datasets.
6. Repeat for any other indexes you have running on a database server.

These instructions will be included in the notes for the next release.
