### ISSUE TITLE
Resource list needs theming

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#672]
The resource list below each individual resource needs to look better. In the least the "active" flag should be respected:

<img width="1187" alt="screen shot 2015-08-28 at 2 33 26 pm" src="https://cloud.githubusercontent.com/assets/512243/9555656/158cd84e-4d94-11e5-9345-4770faa15c56.png">

**Comment by janette** [comment]
look at list-group or some way to jazz it up

**Comment by janette** [comment]
https://github.com/NuCivic/dkan/pull/657#issuecomment-133908086

**Comment by janette** [comment]
https://github.com/NuCivic/dkan/pull/680

Acceptance test on the PR
https://github.com/NuCivic/dkan_dataset/pull/151

**Comment by janette** [comment]
in Mars hands now

**Comment by acouch** [comment]
Looks like this wasn't merged yet.
