### ISSUE TITLE
Make the download button work for both linked and uploaded files.

### ISSUE THREAD

**Issue by dkinzer** [NuCivic/dkan#675]
With data harvest online a lot of the resources for datasets are linked.  Currently the download link only works for uploaded files.  However, as a user when I see a download button I expect it to work.

![slack-imgs com](https://cloud.githubusercontent.com/assets/444215/9608815/3272b1ce-509e-11e5-9304-431b23f6d93e.png)

Two suggested solutions are:
1.  Make "Download" button work for both linked and uploaded files.
2. Only display "Download" button if there is a download.

A combined solution is probably best.

**Comment by janette** [comment]
Fixed! remote files can be downloaded.
