### ISSUE TITLE
DKAN install fails with error "IllegalArgumentException: Points of LinearRing do not form a closed linestring"

### ISSUE THREAD

**Issue by jimcraner** [NuCivic/dkan#678]
I tried to install DKAN (7.x-1.x, 02 Sept 2015) via the drush make build method and by installing the "pre-made" drop version and got the same error each time:

"IllegalArgumentException: Points of LinearRing do not form a closed linestring"

When installing via drush make, this error causes the installation to terminate.  Stack trace output pasted at the bottom of this ticket.

When installing via pre-built drop, this error occurs on the installation screen in the "Cleanup" phase, _after_ entering the site name, admin email, default country and timezone, etc.

In either case, no information is available in the Apache log.

When installing via pre-built drop, the site _does_ seem to be created, but I'm not sure if any resulting errors are because of an installation problem.

Thanks!
Jim

Starting Drupal installation. This takes a while. Consider using the        [ok]
--notify global option.
WD php: Warning: Invalid argument supplied for foreach() in                 [warning]
entity_metadata_convert_schema() (line 151 of
/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/entity/entity.info.inc).
WD node: Exception: IllegalArgumentException: Points of LinearRing do not   [error]
form a closed linestring in GEOSWKTReader->read() (line 38 of
/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geophp/geoPHP/lib/adapters/WKT.class.php).
exception 'Exception' with message 'IllegalArgumentException: Points of     [error]
LinearRing do not form a closed linestring' in
/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geophp/geoPHP/lib/adapters/WKT.class.php:38
Stack trace:
#0

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geophp/geoPHP/lib/adapters/WKT.class.php(38):
GEOSWKTReader->read('POLYGON ((-90.4...')
#1 [internal function]: WKT->read('POLYGON ((-90.4...')
#2

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geophp/geoPHP/geoPHP.inc(73):
call_user_func_array(Array, Array)
#3

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geofield/geofield.module(193):
geoPHP::load('POLYGON ((-90.4...', 'wkt')
#4

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/contrib/geofield/geofield.module(62):
geofield_compute_values(Array, 'wkt')
#5

/srv/example.com/dkan/build/dkan/webroot/modules/field/field.attach.inc(209):
geofield_field_presave('node', Object(stdClass), Array, Array, 'und', Array,
NULL, NULL)
#6

/srv/example.com/dkan/build/dkan/webroot/modules/field/field.attach.inc(914):
_field_invoke('presave', 'node', Object(stdClass))
#7 /srv/example.com/dkan/build/dkan/webroot/modules/node/node.module(1086):

field_attach_presave('node', Object(stdClass))
#8

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/dkan/dkan_dataset/includes/Dataset.inc(266):
node_save(Object(stdClass))
#9

/srv/example.com/dkan/build/dkan/webroot/profiles/dkan/modules/dkan/dkan_sitewide/modules/dkan_default_content/dkan_default_content.module(40):
Dataset->save()
#10 /srv/example.com/dkan/build/dkan/webroot/profiles/dkan/dkan.profile(71):

dkan_default_content_base_install()
#11 /srv/example.com/dkan/build/dkan/webroot/includes/install.core.inc(471):

dkan_additional_setup(Array)
#12 /srv/example.com/dkan/build/dkan/webroot/includes/install.core.inc(339):

install_run_task(Array, Array)
#13 /srv/example.com/dkan/build/dkan/webroot/includes/install.core.inc(77):

install_run_tasks(Array)
#14 /usr/bin/drush-7.x/includes/drush.inc(719): install_drupal(Array)
#15 /usr/bin/drush-7.x/includes/drush.inc(705):

drush_call_user_func_array('install_drupal', Array)
#16 /usr/bin/drush-7.x/commands/core/drupal/site_install_7.inc(80):

drush_op('install_drupal', Array)
#17 /usr/bin/drush-7.x/commands/core/site_install.drush.inc(289):

drush_core_site_install_version('dkan', Array)
#18 [internal function]: drush_core_site_install('dkan')
#19 /usr/bin/drush-7.x/includes/command.inc(359):

call_user_func_array('drush_core_site...', Array)
#20 /usr/bin/drush-7.x/includes/command.inc(210): _drush_invoke_hooks(Array,

Array)
#21 [internal function]: drush_command('dkan')
#22 /usr/bin/drush-7.x/includes/command.inc(178):

call_user_func_array('drush_command', Array)
#23 /usr/bin/drush-7.x/lib/Drush/Boot/BaseBoot.php(62):

drush_dispatch(Array)
#24 /usr/bin/drush-7.x/drush.php(70):

Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#25 /usr/bin/drush-7.x/drush.php(11): drush_main()
#26 {main}

**Comment by acouch** [comment]
@jimcraner great to hear from you. what version of drush are you using? what system is this on?

**Comment by jimcraner** [comment]
Hi @acouch :-)  This is on an Ubuntu 12.04 test system, running the latest Drush 7.0-dev.

If Drush fails like that, can I presume the web-based install method was successful and the rest of the "cleanup" procedures went OK, meaning the site is OK to use?

Any other info you would find helpful?

Thanks!

**Comment by janette** [comment]
Drush 8.x is recommended for the latest release (7.x-1.13.x)
