### ISSUE TITLE
New PHP-based datastore

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#686]
Our current datastore is limited architecturally because of the way in which it is based off of the feeds module. It uses unnecessary on node actions and can't be implemented without using Drupal, and has a lot of complexity for a relatively simple set of functions.

I'd like to create a new datastore that uses the https://github.com/ddeboer/data-import library for parsing, writing, and creating workflows. This library is simple to extend and would give us an easy API to not only parse more file types faster but also export in multiple formats as well.

This would be an independent library that uses PDO to connect to a database if Drupal isn't present. It wouldn't bootstrap Drupal to run imports from the CLI. We could completely turn off feeds module. Once ready this would be a drop-in replacement for the current datastore with additional features listed above.

I've started this effort here: https://github.com/NuCivic/datastore . I'll make it public once it is cleaned up enough.

**Comment by kimwdavidson** [comment]
New tickets are being created for this work. Closing.
