### ISSUE TITLE
Make navbar a region to allow normal block placement of user menu

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#689]
Currently the user menu block is hardcoded into the nav header:

In nuboot radix page.tpl.php:

``` php

          <!-- user menu -->
          <?php
            $block = block_load('dkan_sitewide', 'dkan_sitewide_user_menu');
            if($block):
              $user_menu = _block_get_renderable_array(_block_render_blocks(array($block)));
              print render($user_menu);
            endif;
          ?>
```

A customer asked to move this menu to the footer, but we can't without changing this code.

**Comment by janette** [comment]
https://github.com/NuCivic/nuboot_radix/pull/84

The user menu in the navbar can now be disabled via the theme settings page.
