### ISSUE TITLE
Improve leaflet widget (data extent) field UX

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#696]
Give users easier way to input point data or chose from US states, countries, etc.

**Comment by dafeder** [comment]
I'd like to change some wording, add the countries list and document. @federicca have you taken a look at this?

**Comment by janette** [comment]
Improved!
https://github.com/NuCivic/leaflet_draw_widget/pull/9
https://github.com/NuCivic/leaflet_draw_widget/pull/10
