### ISSUE TITLE
About Harvesting logic CKAN to DKAN

### ISSUE THREAD

**Issue by takuya310** [NuCivic/dkan#701]
We are migrating the whole data of a portal site from CKAN to DKAN.
Through migrating the site, we have two questions below.

1)What is the difference between the [group] and [organization]
CKAN has [group] and [organization].
Group means the tag to administrating some datasets at once in CKAN.
So, we are thinking we can ignore them to Harvesting the data to DKAN.

_We recognize the [group] in DKAN will be the same function in [organization] in CKAN.
So, we are thinking about Harvesting the [organization] of CKAN to [group] of DKAN._

_In the logic of Harvesting the DKAN migrate base module group, it will harvesting the CKAN group.
   Is that means the [organization] in CKAN is the same function of [Group] in DKAN?
   Is there any reason to not to use [organization] in DKAN? 
   ※ We think, the reason is its enough to admin them with [group]._

2)About harvesting the users

We wonder whether we need to Harvesting the users or not.
We are thinking about harvesting the users through the methods below:
_oraganization_list method of CKAN API
oraganization_show method of CKAN API_

Is there any plan to implementing the logic to Harvesting the users of CKAN?

Thanks.

**Comment by Vanuan** [comment]
@takuya310 how do you plan to implement it? DKAN doesn't provide write API.

**Comment by takuya310** [comment]
@Vanuan 
DKAN can use Drupal migrate module as "Harvesting".
Module is here.
https://github.com/NuCivic/dkan_migrate_base

**Comment by kimwdavidson** [comment]
Added Harvester functionality! Considering this complete. Closing. Thanks!

**Comment by fishfree** [comment]
@takuya310 @kimwdavidson Hello. I enabled the modules migrate & migrate_ui & dkan_migrate_base in the latest 7.x DKAN, then accessed /admin/content/migrate, I don't know which to use to harvest from CKAN. Could you share a little more detailed info, pls?
![image](https://github.com/GetDKAN/dkan/assets/1741341/bff4c0e4-4baf-4139-a2b0-5e508c2abd04)
