### ISSUE TITLE
Getting blank pages on node/%node/draft.

### ISSUE THREAD

**Issue by dkinzer** [NuCivic/dkan#705]
There is an open issue at https://www.drupal.org/node/2123343 that describes a problem with restws module and Workbench Moderation where restws processes the path and returns a blank page with 404 status.

The current fix is to apply a patch as done here:
Refs:
https://github.com/NuCivic/dkan_workflow/pull/5
https://github.com/NuCivic/data_workflow/pull/34
https://github.com/NuCivic/healthdata/pull/459

This issue may may not be affecting DKAN currently, but I'm adding it because it has been seen at least twice before in our projects.

**Comment by janette** [comment]
Fixed! https://github.com/NuCivic/dkan_workflow/pull/5
