### ISSUE TITLE
Upgrade breaks logo on nuboot_radix subthemes

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#709]
I have a site using a subtheme of [nuboot_radix](http://github.com/NuCivic/nuboot_radix). The latest upgrade introduced svg support for logos but breaks my subtheme because it is looking for a `logo.svg` that doesn't exist.

We need

- [x] A quick fix for people already experiencing the issue
- [ ] An upstream fix in nuboot_radix

**Comment by dafeder** [comment]
This preprocess function fixed the issue for me. In my case I added it to my subtheme's `includes/structure.inc`.

```
/**
 * Implements template_preprocess_page().
 */
function mytheme_preprocess_page(&$variables) {
	$theme = variable_get('theme_default');
	if (theme_get_setting('default_logo')) {
		$variables['logo'] = '/' . drupal_get_path('theme', $theme ) . '/logo.png';		
	}
}
```

**Comment by janette** [comment]
PR https://github.com/NuCivic/nuboot_radix/pull/40
