### ISSUE TITLE
Change default language for Recline preview

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#713]
The description for the Recline preview is confusing for non-developers. I'm proposing changing to this:

<img width="710" alt="screen shot 2015-09-28 at 11 16 40 am" src="https://cloud.githubusercontent.com/assets/512243/10141498/7b7f449c-65d2-11e5-9214-5ac11365e186.png">

**Comment by acouch** [comment]
I've created a PR here: https://github.com/NuCivic/recline/pull/31

**Comment by janette** [comment]
The fix has been merged
