### ISSUE TITLE
"Command center" user page not enabled by default

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#714]
The command center menu is defined in the dkan_sitewide_profile_page module, but enabling this module may still leave the user page panel disabled. We should either

- add an update/install hook to `dkan_sitewide_profile_page.install`, or
- simply document that you may need to enable this page at `admin/structure/pages`

**Comment by jacintocapote** [comment]
@dafeder for me is working fine. If I have a environment with the feature disable and then I enable I can see the command center user page without enable. By default the page is enable see https://github.com/NuCivic/dkan/blob/7.x-1.x/modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page/dkan_sitewide_profile_page.pages_default.inc#L14. Can you provide me more information?
