### ISSUE TITLE
Improve responsiveness on resources

### ISSUE THREAD

**Issue by yohannaje** [NuCivic/dkan#720]
When you explore data on smaller screens the content doesn't behave responsively. It shrinks and the fields disarrange.
When you are actually seeing a map instead of a table, there's no actual way to see it.
![screen shot 2015-09-29 at 15 30 54](https://cloud.githubusercontent.com/assets/829179/10252031/54c7b406-690b-11e5-80c8-bb7895787fa7.png)

**Comment by janette** [comment]
Done
