### ISSUE TITLE
Broken toggle on mobile menu

### ISSUE THREAD

**Issue by yohannaje** [NuCivic/dkan#721]
When you click on the mobile menu it opens but it can't be closed. If you try to close it it keeps reopening itself.
![screen shot 2015-10-02 at 13 47 16](https://cloud.githubusercontent.com/assets/829179/10252179/2e000c50-690c-11e5-970f-75dbf5ad5e46.png)

**Comment by dafeder** [comment]
No longer an issue - fixed by jQuery update.
