### ISSUE TITLE
Allow enable/disable public view of group membership

### ISSUE THREAD

**Issue by sidburgess** [NuCivic/dkan#726]
As an administrator, I want to be able to enable or disable showing group membership that I am not required to expose group members to the public

![image](https://cloud.githubusercontent.com/assets/339939/10300034/604ee0f4-6ba6-11e5-84bc-751cbe716ebb.png)

![image](https://cloud.githubusercontent.com/assets/339939/10300040/6e35a93c-6ba6-11e5-80f9-fe45225f20a3.png)

**Comment by sidburgess** [comment]
Oklahoma requested this today during their weekly status call. They specifically requested the ability to hide the "Members" button. Seems like just enable/disable functionality for public group membership might make more sense than a UI solution. 

cc/ @jvitello

**Comment by janette** [comment]
Fixed! Anon users no longer have access to group members list https://github.com/NuCivic/dkan/pull/1943/files#diff-9550c00d0f096385b504319b4815df8aL303
