### ISSUE TITLE
WMS dataset import

### ISSUE THREAD

**Issue by gkouk** [NuCivic/dkan#727]
Hello,
I just want to ask you if there is a way in DKAN to import a dataset from a WMS service (Web Map Service) and if yes how can I do this? Furthermore in case that WMS could be imported, can DKAN show it somehow?
Thank you in advance,
George Koukas

**Comment by acouch** [comment]
hi @gkouk we are planning on supporting WMS in an upcoming release. The code is available with the PRs linked to this ticket if you are interested: https://github.com/NuCivic/dkan/issues/738

We are in the process of QAing, testing, and documenting before pulling into the 7.x-1.x branch.

**Comment by gkouk** [comment]
Hi, thanks for your reply. I will visit the link you provided and looking forward for this release.
