### ISSUE TITLE
Fix dkan-flaticon font to display on sites not using nuboot_radix

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#729]
## Description
Using the latest dkan_dataset 7.x-1.9:  file icons are broken if the site does not use the nuboot_radix theme. This would be an issue for existing sites that are adding dkan and already have a different theme in use.
<img width="462" alt="screenshot_10_14_15__11_32_am" src="https://cloud.githubusercontent.com/assets/314172/10490551/658c9e7c-7267-11e5-9b44-81a5783f13fc.png">

## Steps to Reproduce
1. Change the default theme to something other than nuboot_radix.
2. Navigate to a resource page
3. Confirm that the file type icon font is not rendering, a colored square will be seen

## Acceptance Criteria
- [ ] Navigate to the Appearance admin screen
- [ ] Select a default theme that is NOT Nuboot Radix and save the settings.
- [ ] Navigate to a resource page, confirm that the resource file icon is rendering properly.

## Test Updates
 n/a

## Documentation Updates
n/a

**Comment by muelheim-ruhr** [comment]
The problem is, that dkan-flaticon.css is not included.

If you add

drupal_add_css($path . '/css/dkan-flaticon.css');

to the function dkan_dataset_preprocess_html in dkan_dataset.module you will see the rendered icons.
