### ISSUE TITLE
Bug: Dataset search includes non-dataset content types

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#748]
## Description

Dataset search includes all content types. 

## Steps to Reproduce

1. Create a Data Dashboard
2. Go to /datasets
3. See it listed

### 
Search API's new bundle filter seems to fail randomly. A solution would be to update the search index to index content type dataset view to only allow datasets

**Comment by dafeder** [comment]
@acouch this is at odds with another proposal to make the "datasets" link simply go to a more genera search page with the bundle facet already set to "dataset" but able to be changed. Need some clarity on dataset browsing UX vs general sitewide search UX as we add more content types to DKAN.
