### ISSUE TITLE
Every page says "File not found."

### ISSUE THREAD

**Issue by cscott5288** [NuCivic/dkan#751]
I installed dkan using the drush instructions. 

git clone --branch 7.x-1.x https://github.com/NuCivic/dkan.git
cd dkan
drush make --prepare-install build-dkan.make webroot
cd webroot
drush site-install dkan --db-url="mysql://DBUSER:DBPASS@localhost/DBNAME"

Everything seemed to have installed correctly - I can see the home page (although the images aren't showing) but when I try to access another page, such as user login, I get "File not found." I have no clue where to start troubleshooting this as I've never encountered this error on a drupal site before.

**Comment by dafeder** [comment]
@cscott5288 sounds like you don't have clean urls turned on? Here are some guides for making them work:

https://www.drupal.org/node/256410
https://www.drupal.org/getting-started/clean-urls#enabling-7

**Comment by cscott5288** [comment]
Solved. I had put dkan in a subdirectory of the web root. The file system path doesn't start at the subdirectory but the web root. Not sure if this is intended functionality. With standard drupal, I'm pretty sure you can install the site in a subdirectory and and links to files will work.
