### ISSUE TITLE
Graphing Data: Duplicate columns

### ISSUE THREAD

**Issue by cscott5288** [NuCivic/dkan#752]
Suppose my data looks like this:

Date | Country | Fatalities
9/2/14 | United States | 2
9/8/15 | United States | 1
2/7/15 | United States | 9
2/7/15 | UK | 9
2/7/15 | Spain | 9
2/7/15 | Spain | 9

Is the intended functionality for the graph to combine all of the "United States" values on one Axis? That would seem to make the most sense but it seems dkan isn't doing that by default. It's creating a new "United States" entry for each data entry. 

Screenshot:
http://i.imgur.com/RBdmdpE.png

How do I combine "United States" so it just shows once on the axis?

**Comment by dafeder** [comment]
Hi @cscott5288 - that kind of aggregation is not currently possible in DKAN's data preview, which is what you're using. It can be done however by using a Chart Visualization. This functionality needs further documentation but basic instructions are here:

http://docs.getdkan.com/dkan-documentation/dkan-users-guide/visualizations
