### ISSUE TITLE
Problem with index dataset

### ISSUE THREAD

**Issue by jacintocapote** [NuCivic/dkan#784]
Sometimes the view based on the index dataset show another content type. Looks like we need to index content type field on the index and add the filter on the view.

**Comment by sheldonrampton** [comment]
Related Jira ticket: https://jira.govdelivery.com/browse/CIVIC-160

**Comment by dharizza** [comment]
This ticket is also related https://github.com/NuCivic/dkan/issues/748

**Comment by acouch** [comment]
This is a duplicate.
