### ISSUE TITLE
Adding Resource with Groups issue

### ISSUE THREAD

**Issue by FrancescJR** [NuCivic/dkan#785]
Hello, this is a complicated one, but I think you can reproduce that with a brand new installation of dkan and doing that: (you need at least one group present)
1. Create a Dataset and give it some group.
![selection_016](https://cloud.githubusercontent.com/assets/3223567/11386338/da55e2be-9363-11e5-8caa-ef69d4092c1e.png)
2. Add a resource from Dataset and also give it some group (any group, can be the same or a different one).

The result is this:
![selection_015](https://cloud.githubusercontent.com/assets/3223567/11386263/28a0fb76-9363-11e5-9589-dbdc44a07b6c.png)

It looks like the file was not uploaded, nor the resource linked to the dataset.

Notes: 
1.if you edit the same resource, and set it a group again, it will work properly. The issue only happens at adding time.
2. If the dataset has no group set, adding works properly too.

**Comment by acouch** [comment]
@FrancescJR What version of DKAN are you using? Is this on the 7.x-1.x branch or a point release?

**Comment by FrancescJR** [comment]
We were using version 7.x-1.9 But we did a test with 7.x-1.10 and it happened the same

**Comment by blauerberg** [comment]
@FrancescJR It looks like same problem https://github.com/NuCivic/dkan_dataset/pull/158

I think it is bug with dkan_dataset module.
You might be able to solve this issue with https://github.com/NuCivic/dkan_dataset/commit/90721749ad8c430f61e1fc30469734a231a1eb37

**Comment by dafeder** [comment]
Yes, there are a number of issues and PRs tracking this issue. Closing this, please refer to: #940 858
