### ISSUE TITLE
Cross-site scripting (XSS) vulnerability in /dataset page

### ISSUE THREAD

**Issue by grantdobbe** [NuCivic/dkan#790]
During routine security vulnerability scanning, it was discovered that DKAN is susceptible to a cross-site scripting attack. This has been confirmed on DKAN version 1.8; it is unknown if previous versions are vulnerable. It would be safe to assume that versions 1.9 and 1.10 are also affected.

## Steps to reproduce:
1. Load the main dataset page (e.g., http://www.example.com/dataset).
2. Inject the following as part of a GET request for example.com/dataset:
```'type%3Adataset"/><script>alert(512)</script>'``` into the value of parameter ```'f[0]'```
3. The page will be returned, and the Javascript alert will pop up in the browser window.

## Acceptance criteria
This bug will be resolved when random code submitted as part of a GET or POST request is not rendered by DKAN. This bug will most likely be resolved by applying better input sanitation to GET and POST requests.

## Test updates
We probably do not have a test for XSS vulnerabilities, so we will most likely have to write one or more tests to suit our purposes.

## Documentation updates
This vulnerability does not affect DKAN functionality, so documentation changes are probably not needed.

**Comment by topicus** [comment]
I can’t reproduce this.

I’m running this but no alert is being displayed

```http://demo.getdkan.com/dataset?f[0]=author:1"/><script>alert(512)</script>```

Do I missing something?

**Comment by topicus** [comment]
It seems like tags are properly escaped.

<img width="1275" alt="screen shot 2015-12-09 at 4 59 11 pm" src="https://cloud.githubusercontent.com/assets/381224/11697052/7f7ee0b4-9e96-11e5-8c6e-208d8c5496c1.png">

**Comment by grantdobbe** [comment]
It appears to be showing in older versions of DKAN. See my updates in JIRA.

**Comment by topicus** [comment]
@grantdobbe I've added a local patch while we wait facetapi maintainers to merge this change.

**Comment by dafeder** [comment]
You can see this vulnerability in FacetAPI by:

1. Enabling the module
2. Create a search page with facets
3. Then you can inject scripts through url params: http://example.com/search-page?f[0]=field_tags:<script>alert(512)</script>
4. Modern browsers like chrome refuses to execute this script because it's in the url but old ones like IE7 execute the alert.
