### ISSUE TITLE
Cross-site scripting (XSS) vulnerability in user profile pages

### ISSUE THREAD

**Issue by grantdobbe** [NuCivic/dkan#791]
During routine security vulnerability scanning, it was discovered that DKAN is susceptible to a cross-site scripting attack. This has been confirmed on DKAN version 1.8; it is unknown if previous versions are vulnerable. It would be safe to assume that versions 1.9 and 1.10 are also affected.

## Steps to reproduce:
1. Log in and load a user profile page (e.g., http://www.example.com/users/admin).
2. Inject the following as part of a GET request for example.com/users/admin:
```field_license%3ALicense%20Not%20Specified"/><script>alert(559)</script>``` into the value of parameter ```'f[0]'```
3. The page will be returned, and the Javascript alert will pop up in the browser window.

## Acceptance criteria
This bug will be resolved when random code submitted as part of a GET or POST request is not rendered by DKAN. This bug will most likely be resolved by applying better input sanitation to GET and POST requests.

## Test updates
We probably do not have a test for XSS vulnerabilities, so we will most likely have to write one or more tests to suit our purposes.

## Documentation updates
This vulnerability does not affect DKAN functionality, so documentation changes are probably not needed.

**Comment by sheldonrampton** [comment]
Dan reported that https://github.com/NuCivic/dkan/pull/836 fixes this issue.
