### ISSUE TITLE
Frame Phishing vulnerability in DKAN

### ISSUE THREAD

**Issue by grantdobbe** [NuCivic/dkan#792]
## Description

This is related to #790 and #791. During a security scan of a DKAN website, it was discovered that an iframe could be injected into a DKAN page, thus resulting in the ability for an attacker to hijack a user's browsing session.

## Steps to Reproduce
1. Load the main DKAN dataset page (e.g., http://www.example.com/dataset).
2. Inject the following into a GET request for the dataset page: ```'field_license%3ALicense%20Not%20Specified%27%22%3E%3Ciframe+id%3D555+src%3Dhttp%3A%2F%2Fdemo.test
fire.net%2Fphishing.html%3E'``` as the value of parameter ```f[0]```
3. The page will load with the iframe.

## Acceptance criteria
This bug will be resolved when random code submitted as part of a GET or POST request is not rendered by DKAN. This bug will most likely be resolved by applying better input sanitation to GET and POST requests.

## Test updates
We probably do not have a test for XSS vulnerabilities, so we will most likely have to write one or more tests to suit our purposes.

## Documentation updates
This vulnerability does not affect DKAN functionality, so documentation changes are probably not needed.

**Comment by sheldonrampton** [comment]
Dan reported that https://github.com/NuCivic/dkan/pull/836 fixes this issue.
