### ISSUE TITLE
Changing group title causes path alias to change

### ISSUE THREAD

**Issue by frankcarey** [NuCivic/dkan#797]
## Description

Updating the title of a group causes the path to change, which usually isn't what people want since it breaks inbound links. Currently this is causing step `Edit group as administrator` in `group.editor.feature` to fail. Though the test could be updated to get around this by only updating the body, this seems like a bug.
## Steps to Reproduce
1. Create a group and note the path alias
2. Update the same group and notice that the path alias changes instead of staying the same.

**Comment by janette** [comment]
I'm guessing if a group was renamed the expected behavior would be to have a matching alias but if not the user could uncheck the auto-alias feature to keep the old alias.

![demo_group_new___dkan](https://user-images.githubusercontent.com/314172/28186270-1e317e10-67e0-11e7-8fc1-1743a424b8c6.png)
