### ISSUE TITLE
IE issue: Incorrect font rendering on resource preview buttons

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#803]
## Description
When viewing a resource page on Internet Explorer (any version) the button titles are using the icon font rather than the default font.
![screenshot_12_7_15__12_03_pm](https://cloud.githubusercontent.com/assets/314172/11635196/b8308c9a-9cda-11e5-97ac-4b70fb6debf7.png)

## Steps to Reproduce
Using an IE browser, go to a resource page and view the preview buttons on the right side, confirm that the button text does not match the rest of the site.

## Acceptance Criteria
Using an IE browser, go to a resource page and view the preview buttons on the right side, confirm that the button text does match the rest of the site.

## Fix
There was a PR for this that was closed
https://github.com/NuCivic/dkan_dataset/pull/159

![screenshot_12_7_15__12_07_pm](https://cloud.githubusercontent.com/assets/314172/11635262/2cc1b87c-9cdb-11e5-9eee-d513292e8327.png)

**Comment by dafeder** [comment]
Just noticed that this happens on Firefox as well.
