### ISSUE TITLE
Rebuilding with 1.9-release moves Omega from theme directory to modules directory

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#806]
## Description
![screenshot_12_8_15__11_23_am-2](https://cloud.githubusercontent.com/assets/314172/11662939/ff515978-9d9e-11e5-8218-a6ddc676f3de.png)

## Steps to Reproduce
Create a local build of dkan 7.x-1.9 and you will see the omega theme in /profiles/dkan/modules/contrib/omega

## Acceptance Criteria
When I rebuild a website the omega theme should be removed & there should be a github repo with an omega theme, and this should be properly documented in the release notes.

## Fix
Update drupal-org.make file
```
; Themes
projects[omega][version] = 3.1
projects[omega][patch][1828552] = http://drupal.org/files/1828552-omega-hook_views_mini_pager.patch
projects[omega][type] = theme
```

**Comment by amcnally** [comment]
Do a test update to make sure this won't break anything.

**Comment by federicca** [comment]
We're removing this theme from DKAN. 
working on it for 7.1.13
