### ISSUE TITLE
"Tag" list only scrolls 10 entries

### ISSUE THREAD

**Issue by amcnally** [NuCivic/dkan#817]
I was entering a tag and the auto populate list came up as expected, offering a match for all of the tags using my keyword "inpatient". I scrolled through the list of 9 offered tags, then my cursor returned to the top of that of 10 tags only.

looking in the taxonomy for the Tag = inpatient there are 13, plus a few more scattered throughout the rest of the list. But the Tags list on a dataset only shows 10.

[ ] Tag list isn't scrollable beyond 10 entries when adding a tag to a dataset or other content (the autopopulate list)
[ ] Tags in the Taxonomy section are hard to navigate: there's no way to search for a tag, you have to scroll through the endless list
[ ] Pls add tag list scroll capabilities to the top of the screen as it is at the bottom to help advance pages. It's challenging to scroll to the bottom of the long list only to hit "Next" and have to do it all over again.
[ ] Scroll and search capabilities as above should be offered for every single list throughout the platform (taxonomies, groups, users, datasets, blogs, whatever)

![image](https://cloud.githubusercontent.com/assets/13420367/11725838/5a9f1d12-9f41-11e5-8671-0a45125ab14d.png)

**Comment by amcnally** [comment]
https://github.com/NuCivic/External-HHS/issues/290

**Comment by federicca** [comment]
Won't fix.
