### ISSUE TITLE
Move dkan modules downloaded via drush make to their own folder

### ISSUE THREAD

**Issue by frankcarey** [NuCivic/dkan#824]
There are 2 reasons for moving the "drush-make-downloaded" dkan modules into their own folders.

1) It's confusing when looking in that directory which are which. The .gitignore hides this too, making it even more difficult to know.

2) Drush make has an --overwrite flag which we should use instead of having to delete dkan module folders individually. However, the logic isn't perfect, and drupal ends up removing the entire dkan folder, such that you need to use git checkout to get them back.

I propose to move "make-downloaded" dkan modules into modules/dkan-contrib folder instead of modules/dkan. Should be a simple fix.

In core dkan, these modules are:
- dkan_dataset
- dkan_datastore

But data_starter probably has more of them. It might make sense to put all projects NuCivic "controls" in that folder, which would make it easier to understand as well.
### References:

https://github.com/drush-ops/drush/pull/1450

**Comment by janette** [comment]
Done, view documentation here: http://dkan.readthedocs.io/en/latest/introduction/maintaining.html#adding-additional-modules-or-features

DKAN modules can be found in `profiles/dkan/modules/dkan`
and contrib modules can be found in `profiles/dkan/modules/contrib`
