### ISSUE TITLE
Automatic upload / write API

### ISSUE THREAD

**Issue by Vanuan** [NuCivic/dkan#832]
So, what are the options if I'd like to harvest some data and upload dataset automatically to DKAN?
As I see, DKAN doesn't provide any write API.

**Comment by dafeder** [comment]
Hi @Vanuan. We have a REST API in the works that will allow this and will be added to the distro very soon. You can see our progress in the two PRs linked from issue #310.

Closing as duplicate, please add any comments or feedback to that issue. Thanks!
