### ISSUE TITLE
Preview button url starts with double language code

### ISSUE THREAD

**Issue by Kopec** [NuCivic/dkan#853]
URL for preview button od /dataset/<id> page starts with double language code, for example /cs/cs/dataset and therefore leads to 404 page.

**Comment by dafeder** [comment]
Hi @Kopec thanks for reporting, but I'm not seeing this bug - could you explain how to reproduce the problem?

**Comment by Kopec** [comment]
Hello, I made a screenshot of the error a list of internationalization plugins I have installed. I know PHP well, but I am a Drupal begginner (how do you export a proper list of modules anyway?) so I dont know what could I send you more, but tell me and I will try.

OK the upload here fails so I uploaded it to Dropbox: https://www.dropbox.com/sh/sxse0pq33dy462g/AADd7YFbXkzYgYSI_r59ZTxJa?dl=0

**Comment by dafeder** [comment]
Got it - see the problem and can reproduce. We'll work on a fix.

In terms of getting a full list, the `drush` command-line utility is the best way to do that, do you have that?

**Comment by Kopec** [comment]
Thank you very much! As of now I have unfortunately access only to file and
database, but if needed we may consult with our IT. We are using WAMP
environment, I believe drush is somehow possible even here.

If you would need any more info, we will be happy to help.

Martin

--
+420 728603082 :: www.smallhill.cz

2016-01-13 2:40 GMT+01:00 Dan Feder <notifications@github.com>:

**Comment by dafeder** [comment]
This has been fixed on the 7.x-1.x branch, and will be in the next stable release.
