### ISSUE TITLE
Group references incorrect after dataset creation

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#858]
This was reported in PR NuCivic/dkan_dataset#158. That pull request has too many issues to merge, but the underlying bug needs to be fixed:

There are some groups issues, to reproduce it follow the next steps:
1. Create a dataset, Dataset 1, link to "Group 1". Click "Add data".
2. Create a resource, Resource 1, click "add another".
3. Create a resource, Resource 2, click "save"

The problems are:

- [ ] Both Resource 1 and Resource 2 are not a member of Group 1
- [ ] A message pops up saying 
![9-17-2015 10-55-00 am](https://cloud.githubusercontent.com/assets/512243/10079536/407f3b9c-62b0-11e5-8b88-88cfdcc1e981.png)

Further issues:

 Steps:

1. Create new dataset, filling in the info including group
2. Add Data, chosing to use the API (external URL), filling out the info and selecting the group, Save and Add
3. chose to use API, using URL again), fill out the info and the group, Save and Add, 
4. chose to upload a file, selecting CSV, Save. Now when viewing the dataset, the first item the Download Data item is missing the descriptive text and the URL

**Comment by msolv** [comment]
This was fixed on the 'workflow' branch here: https://github.com/NuCivic/dkan/pull/952. The 'workflow' branch was merged with the dev branch already so the fix is available on 7.x-1.x.
