### ISSUE TITLE
Cannot reset password after using one-time login link

### ISSUE THREAD

**Issue by ergonlogic** [NuCivic/dkan#873]
When using a password reset link, we are redirected to the user's landing page. If we then try to change our password by visiting the account edit page, we are prompted for our old password (which we obviously don't have, or we wouldn't be using a password reset link).

This behaviour appears to be caused by a rule called "User dashboard page after login". It's part of the `dkan_sitewide_profile_page` feature.

**Comment by dafeder** [comment]
@ergonlogic having trouble reproducing this bug. What version of the codebase are you on?

**Comment by ergonlogic** [comment]
This bug was observed on 7.x-1.x at commit 9e0b7b2e0eac0c46a6faa1bc8c311527627649e1.

**Comment by dafeder** [comment]
OK, I see what you mean. You can use the one-time login link, but not actually change your password.

**Comment by dafeder** [comment]
@ergonlogic it's a bug in the dkan_sitewide_profile_page module, which provides an alternative layout when viewing one's own profile, which includes shortcuts to common user functions. We'll work on a fix; that module is slated for major changes or replacement soon anyway. In the meantime you could disable that module if you're not using it.

**Comment by poliveiraIPB** [comment]
This problem still occurs in:
Drupal	7.41
DKAN (dkan-7.x-1.x)

**Comment by dafeder** [comment]
@poliveiraIPB presumably you are using a version of DKAN from before this was fixed. "7.x-1.x" is a branch, not a version of DKAN. If you're not on a release tag, can you see the commit hash or date of your copy of DKAN?

**Comment by poliveiraIPB** [comment]
I have installed from dkan-drops-7

I think my dkan version is 7.x-1.10 2015-11-10.

**Comment by dafeder** [comment]
Upgrading to the latest version of dkan-drops-7 should resolve your issue @poliveiraIPB

**Comment by poliveiraIPB** [comment]
Ok, but at https://github.com/NuCivic/dkan-drops-7/releases 
the last release is from 30 Apr 2014

**Comment by dafeder** [comment]
Oops - missed this @poliveiraIPB. We haven't really been adding tags to dkan-drops-7, the HEAD just tracks DKAN releases. We should go back to tagging it though.
