### ISSUE TITLE
Keeping up with Radix -> 7.x-3.0-rc4 update to 7.x-3.2

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#879]
## Issue
1. NuBoot Radix is currently based on radix 7.x-3.0-rc4
2. Radix has released 7.x-3.2 as the recommended branch
    - this new version uses Gulp and no longer requires Compass gems.
    - the theme structure has changed http://www.radixtheme.org/articles/update-rc4-to-3/
3. Due to the changes listed above we will need to create a new point release of NuBoot Radix.
   -  If a legacy site is using a subtheme of nuboot_radix, it will need to stay on Radix 3.0-rc4 until that subtheme is updated to work with Radix 3.2
   -  A new version of Nuboot Radix 7.x-2.x needs to be created and renamed to use a single word name. Why you ask?  To install the tools needed for the new compile process you must run ```npm run setup``` AND capital letters and spaces are not allowed in the "name" field of package.json (https://docs.npmjs.com/getting-started/using-a-package.json). We could change the name to nubootradix, to fix that. But if we are renaming, it would be nice to simplify it to  Nuboot, or NuRadix.

**Comment by dafeder** [comment]
We've discussed and the name issue is really more a bug in the drush command - we can maintain the same name. Everything else sounds good - bring on the Gulp!

**Comment by janette** [comment]
currently using radix 3.3 - closing
