### ISSUE TITLE
OG Module fails to impose group visibility restrictions

### ISSUE THREAD

**Issue by Dylan-A** [NuCivic/dkan#888]
OG group module's group visibility doesn't seem to be restricting the ability to view the private datasets belonging to private groups to group members.

As you can see below, the Group is made private.
![group_pages](https://cloud.githubusercontent.com/assets/16041976/12667225/c34dc3d2-c66e-11e5-9721-0efd54d18682.PNG)

And then a new user (named: nongm) who is not a part of the group

![group_members](https://cloud.githubusercontent.com/assets/16041976/12667257/16b3960a-c66f-11e5-8431-bbfd0c079a7e.PNG)

Can see all the content in the group.

![bug](https://cloud.githubusercontent.com/assets/16041976/12667270/3038602e-c66f-11e5-819e-b4204cff8ae3.PNG)

All this after permissions are set to stop a non member from accessing the group contents.

![permissions](https://cloud.githubusercontent.com/assets/16041976/12667301/9d571d6c-c66f-11e5-92ef-7b8d5350bd31.PNG)

I would also like to add that making all these datasets public or private does not seem to be affecting this behaviour.

**Comment by janette** [comment]
@Dylan-A you would also need to add a selection rule to the group node-view variant 
Navigate to `admin/structure/pages/nojs/operation/node_view/handlers/node_view_panel_context_3/criteria`
and select **OG: user membership in group** 
and select the **Active** for State in group

![node_template___dkan](https://user-images.githubusercontent.com/314172/28175199-2a566b46-67b9-11e7-8e87-289aa1c289df.png)
