### ISSUE TITLE
Metadata should link hyperlinks

### ISSUE THREAD

**Issue by sheldonrampton** [NuCivic/dkan#889]
## Description

The metadata of DKAN datasets and resources often has fields for various hyperlinks such as “Agency Program URL,” “Technical Documentation,” etc. When hyperlinks occur in the metadata, they should display as clickable hyperlinks to the actual hyperlink destination. Currently to visit a hyperlink mentioned in the DKAN metadata, the user has to copy and paste the link into their browser. This subtracts from the usability of the platform.

## User Story

As a *website visitor*
I want to *see hyperlinks as clickable links in metadata fields on dataset and resource pages*
so that *I can easily visit all URLs provided in the metadata*.
 
## Tasks

Add a step to the formatting of metadata fields on dataset and resource pages (including "additional info" metadata as well as other metadata fields. The additional step should test the metadata field to see if it begins with "http://" or "https://". If so, the field is a hyperlink and should be displayed as <a href="$value">$value</a> instead of simply as $value.

## Acceptance Criteria
- When web links are added in metadata fields to datasets and resources, they result in clickable hyperlinks.

## Jira Ticket
CIVIC-2732

**Comment by sheldonrampton** [comment]
Note: This issue is a duplicate of
https://github.com/NuCivic/dkan/issues/820

I'm writing this ticket to clarify that URLs should become clickable hyperlinks for all metadata fields (not just "Additional info" fields).

**Comment by dafeder** [comment]
This has been added to the release-1-12 branch and will be included in the next patch release of DKAN, 7.x-1.12.6
