### ISSUE TITLE
[Fix included] No options available for field_odfe_bureau_code and field_odfe_program_code fields

### ISSUE THREAD

**Issue by rhabbachi** [NuCivic/dkan#901]
## Description
When an agency is selected to be used for the Bureau Code and Program Code fields on the Dataset node. 

Client original issue: https://github.com/NuCivic/usda-nal/issues/770
Client original PR: https://github.com/NuCivic/usda-nal/pull/806
PR to upstream: https://github.com/NuCivic/open_data_federal_extras/pull/6

## Steps to Reproduce
1. Install and enable open_data_federal_extras.
2. Select any agency in admin/dkan/bureu_agency
3. Try to add a dataset via node/add/dataset

Issue: **Program Code** and **Bureau Code** fields options are not available and the user cannot input any value.

![menu_068](https://cloud.githubusercontent.com/assets/1914306/12792827/e6a3a6ec-caad-11e5-8895-79f7254894bc.png)

## Acceptance Criteria
When selecting an agency for the Bureau Code and the Program Code fields. Those fields should be populated with the appropriate (ie. filtered) values for the user to select from.
 
## Test Updates
 No tests to update.

## Documentation Updates
Not needed.

**Comment by janette** [comment]
PR has been merged
