### ISSUE TITLE
/dataset page doesn't select "Dataset" by default

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#908]
## Description
There are a number of internal and external links to the /dataset search that exist in new DKAN sites and existing DKAN sites.

In many cases these links can't be changed.

Going to /dataset shows all content types which is confusing because the url is still /dataset and a new and unexpected behavior.

Changing the menu in the nav bar to /dataset?f%5B0%5D=type%3Adataset doesn't address current sites or existing links.

Making "Dataset" default on /dataset would solve the problem: http://drupal.stackexchange.com/questions/135280/facets-with-default

Ref: NCS-19

**Comment by dafeder** [comment]
Plan is on the next iteration to switch the page URL to /search and make /dataset redirect to /search?f%5B0%5D=type%3Adataset

**Comment by acouch** [comment]
Removing /dataset would break the /dataset search /dataset/dataset-name /dataset/dataset-name/resource-name URL schema.

Maybe doesn't matter. RIP.

Lets enable the dataset searcher at ``/admin/config/search/facetapi_pretty_paths`` so the url is ``/search/type/dataset`` which will make it look cleaner.

**Comment by dafeder** [comment]
I don't see how that would break the schema. The lower-level ones would still work, and the top-level one is still a menu item, it just redirects to `/search?f%5B0%5D=type%3Adataset`

Regarding pretty-paths, I agree, let's do this at the same time as we roll out the new /datasets menu item, and update the code I added here to expand active facets: b3b622dd0c80d37181b919f3c7a19b7a20ea3fa4
