### ISSUE TITLE
Use of undefined constant DKAN_FIELD_LANG

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#92]
Moved from https://drupal.org/node/2104187

@markaspot Could you review if the patch is still necessary and if so provide a pull request to nuams/dkan_dataset ?

Please do remember to cross reference to thiss issue from your commit  message (you could do that including nuams/dkan#92)

Thank you for contributing!!

**Comment by dafeder** [comment]
Pretty sure we don't need this anymore - we don't use DKAN_FIELD_LANG at all.
