### ISSUE TITLE
Warnings and notices when enabling visualization features

### ISSUE THREAD

**Issue by ergonlogic** [NuCivic/dkan#934]
On a stock DKAN 7.x-1.x platform, we see the following warnings and notices upon enabling  "Visualization Entity Choropleth Bundle" and "Visualization Entity Geojson Bundle":

Warnings:

> Warning in features rebuild of geo_file_entity_geojson_bundle. No module defines permission "eck view geo_file geojson entities".
> Warning in features rebuild of visualization_entity_choropleth_bundle. No module defines permission "eck view visualization choropleth_visualization entities".
> Warning in features rebuild of visualization_entity_geojson_bundle. No module defines permission "eck view visualization geojson_visualization entities".

Errors:

> Notice: Undefined index: geojson in get_bundle_admin_info() (line 145 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Notice: Undefined index: geojson in get_bundle_crud_info() (line 153 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Warning: Invalid argument supplied for foreach() in eck_entity_menu() (line 83 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Notice: Undefined index: choropleth_visualization in get_bundle_admin_info() (line 145 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Notice: Undefined index: choropleth_visualization in get_bundle_crud_info() (line 153 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Warning: Invalid argument supplied for foreach() in eck_entity_menu() (line 83 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Notice: Undefined index: geojson_visualization in get_bundle_admin_info() (line 145 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Notice: Undefined index: geojson_visualization in get_bundle_crud_info() (line 153 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).
> Warning: Invalid argument supplied for foreach() in eck_entity_menu() (line 83 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/eck/eck.entity.inc).

**Comment by ergonlogic** [comment]
Possibly related to this, Features is reporting conflicts between "Visualization Entity Charts" and "Geo File Entity Geojson Bundle".

**Comment by dafeder** [comment]
Thanks @ergonlogic will check this out

**Comment by janette** [comment]
Fixed. Will be part of 7.x-1.13
https://github.com/NuCivic/dkan/pull/1130
