### ISSUE TITLE
Remove admin theme setting from strongarm

### ISSUE THREAD

**Issue by dafeder** [NuCivic/dkan#936]
## Description

Having the admin theme in strongarm in a core dkan feature means that a subtheme will always have to override this setting. We should move this variable to an install function

## User story

As an admin user, I want to be able to set the admin theme to my custom subtheme and not have it revert to NuBoot Radix

**Comment by janette** [comment]
better yet set the admin theme = 'Default theme' so colorizer works as expected when a custom theme is used

**Comment by dafeder** [comment]
Yes!
