### ISSUE TITLE
Issues with choropleth_visualization

### ISSUE THREAD

**Issue by ergonlogic** [NuCivic/dkan#938]
When we create a choropleth visualization, the page will not scroll, nor does the leaflet map render.

I'm seeing this error on the javascript console:

> Uncaught ReferenceError: chroma is not defined

The Chroma JS library appears to be in the visualization_entity makefile here: https://github.com/NuCivic/visualization_entity/blob/master/visualization_entity.make#L19. It appears to be downloaded properly, ending up at `sites/all/libraries/chroma/`.

The problem appears to be that the script isn't be added to the page. Chroma appears to be configured the same as the Numeral lib, which _is_ being loaded on the page. The JS itself is available, when I visit the path directly at `http://<site_url>/sites/all/libraries/chroma/chroma.min.js`.

I managed to force chroma to be loaded on all pages by adding this line to `visualization_entity_choropleth_bundle.info`:

```
scripts[] = ../../../../../libraries/chroma/chroma.min.js
```

This resolved the JS console error, and allows the leaflet map to render on the page. However, we still cannot scroll, nor does there appear to be any choropleth layers added to the map.

**Comment by ergonlogic** [comment]
By reducing the zoom in the browser, we're able to see the map, despite the lack of scrolling. It looks like there is some sort of choropleth layer, but it doesn't appear to be re-sized along with the map, and so appears to move around as I scroll the map.

**Comment by ergonlogic** [comment]
It appears that the scrolling issue stems from https://github.com/NuCivic/visualization_entity/blob/master/modules/visualization_entity_choropleth_bundle/visualization_entity_choropleth_bundle.css#L4. Commenting-out that line results in a working choropleth layer representing the geojson data.

**Comment by acouch** [comment]
I created a PR to fix these issues: https://github.com/NuCivic/visualization_entity/pull/40 The team will review before merging.

**Comment by acouch** [comment]
There is an additional PR https://github.com/NuCivic/geo_file_entity/pull/9
