### ISSUE TITLE
Issues with geojson_visualization

### ISSUE THREAD

**Issue by ergonlogic** [NuCivic/dkan#941]
We're unable to get geojson visualizations to work.

Having already uploaded a geojson file as a geo_file entity, I first tried adding a resource simply pointing to that file URL. When I then visited `admin/structure/entity-type/visualization/geojson_visualization/add`, I got the following error:
```
Notice: Undefined index: und in visualization_entity_validate_file() (line 29 of /var/aegir/platforms/dkan-7.x-1.x_2016-02-12/profiles/dkan/modules/contrib/visualization_entity/includes/utils.inc).
```
Also, no resources appeared available in the select field. I then uploaded the file directly to the resource, and was able to create the geojson visualization entity. However, there was no visualization on the resulting page. The JS console showed some errors though:
```
Uncaught ReferenceError: Backbone is not defined  (recline.js?o2g89v:399)
Uncaught ReferenceError: L is not defined  (leaflet.map.zoomToGeometries.min.js:2)
Uncaught ReferenceError: L is not defined  (visualization_entity_geojson_bundle.js?o2g89v:7)
```

**Comment by acouch** [comment]
I created a PR to fix these issues: https://github.com/NuCivic/visualization_entity/pull/40
