### ISSUE TITLE
Better Theme Resources in Search

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#944]
## Description
Currently Resources show up on their own in Dataset searches. This looks OK for the demo content http://demo.getdkan.com/dataset?f[0]=type%3Aresource but in many instances resources are just the title of the file type "CSV" or "XLS" and have no description.

In the new dataset search that is very confusing because there is no context for these files.

<img width="1194" alt="screen shot 2016-02-15 at 4 28 40 pm" src="https://cloud.githubusercontent.com/assets/512243/13062021/3de64962-d401-11e5-92af-419290e286e1.png">

Two options to correct this would be to: 

1. remove resources from the content type list since they almost never provide adequate context, or 
2. theme the resource teaser so it includes the title of the dataset

## Update

For now, we're going with option 2, and will revisit the general issue of resources in the search results (the usefulness of which varies greatly by specific site) in a later release.

### User Story

As a site visitor, I want to see what dataset a resource in my search results belongs to, so that I can understand the context of my search results.

### Acceptance Criteria

* Should look similar to the existing groups reference element
* Use the dataset icon + name of the dataset
* Support resources that belong to multiple datasets

**Comment by janette** [comment]
## PR
https://github.com/NuCivic/nuboot_radix/pull/70
