### ISSUE TITLE
Rendered entity option not Available, while creating views for Solr search results

### ISSUE THREAD

**Issue by Dylan-A** [NuCivic/dkan#947]
Hi,

I have been trying to create a view containing rendered entities as search results using Search API Solr Search,

However while creating the views the rendered entity option does not appear in the format drop down.

for reference see:

My Search API Solr Search index based view options:

![i21](https://cloud.githubusercontent.com/assets/16041976/13111219/a864d538-d5aa-11e5-947b-a986b9b92958.PNG)

Vs. 

The default view options for index created using normal Search API:

![i22](https://cloud.githubusercontent.com/assets/16041976/13111233/bf125b7a-d5aa-11e5-9f01-2cc56e12c313.PNG)

Also I am able to index the full entity content as html while creating index with Solr server:

![i23](https://cloud.githubusercontent.com/assets/16041976/13111308/15183d28-d5ab-11e5-8cfb-d7e86251a692.PNG)

Am I doing something wrong, or is it just not possible to create a view with rendered entity result when using Solr search in DKAN?

**Comment by janette** [comment]
@Dylan-A this might help https://www.drupal.org/project/apachesolr_views_rendered_entity
