### ISSUE TITLE
multiple errors when installing DKAN 7.x-1.11

### ISSUE THREAD

**Issue by sheldonrampton** [NuCivic/dkan#949]
## Description
When installing DKAN on Pantheon, I see multiple errors, as shown in the screenshots below.

### First attempt

![pantheon_install_error_1](https://cloud.githubusercontent.com/assets/2838758/13152086/fc9e1582-d632-11e5-8ab4-10c959abd38b.png)

![pantheon_install_error_2](https://cloud.githubusercontent.com/assets/2838758/13152093/05e37862-d633-11e5-94f2-f0f75b42e58f.png)

![pantheon_install_error_3](https://cloud.githubusercontent.com/assets/2838758/13152096/0aad109c-d633-11e5-82f2-d9f15bb389c7.png)

![pantheon_install_error_4](https://cloud.githubusercontent.com/assets/2838758/13152102/0fd25cee-d633-11e5-89a3-c6d3c2c89ff3.png)

And after the installation completes, I get this when I visit the home page:

![page_not_found___test](https://cloud.githubusercontent.com/assets/2838758/13152111/1d424f74-d633-11e5-89da-af83f2953476.png)

### Second attempt

I experienced a somewhat different sequence of error when I tried the installation from GovDelivery's offices in St. Paul where I had a robust internet connection:

![pantheon_install_error_2](https://cloud.githubusercontent.com/assets/2838758/13152093/05e37862-d633-11e5-94f2-f0f75b42e58f.png)

![pantheon_install_error_5](https://cloud.githubusercontent.com/assets/2838758/13152665/dabcb11e-d635-11e5-83ee-d402603b6bfa.png)

![pantheon_install_error_6](https://cloud.githubusercontent.com/assets/2838758/13152672/e4814d0e-d635-11e5-89c2-f164124cb9ad.png)

Following completion of the second and third installation attempts, the homepage appeared normal.

## Steps to Reproduce

Create a new site in Pantheon. Look at what happens. Note 

## Acceptance Criteria

* Error messages should not appear during installation.
* The user should not see multiple messages that say, "The administrator role has been reset for all permissions."
* The home page should exist.
 
## Ticket Reference
CIVIC-1494

**Comment by dafeder** [comment]
I'm adding full testing of the GUI-based install to our release checklist, so this should be addressed on the next release.
