### ISSUE TITLE
Format of date filters becomes corrupted when filtering datasets

### ISSUE THREAD

**Issue by sheldonrampton** [NuCivic/dkan#976]
## Description
Format of date filters becomes corrupted when filtering by tags and format
 
## Steps to Reproduce
Instructions to reproduce: Click on Groups and then click on the Department of Transportation. Note the ‘Filter by date changed’ on the left. The dates look just fine. In the ‘Filter by tags’ section, click on the the ‘transportation’ tag. Now look at the ‘Filter by date changed’. The formatting appears to be messed up, the dates should look like they did before. Remove the ‘boundary’ tag and now click on ‘html’ format. The same problem will occur.

This has been confirmed on DKAN 7.x-1.10 and 7.x-1.11.

## Acceptance Criteria

* The "Filter by date changed" options for faceted search on Group pages should always look like dates, e.g., "February 4, 2016," not "17:04" or "16:__".
 
## Test Updates

##. Documentation Updates
 
## Ticket Reference
NCS-101

**Comment by dafeder** [comment]
Yes, this has been an issue for some time, thanks for flagging.

**Comment by janette** [comment]
Facet granularity setting is not captured by features

![screenshot_3_21_16__3_16_pm](https://cloud.githubusercontent.com/assets/314172/13933021/1686a3f6-ef79-11e5-916e-6acdcdf91989.png)
