### ISSUE TITLE
DKAN on ORACLE - 4095 CHAR issues

### ISSUE THREAD

**Issue by Fr3dY2** [NuCivic/dkan#983]
Hi,

I managed to compile PDO_OCI using Instant Client 11.2 and install the Oracle drupal module. Now the 'Oracle' database option appears when installing from install.php, but at some point it fails with the following error:

`CREATE TABLE {rdfx_vocabulary_details} ( "GID" number NOT NULL CHECK ("GID" >= 0), "LANGUAGE" varchar2(12 CHAR) NOT NULL, "LABEL" varchar2(255 CHAR), "DESCRIPTION" varchar2(4095 CHAR), CONSTRAINT "PK_RDFX_VOCABULARY_DETAILS" PRIMARY KEY ("GID", "LANGUAGE") ) (prepared: CREATE TABLE "RDFX_VOCABULARY_DETAILS" ( "GID" number NOT NULL CHECK ("GID" >= 0), "LANGUAGE" varchar2(12 CHAR) NOT NULL, "LABEL" varchar2(255 CHAR), "DESCRIPTION" varchar2(4095 CHAR), CONSTRAINT "PK_RDFX_VOCABULARY_DETAILS" PRIMARY KEY ("GID", "LANGUAGE") ) ) e: SQLSTATE[HY000]: General error: 910 OCIStmtExecute: ORA-00910: specified length too long for its datatype (/root/php-5.6.19/ext/pdo_oci/oci_statement.c:148) args: Array ( ) 
`

It seems it's trying to create **4095 CHAR** fields, but for Oracle the maximum value should be **4000**.

Regards,

**Comment by Fr3dY2** [comment]
OK, I manually edited the file: **profiles/dkan/modules/contrib/rdfx/rdfx.install** , replacing 4095 values with 4000.

However, near the end of the modules installation, I got the following error:

`An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://Server-IP/dkan/install.php?profile=dkan&locale=en&id=1&op=do StatusText: Service unavailable (with message) ResponseText: DatabaseTransactionNoActiveException: in DatabaseConnection->rollback() (line 1038 of /var/www/html/dkan/includes/database/database.inc).`


The error_log shows many errors:
```
...
...
oracle[1787]: error: SQLSTATE[HY000]: General error: 24344 OCIStmtExecute: OCI_SUCCESS_WITH_INFO: ORA-24344: success with compilation error
 (/root/php-5.6.19/ext/pdo_oci/oci_statement.c:148) create or replace function md5(p_buff varchar2)
return varchar2
as
begin
  return lower(dbms_crypto.hash(to_clob(p_buff), dbms_crypto.hash_md5));
end;


oracle[1787]: object includes/database/oracle/resources/function/md5.pls created with errors

oracle[1787]: error: SQLSTATE[HY000]: General error: 2303 OCIStmtExecute: ORA-02303: cannot drop or replace a type with type or table dependents
 (/root/php-5.6.19/ext/pdo_oci/oci_statement.c:148) create or replace type vargs as table of varchar2(4000 char);

oracle[1787]: object includes/database/oracle/resources/type/vargs/vargs.pls created with errors

oracle[1787]: creating object: includes/database/oracle/resources/package/drupal_timestamp/drupal_timestamp.plb
oracle[1787]: current dir: /var/www/html/dkan
oracle[1787]: trying to bind 4000 bytes...
oracle[1787]: error: SQLSTATE[HY000]: General error: 1461 OCIStmtExecute: ORA-01461: can bind a LONG value only for insert into a LONG column
 (/root/php-5.6.19/ext/pdo_oci/oci_statement.c:148) insert into bind_test values (?)
oracle[1787]: trying to bind 1332 bytes...
oracle[1787]: bind succeeded.
...
...
```


Does DKAN really support ORACLE as backend database (out-of-the-box)?

Regards,

**Comment by dafeder** [comment]
Hi @Fr3dY2. There are some early DKAN materials still circulating that mistakenly list Oracle as a supported platform. While the Drupal database abstraction layer does support Oracle, DKAN itself has never been tested and we do not support it. If you do get it working do let us know and submit any relevant pull requests.
