### ISSUE TITLE
DKAN Charts adding decimal point and digits to right of it

### ISSUE THREAD

**Issue by chrisodva** [NuCivic/dkan#985]
## Description

Source dataset values are whole numbers only, yet when creating a chart DKAN displays values with one digit to right of the decimal point. Beyond just looking odd, especially for charts with larger numbers where the tenths are not significant, it seems like DKAN should respect format in the source data.

## Steps to Reproduce

See example chart at http://dev-cod-dkan.getnucivic.com/visualization/ve_chart/1 with tenths place displayed.
See source data at http://dev-cod-dkan.getnucivic.com/dataset/us-national-foreclosure-statistics-january-2012 which is whole numbers.

## Acceptance Criteria

DKAN should match number format of source data.

**Comment by topicus** [comment]
@chrisodva there is a formatter select to choose the proper axes format. There is no way to guess the source format since they doesn't have types associated like in a database. CSV files doesn't say anything about the column data type.For example if you have $10,000 as value, is that a number or a string? To avoid such issues the axis formatter exists. 

However there is a bug related with this formatter not being saved after the second edition we are currently investigating.

**Comment by chrisodva** [comment]
Understood. However if the csv file includes a value or string of 10,000,
either way do we want it being represented on the chart as 10,000.0? That
is what I was pointing out - the extraneous digit to the right of the
decimal. If the CSV is 10,000.00, DKAN should copy that. If 10,000,
likewise. It shouldn't added anything to the format, right?

On Wed, Apr 13, 2016 at 4:47 PM, Mariano Carballal <notifications@github.com
> wrote:

> @chrisodva <https://github.com/chrisodva> there is a formatter select to
> choose the proper axes format. There is no way to guess the source format
> since they doesn't have types associated like in a database. CSV files
> doesn't say anything about the column data type.For example if you have
> $10,000 as value, is that a number or a string? To avoid such issues the
> axis formatter exists.
>
> However there is a bug related with this formatter not being saved after
> the second edition we are currently investigating.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/NuCivic/dkan/issues/985#issuecomment-209641540>
>



-- 
Chris
@chrisod

**Comment by topicus** [comment]
I don't have a working version at hand but I remember there is a format which doesn't include the decimal at right. Given the number 10 it should exists 3 available formats: 10, 10.1, 10.10
