### ISSUE TITLE
Margin adjustment boxes in Chart UI should be labeled

### ISSUE THREAD

**Issue by chrisodva** [NuCivic/dkan#986]
As a DKAN content creator, I need labels on the 4 margin editing boxes so that I know how to change a margin without guessing at which box controls which margin.

![edit chart cod dkan](https://cloud.githubusercontent.com/assets/3311209/13891771/84171b3c-ed29-11e5-915f-6abade5cd9f5.png)

**Comment by janette** [comment]
Fixed. We've added help text to the chart interface to assist users https://github.com/NuCivic/visualization_entity/pull/69
