### ISSUE TITLE
Download Data and Web Services resource links don’t properly work

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#990]
See: NCS-137 for complete conversation and screenshots. 

## Description: 
Download Data and Web Services and other resource links don’t properly work
## Severity: 
Medium
## Instructions to reproduce: 
In the above URL, the Download Data and Web Services titles, and their associated links & icons don’t properly work. For example, clicking on the Web Services title creates a page (see attached ‘File Type Null and Bad Link’ image). The Data icon links instead of a resource and there is the ‘File type null not support for preview’ message. And at the bottom of the page there is some information that hasn’t been there before, the list of resources, which should be removed as it’s confusing. In another example,  all of the title/icon links exhibit the same problem as the previous example. the Web Application title/icon has the same problem.
I think the solution to this issue is to disable the links on the icons and the titles of the resources, instead relying on the URLs that are associated with the buttons to the right of each resource. Having some links that work (Data Table) and the majority of the links not working, and having the link on Data Table title being the same as the Preview button associated with Data Table is could be very confusing to a user. If NuCivic sees a flaw in this thinking please let me know. I don’t see how we would lose any functionality by removing these links.

**Comment by jpasila** [comment]
![capture1](https://cloud.githubusercontent.com/assets/7002549/14297998/74c2c994-fb50-11e5-9bf2-1a92d846ada3.png)

**Comment by jpasila** [comment]
![go_to](https://cloud.githubusercontent.com/assets/7002549/14298022/8e5db422-fb50-11e5-9f1d-dd1e7f1c5085.jpg)

**Comment by jpasila** [comment]
![data_prev_unav](https://cloud.githubusercontent.com/assets/7002549/14298025/930d80c4-fb50-11e5-887a-43c140dca9d3.png)

**Comment by jpasila** [comment]
![failed_resource](https://cloud.githubusercontent.com/assets/7002549/14298038/9a54d8dc-fb50-11e5-9bbf-2c7a89f7468e.png)

**Comment by jpasila** [comment]
![go_to](https://cloud.githubusercontent.com/assets/7002549/14298123/1a632c68-fb51-11e5-93b5-f53931120da8.jpg)

**Comment by jpasila** [comment]
![resources](https://cloud.githubusercontent.com/assets/7002549/14298132/2466b2b6-fb51-11e5-92a1-01c8804aae66.jpg)

**Comment by jpasila** [comment]
![we_found_it](https://cloud.githubusercontent.com/assets/7002549/14298147/399ff318-fb51-11e5-9bbf-c9bd19bdcc70.jpg)

**Comment by jpasila** [comment]
![workflow1](https://cloud.githubusercontent.com/assets/7002549/14298205/9fd24082-fb51-11e5-84f7-edb03b87c46d.png)

**Comment by jpasila** [comment]
Upon further review we realized that we can't actually confirm if DKAN 1.11 fixed the issue. DKAN 1.11 is going to be released soon and it will take some time to upgrade the live sites. We estimate that this should be around the middle of February. Again we can't confirm that DKAN 1.11 will fix the problem but we believe it will. (Fritz commented in Jira 02.01)

**Comment by sheldonrampton** [comment]
This issue was determined to be a "working as expected/won't fix situation," so I've closed it.
