### ISSUE TITLE
Empty content when displaying HTML resource

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#991]
See; NCS-21 for full conversation
## Description

No content is displayed when viewing HTML page within a resource. 
## Steps to Reproduce

click on the ‘Web Page’ link to reproduce the problem as displayed on the attached image.
When clicking on the link, I think the contents of the HTML page should be displayed within the empty area.

**Comment by janette** [comment]
Resource previews have been fixed https://github.com/NuCivic/recline/pull/56
