### ISSUE TITLE
Missing recline options if the CSV is linked

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#992]
See; NCS-70 for comment thread as needed.
## Description

If the CSV file is linked instead of having been imported, the options to use the Recline views of chart, map, table are missing.
## Steps to Reproduce

Edit the Data Table resource 
You will see that there are no options to select how to display the data
## Acceptance Criteria

When linking a file for a resource I should see the recline options

**Comment by janette** [comment]
resolved
