### ISSUE TITLE
Disappearing hero image 

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#994]
See; CIVIC-246 for further details as needed

## Description:
 the custom hero image keeps disappearing and reverting to DKAN's default hero image.

## Steps to reproduce:
As part of the site update to DKAN 7.x-1.9, I have uploaded a custom hero image to the NuBoot Radix theme

However, the custom hero image keeps disappearing and reverting to DKAN's default hero image. I have tried re-uploading the custom hero image repeatedly, and it always reverts eventually to the DKAN default. The reversion does not happen immediately. It usually takes several hours before the reversion occurs.

As a workaround so that I do not have to postpone the code release of 7.x-1.9 to production  I can overwrite the default hero image inside profiles/dkan. This issue is therefore not a blocker or urgent. However, it appears that there is a bug in DKAN which should be fixed.

**Comment by jpasila** [comment]
![marine_scotland_data_publications](https://cloud.githubusercontent.com/assets/7002549/13928049/9d7374ac-ef6a-11e5-9c86-b4ced8fde6f3.png)

**Comment by janette** [comment]
This is fixed upstream https://github.com/NuCivic/nuboot_radix/pull/65

**Comment by dafeder** [comment]
This should be fixed by getting the code up to day. Re-open if not.
