### ISSUE TITLE
Can't delete dataset without entering data in required fields

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#997]
## Description
Client can't delete a dataset without entering data first.
Work around for now is to unpublish the dataset, but as we clean up the catalog that will leave a lot of unpublished, but not deleted, datasets in the data store.
## Steps to Reproduce
Visit the duplicate dataset "Radiation Emitting Product Corrective Actions and Recalls" and try to delete it. You will get an error message that says

until you enter data into the required fields.
## Acceptance Criteria
Users shouldn't have to enter data to complete a deletion.

**Comment by jpasila** [comment]
![clipboard-20160217-142152-792](https://cloud.githubusercontent.com/assets/7002549/13928536/6e32c772-ef6c-11e5-889e-92c4ea2fe2d8.png)

**Comment by jpasila** [comment]
![screen shot 2016-02-05 at 5 51 20 pm 1](https://cloud.githubusercontent.com/assets/7002549/13928544/730fb188-ef6c-11e5-9160-8c343bce0b3c.png)

**Comment by federicca** [comment]
won't fix. It's a core Drupal problem + edge case. 
Another workaround is to add random content in the required field before deleting.
