### ISSUE TITLE
Fivestar rating fields don't work on Resource content type

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#998]
see: CIVIC-767

When trying to add a Fivestar rating field to the Resource content type, I discovered a bug. Visiting a resource node and voting causes Recline visualizations to be duplicated on the page.
## Steps to reproduce
Install DKAN 7.x-1.10
Add the Fivestar, Voting API and Ajax Comments modules: drush dl fivestar votingapi ajax_comments
Enable the DKAN Dataset Voting module
Try out voting on the Dataset content type
For testing purposes, you'll want to allow yourself to vote on content that you have created. Go to admin/structure/types/manage/dataset/fields/field_rating and check the boxes for
Allow users to cancel their ratings.
Allow users to re-vote on already voted content.
Allow users to vote on their own content.
Go to dataset/wisconsin-polling-places and try using the Rating widget:
Vote
Refresh the page
Change your vote
Refresh the page again
Everything works!
Try voting on the Resource content type
Add a Rating field to the Resource content type:
Go to admin/structure/types/manage/resource/fields
Add existing field Rating with a form element Stars (rated while viewing). (Once again, check the boxes to allow users to vote on their own content, etc.)
Go to the Wisconsin polling places resource, e.g., dataset/wisconsin-polling-places/resource/e164f1c0-afea-4926-bb1c-a07a92357cf1
Try voting, changing your vote, etc.
Each time you do, a duplicate of the Recline visualization will appear on the page.
Reloading the page in your web browser will restore it to normal.

**Comment by dafeder** [comment]
We don't offer fivestar on resources OOB. I don't think we'll be fixing this.
