### ISSUE TITLE
Fix database exports 

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#999]
See: CIVIC-1329

##  Description

DKAN websites that are using the Backup and Migrate module to backup their database are generating backup files that incorrectly have an extension ending with .gz when in fact the database is not being gzipped. This has been noticed on two websites. I have not checked to see if it is happening on other websites.

## Steps to Reproduce

* Log in to website and visit the Backup and Migrate page.

* Click "Backup Now" to create a manual backup of the database.
* This will download a file with a name such as xyz-2016-02-10T13-50-33.mysql.gz
* The file will not unzip properly, and a command such as *tail xyz2016-02-10T13-50-33.mysql.gz* will show that the file contains uncompressed MySQL commands.
 
## Acceptance Criteria

* Clicking "Backup Now" should create a database backup that has been gzipped.

**Comment by dafeder** [comment]
We won't be using Backup and Migrate anymore.
